### ISSUE TITLE
Remaining GeoDan migration tasks

### ISSUE THREAD

**Issue by timlinux** [kartoza/IGRAC-GGIS#148]
Viewers from the old system:

https://apps.geodan.nl/igrac/ggis-viewer/viewer/go/public/default

In early Novemebr we should review the data in the old system and come up with a way to provide similar functionality.

We should follow up with GeoDan asking for documents from the old system:

- [x] The document store contained PDF's and metadata should be obtained from GeoDan.
- [x] Kartoza to try to batch import the documents into GeoNode.
- [ ] IGRAC will screen the documents and decide which ones to publish on GeoNode.

**Comment by timlinux** [comment]
To close this off:

* Admire please also share the original archives we got from GeoDan with the backups from their geoserver and pg
* Admire please share a backup of the current PG backend for GeoNode and all of the associated data files
@ArnaudIGRAC will store that on their own infrastructure and then we can close this issue

**Comment by NyakudyaA** [comment]
@ArnaudIGRAC You can download the backups from https://cloud.kartoza.com/s/M6xFZiDJYmmciBd
