### ISSUE TITLE
Add creation metadata to well form and organisation sharing

### ISSUE THREAD

**Issue by timlinux** [kartoza/IGRAC-GGIS#187]
![image](https://user-images.githubusercontent.com/178003/99382220-1b339b00-28c4-11eb-9c50-bcc13082ba35.png)

We should have a list of organisations where you can put ticks next to the organisations that should be able to view the well record.

![image](https://user-images.githubusercontent.com/178003/99382355-5930bf00-28c4-11eb-815b-729a25a1e7ce.png)

**Comment by ArnaudIGRAC** [comment]
After you give admin rights to one user for his organisation (in Django https://ggis.un-igrac.org/en/admin/gwml2/organisation/), where can this new admin manage the users within his organisation?

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
they can organize their organisation in here

User can click "Organisation" on the top-right 
![Selection_306](https://user-images.githubusercontent.com/4530905/110916966-f029f700-834b-11eb-9f73-32cbacac461f.png)

After clicked, they will see list of organisation
![Selection_307](https://user-images.githubusercontent.com/4530905/110917032-033cc700-834c-11eb-95ed-5c9c229e3b00.png)

Click an organisation and there will be a form to update the organisations and their users role
![Selection_308](https://user-images.githubusercontent.com/4530905/110917058-0d5ec580-834c-11eb-8f1d-c826a6ef7895.png)

**Comment by ArnaudIGRAC** [comment]
thank you Irwan!
