### ISSUE TITLE
Accessing the RAW GGMN database

### ISSUE THREAD

**Issue by timlinux** [kartoza/IGRAC-GGIS#211]
We have been discussing the GGMN import here. Just some background it seem that there are about 190 000 wells, 100 million measurements spanning 1977 - 2018. Obviously this is too much data to show all at once and we need a good segmentation strategy so that each user sees only a small part of the data.

For this reason, I propose that the staff / admin users cannot see all the data, but rather are treated like normal users and need to be associated to an organisation specifically to see its data.

We also have the issue that the imported data needs to be associated to a user. I have asked Dimas to try to migrate users and organisations from the GGMN - but we still need to confirm if the well and measurement data is each associated to a specific user and organisation. Currently Dimas is having issues with the GGMN site at https://ggmn.lizard.net/api/v3/ which seems a bit buggy and logging him out. We were wondering if it would be possible to ask them for a direct database access or a database backup like we did for the GGIS data?

## Data holdings

![image](https://user-images.githubusercontent.com/178003/101335541-3feeb300-3871-11eb-965d-ac26c1063d32.png)

## Strategy for preventing staff seeing entire dataset

![image](https://user-images.githubusercontent.com/178003/101335484-2baab600-3871-11eb-99f0-f8074e8c4d1f.png)

## Strategy for dealing with large datasets on charts, mobile etc

![image](https://user-images.githubusercontent.com/178003/101335617-598ffa80-3871-11eb-8683-63d3601c5d13.png)

**Comment by timlinux** [comment]
Thanks Claudia. All the missing data is imported on staging and after your review we can close this I think?

**Comment by clau1313** [comment]
Yes, I reviewed them and it's fine. I will close this now.
