### ISSUE TITLE
Batch upload form needs revision

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#217]
A. 
There is currently no option for the data provider to determine which other organizations can view the data or if the data is public.

B.
"Well Upload Form" should be "Batch Upload Form"
"Well Descriptors" should be "General Information" 
"Well Monitoring" should be "Monitoring data"

C.
Please also insert the following explanation text:
"The Batch Upload allows you to import several Well and Monitoring Data at one time. The Batch Upload currently supports the upload of General Information (i.e. identification and location of your data points) and Monitoring Data. Download the templates (put the download links here) and fill them in with your data, then simply upload these files. Don't forget to assign permissions on your data: is it public? which organisations can access the data?"

**Comment by meomancer** [comment]
this is done, when we face issue, we can raise ticket
