### ISSUE TITLE
Investigate CRS for global map layers

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/IGRAC-GGIS#225]
GeoNode natively supports a few CRS. We need to investigate what other CRS we can expose which works well for map layers

Possible candidates

* EPSG:54009
*

**Comment by meomancer** [comment]
could you check this @NyakudyaA or @seabilwe ?
is this ticket done?

**Comment by NyakudyaA** [comment]
> could you check this @NyakudyaA or @seabilwe ?
> is this ticket done?

I am checking @meomancer

**Comment by NyakudyaA** [comment]
@meomancer I do not see how the CRS is changing in the map viewers. Can you change the label for the CRS from `GK4` to the actual CRS `ESRI:54030`

Examples

EPSG:4326
![4326-1](https://user-images.githubusercontent.com/2510900/107323636-48e94400-6aaf-11eb-9904-2d7f7997bd8f.png)

EPSG:3857
![3857-1](https://user-images.githubusercontent.com/2510900/107323656-5acae700-6aaf-11eb-8869-7b3c10f3eab3.png)

Can you also add the other CRS which was mentioned by Gavin `EPSG:8857`

**Comment by dimasciput** [comment]
@NyakudyaA you can change the crs from here : 
<img width="513" alt="image" src="https://user-images.githubusercontent.com/1979569/107324260-5b2ca780-6ada-11eb-939e-2cde81257233.png">

**Comment by NyakudyaA** [comment]
Thanks @dimasciput the CRS is not working. It seems it's not compatible with the base map. So I think we should try the standard EPSG codes i.e `EPSG:8857` and remove the `ESRI:54030`.  Here is the error I see
![crs-fixes](https://user-images.githubusercontent.com/2510900/107325988-5e606d00-6ab3-11eb-9680-d6facb6ef3a9.png)

If you click on the scale the label should match the CRS being used

**Comment by timlinux** [comment]
Try this:

EPSG:8857
```
+proj=eqearth +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs
-180.00, -90.00, 180.00, 90.00
```

**Comment by dimasciput** [comment]
Hi @NyakudyaA , EPSG:8857 is using equal earth projection which is not supported in the proj4 library at the moment. Do you have any other alternatives?

**Comment by timlinux** [comment]
@ArnaudIGRAC we spent some time investigating this. Because we use OpenStreetMap for the base map, we are limited to using the current coordinate reference system for the base map so I think we have to stop here and close this issue. Creating our own base map to support a nicer projection would be a huge job so I don't recommend spending more time on this now.

**Comment by ArnaudIGRAC** [comment]
It is ok Tim, thanks. OSM basemap is also not the best looking one, so we could look for other options in the future.
