### ISSUE TITLE
uploading style

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#281]
I am uploading a style to a layer. The style uploads fine, except that it keeps the name of the previous style file. 
[test style.txt](https://github.com/kartoza/IGRAC-GGIS/files/5770751/test.style.txt)

**Comment by seabilwe** [comment]
Hi @ArnaudIGRAC, which of the following styles should be used by the https://ggis.un-igrac.org/layers/geonode_data:geonode:TBA_map_2020_02, excluding the harmonized_tbamap styles. 

![image](https://user-images.githubusercontent.com/56301949/106595021-99b2e700-655b-11eb-8187-536c0db0b06f.png)

**Comment by ArnaudIGRAC** [comment]
it should be TBA_map_2020_02 only

**Comment by seabilwe** [comment]
I have updated the style @ArnaudIGRAC 

![image](https://user-images.githubusercontent.com/56301949/106596101-3aee6d00-655d-11eb-890b-b0a176c5b71f.png)
 
![image](https://user-images.githubusercontent.com/56301949/106596602-edbecb00-655d-11eb-93bf-c03c8e925f4c.png)

**Comment by meomancer** [comment]
this is done, when we face issue, we can raise ticket
