### ISSUE TITLE
thumbnails halved

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#290]
I have a couple of layers where the thumbnail is halved. See for instance
![image](https://user-images.githubusercontent.com/64771599/103748872-068e9c00-5005-11eb-9fd7-24720f81ecda.png)
![image](https://user-images.githubusercontent.com/64771599/103748957-26be5b00-5005-11eb-885f-8e5d3d493e21.png)
I tried to reset the thumbnails a couple of times but it doesn't work.

**Comment by meomancer** [comment]
this is done, when we face issue, we can raise ticket
