### ISSUE TITLE
url addresses in metadata abstract

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#292]
Website addresses that I type in metadata don't display correctly
![image](https://user-images.githubusercontent.com/64771599/103762349-72c6cb00-5018-11eb-84a5-e26c04a42423.png)

**Comment by ArnaudIGRAC** [comment]
The issue is still there Irwan. All metadata that @seabilwe has updated here https://ggis.un-igrac.org/documents/?limit=5&offset=0&group__group_profile__slug__in=twap-sids have that issue. It seems to appear whenever you copy-paste links.

**Comment by meomancer** [comment]
hi @ArnaudIGRAC @seabilwe 
Please check my comment on this ticket before

so basically you need to clean the abstract as my description in
https://github.com/kartoza/IGRAC-GGIS/issues/292#issuecomment-763556823

Example of document that i have cleaned
https://ggis.un-igrac.org/documents/1577

You don't need to do "insert link", just put the link directly to abstract, it will automatically create link
![Selection_178](https://user-images.githubusercontent.com/4530905/106542181-e5529a00-6535-11eb-9383-65525dacd4ff.png)

**Comment by ArnaudIGRAC** [comment]
Thanks Irwan. The problem is that we get this issue whenever we copy paste an url. I can't believe that we need a manual fix whenever we copy-paste an url in the metadata. It is more probably an error in new GeoNode version, can you please check?

**Comment by meomancer** [comment]
ok @ArnaudIGRAC 
let me check it if we can fix it

**Comment by meomancer** [comment]
this is fixed in staging for now @ArnaudIGRAC 

here is example on staging that has same abstract
https://staging.igrac.kartoza.com/documents/1798

with 
https://ggis.un-igrac.org/documents/1578

**Comment by meomancer** [comment]
The fix already in production (1.1.1)
Please check this @ArnaudIGRAC
