### ISSUE TITLE
layers missing in map viewers

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#298]
Hi @seabilwe, I had a look at the SIDS viewer and several layers were missing:
twap_public:twap_sids_hydrogeological_tannspringdischarge
twap_public:twap_sids_hydrogeological_totgwvol
twap_public:twap_sids_socioeconomic_inducedrecharge
twap_public:twap_sids_socioeconomic_artificialrecharge
twap_public:twap_sids_socioeconomic_totgwabstraction
twap_public:twap_sids_socioeconomic_totgwabstraction
twap_public:twap_sids_socioeconomic_gwasbtractionagri
twap_public:twap_sids_socioeconomic_gwasbtractionagri
Please add these layers to the viewer. Also check the other viewers to make sure that all layers have been properly included.

**Comment by seabilwe** [comment]
The missing layers in the SIDS viewer: https://ggis.un-igrac.org/maps/1848 have been updated @ArnaudIGRAC
