### ISSUE TITLE
update keyword suggestions

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#305]
When entering keywords, I am suggested keywords that are no longer in use. See for instance
![image](https://user-images.githubusercontent.com/64771599/104180573-a38a7400-540d-11eb-917e-4b3778f74234.png)
Can you please change that?

**Comment by ArnaudIGRAC** [comment]
it doesn't work. Whatever keyword I try, I am unable to remove it from the list.

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
to delete keyword, we need to use delete action on the top of the list, not the bottom one

The top one @ArnaudIGRAC 
![Selection_043](https://user-images.githubusercontent.com/4530905/106999777-5b1a6800-67b9-11eb-9a0d-ff3fa8a02d83.png)

**Comment by ArnaudIGRAC** [comment]
thanks Irwan
