### ISSUE TITLE
metadata fonts and formatting

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#311]
The new GeoNode version offers several fonts and editing options for the abstracts. They don't seem to work however, e.g. you write some text in bold, it doesn'appear in bold. Can you please check and eventually ix it?

**Comment by meomancer** [comment]
this is already in production, please check this @ArnaudIGRAC

**Comment by ArnaudIGRAC** [comment]
just one last question: how can I make a line break in the abstract? Enter makes a new paragraph with a large space between the lines (see screenshot below)
![image](https://user-images.githubusercontent.com/64771599/107216179-af695600-6a0c-11eb-840c-e0813bba94ba.png)

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
To make new line without large space, you need to do "shift+enter", and it will make new line with no space
For that large space when we do "enter", that is a bug. It should not that large. I will check it.

So in conclusion:
1. To make new line without space, do "shift+enter"
2. To make new line with space (basically new paragraph), do "enter"

**Comment by meomancer** [comment]
this is fixed in staging : https://staging.igrac.kartoza.com/layers/groundwater:Groundwater_Well_GGMN
Will be deployed on 1.1.2

**Comment by meomancer** [comment]
this fix is deployed @ArnaudIGRAC to production
please check it
https://ggis.un-igrac.org/maps/1233
