### ISSUE TITLE
title of viewer cropped

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#324]
The title of this viewer is cropped in MapStore: https://ggis.un-igrac.org/view/basm
![image](https://user-images.githubusercontent.com/64771599/104906763-6c274480-5984-11eb-9071-12372a748d2f.png)

**Comment by dimasciput** [comment]
@meomancer fixed in staging
![image](https://user-images.githubusercontent.com/1979569/105937148-8ac5c380-6087-11eb-8992-f0c29b575247.png)

**Comment by meomancer** [comment]
this is fixed in staging

will be deployed using 1.1.1
