### ISSUE TITLE
identify data points on the map

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#333]
When you select a data point in the list https://ggis.un-igrac.org/view/well-and-monitoring-data, would there be an easy way to highlight it on the map or to zoom to this point?

**Comment by dimasciput** [comment]
@meomancer fixed in staging
![image](https://user-images.githubusercontent.com/1979569/105937087-72ee3f80-6087-11eb-85f1-2f5880ceb515.png)

**Comment by meomancer** [comment]
could you test it @ArnaudIGRAC 
will be deployed in 1.1.1

**Comment by ArnaudIGRAC** [comment]
Nice!
