### ISSUE TITLE
error Django layers

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#335]
I am moving some layers from TWAP group to TWAP-SIDS, in Django
I get this error message, do you know why? 
![image](https://user-images.githubusercontent.com/64771599/105704249-cee18880-5f0e-11eb-9748-c37b16bbde84.png)

**Comment by ArnaudIGRAC** [comment]
See this one for example
twap_public:twap_sids_socioeconomic_artificialrecharge

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
is this still an issue? i checked the layer is already in SIDS
https://ggis.un-igrac.org/layers/twap_public:twap_public:twap_sids_socioeconomic_artificialrecharge

**Comment by ArnaudIGRAC** [comment]
Solved! apparently by itself :)
