### ISSUE TITLE
Create simple page said that the website is down

### ISSUE THREAD

**Issue by meomancer** [kartoza/IGRAC-GGIS#337]
show static page tell website is down and put it on nginx replaced 503

**Comment by meomancer** [comment]
hi @ArnaudIGRAC @timlinux 
PR for this:
https://github.com/kartoza/IGRAC-GGIS/issues/337

Currently the page like this, maybe we can redesign with @MariaSolovyeva helps?
![Selection_126](https://user-images.githubusercontent.com/4530905/108168960-ac681700-712a-11eb-9245-5dd7d926dba9.png)

**Comment by ArnaudIGRAC** [comment]
it looks fine
