### ISSUE TITLE
Start graph in "yearly for all time" by default

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#341]
Is it possible to show the graph by default in "yearly for all time"? This is because in most of the cases we don't have data for the last 100 days (yet), and the graphs will appear empty by default.

![image](https://user-images.githubusercontent.com/36033176/105965612-ee4df200-6083-11eb-82f9-1325e1eb27f5.png)

**Comment by meomancer** [comment]
this is updated on staging
can you try it @clau1313 ?

**Comment by clau1313** [comment]
Hi @meomancer, I don't see the change. "Daily for last 100 days" is still the by default.

**Comment by meomancer** [comment]
ah, i'm sorry @clau1313 
i forgot to reload the server, it is updated @clau1313

**Comment by clau1313** [comment]
Thanks @meomancer, it is working.

Although in Chile I can't see any data. The graph is also quite strange:

![image](https://user-images.githubusercontent.com/36033176/106593628-55bae480-6551-11eb-8225-c1260cd69603.png)

You can see that even though the map is supposed to show "Yearly for all time", the horizontal axis shows time in hours (it appears like that by default). So it looks empty.

This happens in other countries as well (e.g. the Gambia)

**Comment by meomancer** [comment]
it doesn't show anything basically because:
- no measurement for that well
or
- no groundsurface elevation for that well

what well is this @clau1313

**Comment by clau1313** [comment]
Hi Irwan. All wells in the Gambia are supposed to have groundwater levels associated. For example, see below (screenshot of the old GGMN):

![image](https://user-images.githubusercontent.com/36033176/106607432-96235e00-6563-11eb-87b6-f52a565a2a91.png)

The same well in the new GGIS: https://ggis.un-igrac.org/groundwater/record/2428/ 

This makes me wonder if indeed all the measurements were migrated via the GGMN API. 


Also, this is an example of a well in Chile where the graph doesn't show anything, but has data:
https://staging.igrac.kartoza.com/groundwater/record/11101/

![image](https://user-images.githubusercontent.com/36033176/106608138-5446e780-6564-11eb-86a0-209787c4828c.png)

**Comment by dimasciput** [comment]
@clau1313 I just checked again, and I couldn't get any measurements data via api for this particular well from ggmn server. So I don't know how they get these data from the system, I think it would be better if we can access the database directly.

**Comment by meomancer** [comment]
I'm going to close this issue because the issue that we disscuss in further is already different with this tickets

the ticket
https://github.com/kartoza/IGRAC-GGIS/issues/358
