### ISSUE TITLE
TWAP layers without style

### ISSUE THREAD

**Issue by seabilwe** [kartoza/IGRAC-GGIS#342]
Hi @ArnaudIGRAC , while I was updating the thumbnails and licenses I came across these two layers which use the GeoNode default style.

https://ggis.un-igrac.org/layers/igrac:igrac:twap_key_parameters
https://ggis.un-igrac.org/geoserver/web/wicket/bookmarkable/org.geoserver.web.data.layer.LayerPage?47

https://ggis.un-igrac.org/layers/igrac:igrac:twap_indicator_values
https://ggis.un-igrac.org/geoserver/web/wicket/bookmarkable/org.geoserver.web.data.layer.LayerPage?47

**Comment by ArnaudIGRAC** [comment]
Hi Seabilwe, I am not sure what these two layers are. I made them private, only admins can access them.
