### ISSUE TITLE
TWAP TBA sheets

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#345]
Dear Seabilwe, I would need your help to publish the TWAP TBA sheets in the document section. Attached is a list of all TBA sheets (there are 173). [TWAP sheets.xlsx](https://github.com/kartoza/IGRAC-GGIS/files/5879941/TWAP.sheets.xlsx)
You should find them all in the document section. If not, let me know those that are not there.

Open each TBA sheet (see example attached) and update the metadata as follow:
[AS108_20151215.pdf](https://github.com/kartoza/IGRAC-GGIS/files/5879945/AS108_20151215.pdf)

**Title:** bold title on top of the sheet, for example "AS108 - Buir Nuur-Khalkh River Aquifer"
**Abstract:** This Transboundary Aquifers information sheet has been produced as part of the Groundwater Component of the GEF Transboundary Water Assessment Programme (GEF TWAP). GEF TWAP is the first truly global comparative assessment of
transboundary groundwater, lakes, rivers, large marine ecosystems and the open ocean. More information on TWAP can be
found on www.geftwap.org . The Groundwater component of TWAP carried out a global comparison of 199
transboundary aquifers and the groundwater systems of 41 Small Island Developing States. The data used to compile this
transboundary aquifer information sheet has been made available by national and regional experts from countries involved
in the TWAP Groundwater project. For aquifers larger than 20 000 km2 and which are not overlapping, additional data are
available from modelling done by the Goethe University Frankfurt (Germany) as part of TWAP Groundwater. All data were
compiled by UNESCO-IHP and the International Groundwater Resources Assessment Centre (IGRAC – UNESCO Category II
Institute). Values given in the fact-sheet represent an approximate guide only and should not replace data obtained from
recent local assessments. The editors of this information sheet are not responsible for the quality of the data.
For more information on TWAP Groundwater and for more data, please have a look at the TWAP Groundwater Information
Management System which is accessible via http://twapviewer.un-igrac.org.
**Keywords:** Transboundary Aquifer
**Group:** TWAP - Transboundary Aquifers
**Regions:** the countries indicated next to _Countries sharing_, for example "Mongolia, China"
**License:** Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) (CC BY-SA 4.0)

**Permissions:** the sheets should be available to anyone (view and download)

**Thumbnail:** Take a snapshot of the first figure in the sheet and use it as thumbnail. For example:
![AS108](https://user-images.githubusercontent.com/64771599/105986633-7987b180-609d-11eb-92ed-efcfaa83d310.jpg)

Related all sheets to the map https://ggis.un-igrac.org/maps/1249

**Comment by ArnaudIGRAC** [comment]
small edit: don't consider the line breaks in the abstract and use www.twap.un-igrac.org instead of http://twapviewer.un-igrac.org.

**Comment by seabilwe** [comment]
All sheets have been updated @ArnaudIGRAC
