### ISSUE TITLE
TWAP SIDS sheets

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#346]
Dear Seabilwe, I would also need your help to publish the TWAP SIDS sheets in the document section. Attached is a list of all SIDS sheets (there are 47). [TWAP sheets.xlsx](https://github.com/kartoza/IGRAC-GGIS/files/5879941/TWAP.sheets.xlsx)
You should find them all in the document section. If not, let me know those that are not there.

Open each SIDS sheet (see example attached) and update the metadata as follow:
[Guam_final.pdf](https://github.com/kartoza/IGRAC-GGIS/files/5879961/Guam_final.pdf)

**Title:** bold title on top of the sheet, for example "GUAM ISLAND - GUAM"
**Abstract:** This SIDS information sheet has been produced as part of the Groundwater Component of the GEF Transboundary Water Assessment Programme (GEF TWAP). GEF TWAP is the first truly global comparative assessment of transboundary groundwater, lakes, rivers, large marine ecosystems and the open ocean. More information on TWAP can be found on www.geftwap.org . The Groundwater component of TWAP carried out a global comparison of 199 transboundary aquifers and the groundwater systems of 41 Small Island Developing States. The data used to compile this information sheet has been made available by national and regional experts from countries involved in the TWAP Groundwater project. All data were compiled by UNESCO-IHP and the International Groundwater Resources Assessment Centre (IGRAC – UNESCO Category II Institute). Values given in the fact-sheet represent an approximate guide only and should not replace data obtained from recent local assessments. The editors of this information sheet are not responsible for the quality of the data. For more information on TWAP Groundwater and for more data, please have a look at the TWAP Groundwater Information Management System which is accessible via https://ggis.un-igrac.org/view/sids.
**Keywords:** Small Island Developing State
**Group:** TWAP - Small Island Developing State
**Regions:** The name of the island, for example "Guam"
**License:** Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) (CC BY-SA 4.0)

**Permissions:** the sheets should be available to anyone (view and download)

**Thumbnail:** Take a snapshot of the map in the top left corner and use it as thumbnail. For example:
![image](https://user-images.githubusercontent.com/64771599/105988598-2cf1a580-60a0-11eb-8049-6c1493b20a1f.png)

Related all sheets to the map https://ggis.un-igrac.org/maps/1848

**Comment by seabilwe** [comment]
Hi @ArnaudIGRAC, please have a look at the SIDS sheets that I have updated.

The following sheets were not available:
- [ ] Aruba_Final_final.pdf
- [ ] C'Wealth of  N.M_final.pdf 
- [ ] Comoros_question.pdf
- [ ] filenames.txt
- [ ] Netherlands Antilles_final.pdf 
- [ ] New Caledonia_final.pdf 
- [ ] Sao Tome_final.pdf 
- [ ] St_Kitts_Nevis_final.pdf
- [ ] Trinidad and Tobago_final.pdf

**Comment by ArnaudIGRAC** [comment]
Nice Seabilwe, thank you. I noticed a (known) issue with url in the abstracts, I have asked Irwan to tackle this (#292). The missing layers are in the system:

> * [x]  Aruba_Final_final.pdf
Error (no further action required)
> * [ ]  C'Wealth of  N.M_final.pdf
https://ggis.un-igrac.org/documents/1567
> * [x]  Comoros_question.pdf
Error (no further action required)
> * [x]  filenames.txt
Error (no further action required)
> * [ ]  Netherlands Antilles_final.pdf
https://ggis.un-igrac.org/documents/1591
> * [ ]  New Caledonia_final.pdf
https://ggis.un-igrac.org/documents/1592
> * [ ]  Sao Tome_final.pdf
https://ggis.un-igrac.org/documents/1545
> * [ ]  St_Kitts_Nevis_final.pdf
Already done
> * [ ]  Trinidad and Tobago_final.pdf
https://ggis.un-igrac.org/documents/1594

Can you please finalize them?

**Comment by seabilwe** [comment]
Thank you @ArnaudIGRAC, I will finalise them

**Comment by seabilwe** [comment]
Hi @ArnaudIGRAC I have updated the last of the sheets.
