### ISSUE TITLE
Adjust background map in GGMN viewer (staging)

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#347]
Hi Irwan! 

When the GGMN viewer starts, the map appears like this:

![image](https://user-images.githubusercontent.com/36033176/106112841-0a1dca80-614e-11eb-990d-ad54b2c427c8.png)

Can you please center it, so it looks like this?:

![image](https://user-images.githubusercontent.com/36033176/106112913-1dc93100-614e-11eb-8814-4719b8da9798.png)

**Comment by meomancer** [comment]
Could you check this @dimasciput ?

**Comment by meomancer** [comment]
this is fixed @clau1313

**Comment by clau1313** [comment]
Great, perfect! Thanks
