### ISSUE TITLE
GGMN title is too long

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#348]
In staging, the title of the GGMN viewer looks like this:

![image](https://user-images.githubusercontent.com/36033176/106113074-5537dd80-614e-11eb-889e-4e33c6690e98.png)

Can you make it look as it is currently in the production version? Like this:

![image](https://user-images.githubusercontent.com/36033176/106113171-739dd900-614e-11eb-91d8-4282f2e0bf42.png)

or did you ask for this change @ArnaudIGRAC ?

**Comment by ArnaudIGRAC** [comment]
No, I didn't.

**Comment by meomancer** [comment]
hi @clau1313 @ArnaudIGRAC 
it is on staging? i'm the one who change it to provide @dimasciput for fixing long title in mapstore
let me rechange it
