### ISSUE TITLE
Resizing of global map when adding layers (staging)

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#349]
I added a layer to the GGMN viewer and the map resized to look like this:

![image](https://user-images.githubusercontent.com/36033176/106113906-430a6f00-614f-11eb-8313-145905e9deac.png)

Can the global map stays in its original size? I understand that it readjusts itself when the layer is smaller (i.e. zoom to layer) but when the layer is bigger I think it should stay as it is...

The layer is called "GP: Groundwater abstraction [m3/yr]"

**Comment by meomancer** [comment]
hi @dimasciput , could you check this? when layer GP: Groundwater abstraction is added, it is automatically zoom out (instead fit the map to the layer

**Comment by dimasciput** [comment]
![image](https://user-images.githubusercontent.com/1979569/106222154-8c22f780-6211-11eb-898a-0e466f0f1423.png)
@meomancer @clau1313 looks fine on my side

**Comment by meomancer** [comment]
hi @clau1313 
is this really needed? because that is behaviour of mapstore
when we add new layer, it will automatically zoom to the new layer
this is editor, not the map view, we can still make map to look like we want and save it manually

**Comment by clau1313** [comment]
I would like it, but if it is too much work, maybe we can leave it. @ArnaudIGRAC what do you think?

**Comment by ArnaudIGRAC** [comment]
I don't see it as a big issue excepted for global map viewers where we want the initial view set on global. I would wait for #225 to be sorted out first.

**Comment by clau1313** [comment]
@ArnaudIGRAC ok!

**Comment by meomancer** [comment]
can we close this ticket @ArnaudIGRAC @clau1313 ?
