### ISSUE TITLE
Embed link in wagtail gives error

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#353]
Hi @dimasciput, I wanted to embed a link in a test child page I created (Test Claudia) but I get the error "Cannot find an embed for this URL". It was just a YouTube video, but I tried other sites and it doesn't work either. What am I doing wrong? Thanks.

**Comment by clau1313** [comment]
Btw I just submitted the page for moderation

**Comment by dimasciput** [comment]
Thanks @clau1313 , I'll check it tomorrow.

**Comment by meomancer** [comment]
hi @clau1313 
this is fixed on staging
could you test it?

**Comment by clau1313** [comment]
It is working, thanks! One more question, how can I make it bigger? It looks tiny at the moment: https://staging.igrac.kartoza.com/about/test-claudia/

**Comment by meomancer** [comment]
ok @clau1313 
i will check it

**Comment by meomancer** [comment]
hi @clau1313 
this is fixed by @dimasciput 
could you check it?

Note: 
this is still on staging, will release it on 1.1.1

**Comment by clau1313** [comment]
Yes, it is solved, thank you.
