### ISSUE TITLE
Wagtail: bullet points and numbered list do not show in published page

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#356]
I created a test child page (Test Claudia). As you can see below, I group some text in bullet points and numbered list:

![image](https://user-images.githubusercontent.com/36033176/106592035-4a66b980-654f-11eb-99cb-a222d67401ea.png)

However, they disappear in the published version:

![image](https://user-images.githubusercontent.com/36033176/106592123-666a5b00-654f-11eb-82e1-ae17aff800e8.png)

What can I do?

**Comment by meomancer** [comment]
let me check it tomorrow @clau1313 
i think it is bug

**Comment by meomancer** [comment]
hi @clau1313 
this is fixed by @dimasciput 
could you check it?

**Comment by clau1313** [comment]
Yes, it is solved, thank you.
