### ISSUE TITLE
Getlegend text overflowing

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/IGRAC-GGIS#357]
A picture says a thousand words
![long-title](https://user-images.githubusercontent.com/2510900/106604379-3bd8cc00-6568-11eb-8bed-c0dc330f7121.png)

# Possible solution
Investigate getlegend extensions in GeoServer or fix in Geonode

**Comment by meomancer** [comment]
in geonode, it is just showing it using image
we could make the image fit to the place, but it will make the legend turns to be small

![Selection_181](https://user-images.githubusercontent.com/4530905/106683752-abe26300-65f7-11eb-9429-31ed4aa77705.png)

**Comment by meomancer** [comment]
hi @NyakudyaA 
do we still need to resolve it? (on geonode, it is impossible as per my picture)

**Comment by NyakudyaA** [comment]
I think it's not worth the effort so it should rather have a user fix the text in the SLD. And it's an edge case
