### ISSUE TITLE
Missing data for some of GGMN wells

### ISSUE THREAD

**Issue by meomancer** [kartoza/IGRAC-GGIS#358]
child of https://github.com/kartoza/IGRAC-GGIS/issues/358

Some of GGMN wells does not have:
- measurements : https://github.com/kartoza/IGRAC-GGIS/issues/341#issuecomment-771673977
- organisation : https://github.com/kartoza/IGRAC-GGIS/issues/332#issuecomment-771689817

**Comment by meomancer** [comment]
From @clau1313 :
https://github.com/kartoza/IGRAC-GGIS/issues/332#issuecomment-771564314

Could you create a csv or excell that have list of organisation and the country? after that we could create script to match organisation and the country and assign non-organisation well?

or is it possible fro ggmn? CC @dimasciput

**Comment by meomancer** [comment]
Mostly, fetch data through API of ggmn is not 100% good, because we don't know the connection or maybe the error when fetch it. The best way is accessing to database directly

this ticket basically related with: https://github.com/kartoza/IGRAC-GGIS/issues/211

CC @ArnaudIGRAC @clau1313

**Comment by timlinux** [comment]
To complete this:

* @meomancer generate a report listing wells with no measurement data
* @meomancer generate a report listing wells with no org

Share to @ArnaudIGRAC 

@clau1313 from IGRAC can then provide CSVs for missing wells

**Comment by ArnaudIGRAC** [comment]
Hi @clau1313 , could you share the csv files with the GGMN data in one big zip file?

**Comment by clau1313** [comment]
[GGMN data N&S.zip](https://github.com/kartoza/IGRAC-GGIS/files/5919586/GGMN.data.N.S.zip)

Hi guys, sorry for the delay. Here are the files as I got them from the old system. There is also a shapefile with the locations of all the wells that I got from the developers.

There is a couple of files that are empty, but I included them anyway, FYI.

Each CSV has 2 parts (2 tables). The first table is like this:

![image](https://user-images.githubusercontent.com/36033176/106770887-b07e3a00-663e-11eb-831d-f33d1dbac0be.png)

"uuid" is the ID of the well given by the system. "name" indicates if the well measures gw level above mean sea level (GWmMSL) or below ground surface (GWmBGS). "location_name" is the ID of the well given by us. x and y are the coordinates in WGS84.

The second table looks like this:

![image](https://user-images.githubusercontent.com/36033176/106771752-9abd4480-663f-11eb-8327-436b7080bd30.png)

"name" and "uuid" are the same as before. "timestamp" is when the measurement was recorded, and "value" is the actual measurement.

Please notice that not all wells are in here (I was unable to download the whole datasets from USA, Chile, Canada and Germany, because they are too big). However, I have them stored in our server in a different format (except Canada, because we got those data via the SOS connection). I will send you these datasets shortly.

**Comment by clau1313** [comment]
Here are the time series from the United States. They look like this:

![image](https://user-images.githubusercontent.com/36033176/106772897-c12faf80-6640-11eb-8e71-845811f762ab.png)

Please note that column C is the groundwater level (in meters) and column D the ID of the well. 

[levels USA.zip](https://github.com/kartoza/IGRAC-GGIS/files/5919781/levels.USA.zip)

The location of the wells is in this shapefile:

[usa_ggmn_shape.zip](https://github.com/kartoza/IGRAC-GGIS/files/5919789/usa_ggmn_shape.zip)

**Comment by clau1313** [comment]
In this .zip file you can find the groundwater levels from Chile + shapefile with the location of the stations. The format is the same as in the US files.

[gw levels Chile.zip](https://github.com/kartoza/IGRAC-GGIS/files/5919860/gw.levels.Chile.zip)

**Comment by meomancer** [comment]
hi @clau1313 @ArnaudIGRAC CC @timlinux 

Found the hard situation in here:

here is shapefile from claudia
This wells basically has 2 wells with different code:
**0000043001** and **NWP230001**

![Selection_050](https://user-images.githubusercontent.com/4530905/107195236-a8017700-6a23-11eb-9774-1259b32d7f57.png)

On the measurements files, there are just for **NWP230001**
So, measurement does not found for **0000043001**
![Selection_051](https://user-images.githubusercontent.com/4530905/107195377-d97a4280-6a23-11eb-940d-fd5c94d9e0b8.png)

Unfortunately, on our data in igrac that coming from ggmn API,
there is no **NWP230001**, instead, we have **0000043001**

![Selection_052](https://user-images.githubusercontent.com/4530905/107195481-fca4f200-6a23-11eb-9437-1d6a92708676.png)
![Selection_053](https://user-images.githubusercontent.com/4530905/107195490-fe6eb580-6a23-11eb-8998-3f556bc5946a.png)

So when we want to insert data for **NWP230001**, we can't insert it because on our system, the well that found is **0000043001**

So:
1. Are they different wells?
2. Should we put measurement for **NWP230001** to **0000043001**, so on our system, we have **0000043001** and have measurements from **NWP230001**
3. Or should we add rename **0000043001** to **NWP230001** and save it to system?

**Comment by timlinux** [comment]
As discussed today, @clau1313 proposes to merge all wells where one has measurement and the other has none if they share the same location and have similar idea.

**Comment by timlinux** [comment]
Further clarification: We can remove any GGMN wells that do not have any measurement data.

**Comment by meomancer** [comment]
hi @clau1313 
can you provide organisation vs country csv, so i can make script to assign organisation to well?

**Comment by meomancer** [comment]
hi @clau1313 
I already run the script to import monitoring from the csv
could you check it?
https://staging.igrac.kartoza.com/view/well-and-monitoring-data

**Comment by clau1313** [comment]
Hi @meomancer, I can't access to the site, I get the message "The connection has timed out".

**Comment by meomancer** [comment]
hi @clau1313 
i'm sorry, please wait, i'm still restoring staging site
and also please wait for mobile too (making mobile down)

**Comment by meomancer** [comment]
hi @clau1313 
it's up, please check it

**Comment by clau1313** [comment]
Hi @meomancer, I am exploring the wells in Chile and the US, but I don't see any groundwater levels. Regarding recently added data, I only see data from The Gambia. However, if I go to the GGMN viewer, I don't see the data for the Gambia either.

Also, I didn't realise that you need a CSV with organisation vs country, sorry. Do you still need it?

**Comment by meomancer** [comment]
ok @clau1313 
i will recheck it for Chile and US

hi @clau1313 
yes, i still need it

**Comment by meomancer** [comment]
Hi @clau1313 @ArnaudIGRAC  cc @timlinux 
I checked the chile and US has monitoring data

you can check example in here : https://staging.igrac.kartoza.com/groundwater/record/11238/
![Selection_118](https://user-images.githubusercontent.com/4530905/108160752-45436600-711c-11eb-9c0a-473fab8e5414.png)
![Selection_119](https://user-images.githubusercontent.com/4530905/108160783-512f2800-711c-11eb-8efb-3d7b4e3062f7.png)

But the problem why the chart doesn't show anything is becuase it doesn't has ground surface
![Selection_120](https://user-images.githubusercontent.com/4530905/108160804-61470780-711c-11eb-9271-27f39f995c0c.png)

I remember that we can't show chart if the elevation does not provided (i forget where the ticket)
and the shapefile and also the csv doesn't have this data elevation data

Should we still show the chart although the elevation is no provided?

**Comment by clau1313** [comment]
Hi @meomancer, thank you. I think there was a confusion regarding what graph not to show when the elevation is not provided. There are 2 cases:

1) A well has groundwater level data (either depth or elevation from sea level). Then, this data should be shown in the graph (even if the elevation was not provided)

2) There is a well that only has groundwater level as "water depth". Currently, if the elevation was provided, the system can calculate the gw level above sea level, and show a graph, right? The ticket you are referring is related to this case. In the past, when there was no elevation provided, it seemed that the system was still doing the calculation (to transform groundwater levels from water depth to elevation above sea level, considering an empty value of ground elevation). The result was that the same graph was shown for gw depth and elevation, which is wrong, and also, and it was not clear which one was the original.

What should happen is this:

1) If there is original gw level data, either as depth or elevation, it has to be shown in the graph.
2) If a well has only gw level as depth from the ground surface as original data, and the elevation of the ground surface IS NOT provided, the system should not calculate the gw level above the sea level, and no graph should be displayed for gw level above sea level. This means that in this case, the only graph shown should be the one with gw level as depth.
3) If a well has only gw level as depth from the ground surface as original data, and the elevation of the ground surface IS provided, the system can calculate the gw level above the sea level and generate a graph (this function is already implemented, right?).

Question: is the system showing one of the reference points always as default? (e.g. always show "water depth from ground surface" first? If so, could it be that, instead, the system always tries to show you the available graph? (e.g., if depth is not available, the system will show you "water level elevation a.m.s.l.)

If this is not clear we can have a call too.

**Comment by meomancer** [comment]
hi @clau1313 
This is updated on staging, please try it:
what it does:
will show data to the graph :
- if parameter from and parameter to are same
- if parameter from not same with to, and the elevation is provided, example: from ground, to top well, but top well is provided, show it
- if parameter to is a.m.s.l and parameter from does have elevation, example: from ground to a.m.s.l, but ground elevation is provided, show it

By default, parameter that is selected that the parameter that has data.

**Comment by clau1313** [comment]
hi @meomancer, thanks. It works well!
