### ISSUE TITLE
Update READme for IGRAC

### ISSUE THREAD

**Issue by meomancer** [kartoza/IGRAC-GGIS#361]

**Comment by ArnaudIGRAC** [comment]
Could we add an open license on the code? We usually use the Creative Commons Attribution-ShareAlike (CC BY-SA) for our products. What do you advise? @timlinux

**Comment by meomancer** [comment]
could you provide the best readme for this @ArnaudIGRAC @timlinux ?

**Comment by timlinux** [comment]
The GGIS is an interactive portal for sharing data and information on groundwater resources around the world. It gives access to map layers, documents, and well and monitoring data. It also contains several thematic map viewers.

Funded By

Contact Person

Screenshot

Code License

**Comment by timlinux** [comment]
Affero

https://en.wikipedia.org/wiki/Affero_General_Public_License


Creative Commons

https://creativecommons.org/share-your-work/


MIT

https://en.wikipedia.org/wiki/MIT_License

**Comment by ArnaudIGRAC** [comment]
Hi Tim, I had a look at the licenses and it reads as Chinese to me. All we want is that our work be acknowledged if reused (attribution). Better if derivatives are also free and open-source but we can also live with commercial derivatives. Can you please advise one license that matches these criteria?

**Comment by ArnaudIGRAC** [comment]
> The GGIS is an interactive portal for sharing data and information on groundwater resources around the world. It gives access to map layers, documents, and well and monitoring data. It also contains several thematic map viewers.
> 
> Funded By **the International Groundwater Resources Assessment Centre (IGRAC)**
> 
> Contact Person **ggis@un-igrac.org**
> 
> Screenshot **(a screenshot of the home page will do)**
> 
> Code License **(to be determined)**

**Comment by timlinux** [comment]
I suggest we go with the AGPL (https://en.wikipedia.org/wiki/Affero_General_Public_License)

**Comment by timlinux** [comment]
https://github.com/kartoza/IGRAC-GGIS/blob/develop/LICENSE - we now have a license!

**Comment by ArnaudIGRAC** [comment]
Thank you Tim
