### ISSUE TITLE
layer doesn't upload error 400

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#366]
Can you help me figuring out why this layer doesn't upload? I get the following error message: 
![image](https://user-images.githubusercontent.com/64771599/107242415-3b3eaa80-6a2c-11eb-92d3-5403ca928cfd.png)

[test3.zip](https://github.com/kartoza/IGRAC-GGIS/files/5944703/test3.zip)

**Comment by NyakudyaA** [comment]
I am on it @ArnaudIGRAC

**Comment by NyakudyaA** [comment]
I have managed to upload it.
![uploaded](https://user-images.githubusercontent.com/2510900/107244303-8bbb0580-6a36-11eb-8f8d-f9dfacd62770.png)

**Comment by ArnaudIGRAC** [comment]
it works on my side too now, strange... thank you

**Comment by ArnaudIGRAC** [comment]
Can you please also check this layer? I get the same error.
[Weathering_thickness.zip](https://github.com/kartoza/IGRAC-GGIS/files/5949872/Weathering_thickness.zip)

**Comment by NyakudyaA** [comment]
@ArnaudIGRAC I think I have found out why. I am going to pass this to @lucernae so that he can figure it out.

So this is what happens
* Login to GeoNode
* Try to upload vector layer and it times out.
* Login to geoserver using the auth - if it succeeds then try to upload the layer again and it works
* Sometimes the auth login doesn't work seamlessly so it gives a 404 because it fails to register in geoserver
*
# Solution
Fix GeoServer auth login

**Comment by ArnaudIGRAC** [comment]
Hi Admire, I can't find the layer in the GGIS.

**Comment by NyakudyaA** [comment]
@ArnaudIGRAC Can we wait for tomorrow when the new version is deployed. The layer is still being ingested

**Comment by ArnaudIGRAC** [comment]
sure!

**Comment by meomancer** [comment]
this fix is deployed @ArnaudIGRAC @NyakudyaA  to production
could you retry?

**Comment by ArnaudIGRAC** [comment]
I still see no weathering thickness layer in the GGIS...

**Comment by meomancer** [comment]
> I still see no weathering thickness layer in the GGIS...

could you reupload the layer @ArnaudIGRAC @NyakudyaA @seabilwe ?

**Comment by seabilwe** [comment]
@ArnaudIGRAC, please confirm the styling of this layer

![image](https://user-images.githubusercontent.com/56301949/108980742-ae832600-7694-11eb-8174-08b49ff33fa3.png)

**Comment by ArnaudIGRAC** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor xmlns="http://www.opengis.net/sld" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:se="http://www.opengis.net/se" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0">
  <NamedLayer>
    <se:Name>Weathring_Thickness</se:Name>
    <UserStyle>
      <se:Name>Weathring_Thickness</se:Name>
      <se:FeatureTypeStyle>
        <se:Rule>
          <se:Name>1 - 19 </se:Name>
          <se:Description>
            <se:Title>1 - 19 </se:Title>
          </se:Description>
          <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
            <ogc:And>
              <ogc:PropertyIsGreaterThanOrEqualTo>
                <ogc:PropertyName>Epaisseur</ogc:PropertyName>
                <ogc:Literal>1</ogc:Literal>
              </ogc:PropertyIsGreaterThanOrEqualTo>
              <ogc:PropertyIsLessThanOrEqualTo>
                <ogc:PropertyName>Epaisseur</ogc:PropertyName>
                <ogc:Literal>19</ogc:Literal>
              </ogc:PropertyIsLessThanOrEqualTo>
            </ogc:And>
          </ogc:Filter>
          <se:PointSymbolizer>
            <se:Graphic>
              <se:Mark>
                <se:WellKnownName>circle</se:WellKnownName>
                <se:Fill>
                  <se:SvgParameter name="fill">#ffe6b1</se:SvgParameter>
                </se:Fill>
                <se:Stroke>
                  <se:SvgParameter name="stroke">#232323</se:SvgParameter>
                  <se:SvgParameter name="stroke-width">0.5</se:SvgParameter>
                </se:Stroke>
              </se:Mark>
              <se:Size>11</se:Size>
            </se:Graphic>
          </se:PointSymbolizer>
        </se:Rule>
        <se:Rule>
          <se:Name>19 - 38 </se:Name>
          <se:Description>
            <se:Title>19 - 38 </se:Title>
          </se:Description>
          <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
            <ogc:And>
              <ogc:PropertyIsGreaterThan>
                <ogc:PropertyName>Epaisseur</ogc:PropertyName>
                <ogc:Literal>19</ogc:Literal>
              </ogc:PropertyIsGreaterThan>
              <ogc:PropertyIsLessThanOrEqualTo>
                <ogc:PropertyName>Epaisseur</ogc:PropertyName>
                <ogc:Literal>38</ogc:Literal>
              </ogc:PropertyIsLessThanOrEqualTo>
            </ogc:And>
          </ogc:Filter>
          <se:PointSymbolizer>
            <se:Graphic>
              <se:Mark>
                <se:WellKnownName>circle</se:WellKnownName>
                <se:Fill>
                  <se:SvgParameter name="fill">#ab8e6f</se:SvgParameter>
                </se:Fill>
                <se:Stroke>
                  <se:SvgParameter name="stroke">#232323</se:SvgParameter>
                  <se:SvgParameter name="stroke-width">0.5</se:SvgParameter>
                </se:Stroke>
              </se:Mark>
              <se:Size>11</se:Size>
            </se:Graphic>
          </se:PointSymbolizer>
        </se:Rule>
        <se:Rule>
          <se:Name>38 - 81 </se:Name>
          <se:Description>
            <se:Title>38 - 81 </se:Title>
          </se:Description>
          <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
            <ogc:And>
              <ogc:PropertyIsGreaterThan>
                <ogc:PropertyName>Epaisseur</ogc:PropertyName>
                <ogc:Literal>38</ogc:Literal>
              </ogc:PropertyIsGreaterThan>
              <ogc:PropertyIsLessThanOrEqualTo>
                <ogc:PropertyName>Epaisseur</ogc:PropertyName>
                <ogc:Literal>80.54999999999999716</ogc:Literal>
              </ogc:PropertyIsLessThanOrEqualTo>
            </ogc:And>
          </ogc:Filter>
          <se:PointSymbolizer>
            <se:Graphic>
              <se:Mark>
                <se:WellKnownName>circle</se:WellKnownName>
                <se:Fill>
                  <se:SvgParameter name="fill">#56352d</se:SvgParameter>
                </se:Fill>
                <se:Stroke>
                  <se:SvgParameter name="stroke">#232323</se:SvgParameter>
                  <se:SvgParameter name="stroke-width">0.5</se:SvgParameter>
                </se:Stroke>
              </se:Mark>
              <se:Size>11</se:Size>
            </se:Graphic>
          </se:PointSymbolizer>
        </se:Rule>
      </se:FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
</StyledLayerDescriptor>

**Comment by ArnaudIGRAC** [comment]
Here is the sld
[Weathering_thickness (2).zip](https://github.com/kartoza/IGRAC-GGIS/files/6034930/Weathering_thickness.2.zip)

**Comment by seabilwe** [comment]
@ArnaudIGRAC 
![image](https://user-images.githubusercontent.com/56301949/108982530-94e2de00-7696-11eb-99e7-3743833d2c08.png)

**Comment by ArnaudIGRAC** [comment]
thank you!
