### ISSUE TITLE
Missing layers in viewer Groundwater Resources in Africa

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#369]
We miss the following layers:

- [ ] - Aquifer productivity (l/s): the layer is there but doesn’t display
- [x] - Unconsolidated sediment maps of Botswana, Mauritania and South Sudan: can't add the layers because "Missing OGC reference metadata"
- [x] - Geological map of Burkina Faso (Africa Groundwater Atlas, 2019), Geological map of the Gambia (Africa Groundwater Atlas, 2019): can't add the layers because "Missing OGC reference metadata"

**Comment by NyakudyaA** [comment]
@seabilwe The layers I have ticket above are all rendering without the errors. Can you try to add them to the viewers and confirm if the error still occurs

**Comment by NyakudyaA** [comment]
https://ggis.un-igrac.org/layers/34fd74d1-0194-4b1d-af05-4644014acfe4:groundwateratlas:atlas_aquifer_productivity seems to have a serious bug which cannot be rectified. I suggest we delete the layer and recreate a new one. I have already created a new one in geoserver https://ggis.un-igrac.org/geoserver/groundwateratlas/wms?service=WMS&version=1.1.0&request=GetMap&layers=groundwateratlas%3Aatlas_aquifer_productivity1&bbox=-17.41092529296875%2C-34.823828125%2C51.23907470703126%2C37.27617187500001&width=731&height=768&srs=EPSG%3A4326&access_token=LmFFbPnTszoGSvXNWOl6BGrt6wcPzi&format=application/openlayers which we can publish in production once we have deleted the one in GeoNode. @seabilwe Is this layer being used in many viewers. If not Can we proceed with this solution

**Comment by seabilwe** [comment]
> https://ggis.un-igrac.org/layers/34fd74d1-0194-4b1d-af05-4644014acfe4:groundwateratlas:atlas_aquifer_productivity seems to have a serious bug which cannot be rectified. I suggest we delete the layer and recreate a new one. I have already created a new one in geoserver https://ggis.un-igrac.org/geoserver/groundwateratlas/wms?service=WMS&version=1.1.0&request=GetMap&layers=groundwateratlas%3Aatlas_aquifer_productivity1&bbox=-17.41092529296875%2C-34.823828125%2C51.23907470703126%2C37.27617187500001&width=731&height=768&srs=EPSG%3A4326&access_token=LmFFbPnTszoGSvXNWOl6BGrt6wcPzi&format=application/openlayers which we can publish in production once we have deleted the one in GeoNode. @seabilwe Is this layer being used in many viewers. If not Can we proceed with this solution

@NyakudyaA It is only used in the Groundwater Resources in Africa map viewer

**Comment by seabilwe** [comment]
> @seabilwe The layers I have ticket above are all rendering without the errors. Can you try to add them to the viewers and confirm if the error still occurs

@NyakudyaA I have added the layers but the map will not save them, there is an error.

@meomancer whenever I add layers to the Groundwater Resources in Africa viewer, I get an error and none of the layers are saved.
![image](https://user-images.githubusercontent.com/56301949/107607606-61d62e80-6c42-11eb-8f18-0b7f04310e78.png)

**Comment by seabilwe** [comment]
https://user-images.githubusercontent.com/56301949/107607769-d9a45900-6c42-11eb-9ebe-8cffed5b550d.mp4

**Comment by meomancer** [comment]
hi @seabilwe 
yes, the error is already reported in : https://github.com/kartoza/IGRAC-GGIS/issues/372
i will deploy the upgraded geonode tomorrow and will test and check it tomorrow

**Comment by meomancer** [comment]
this fix is deployed @seabilwe to production
could you retry?

**Comment by seabilwe** [comment]
> this fix is deployed @seabilwe to production
> could you retry?

Okay @meomancer

**Comment by seabilwe** [comment]
> this fix is deployed @seabilwe to production
> could you retry?

Hi @meomancer, I was able to add and save the layers. Thanks so much

**Comment by seabilwe** [comment]
@NyakudyaA, can I remove https://ggis.un-igrac.org/layers/34fd74d1-0194-4b1d-af05-4644014acfe4:groundwateratlas:atlas_aquifer_productivity from the viewer so that the one you replicated can be added and then added to the viewer again?

**Comment by meomancer** [comment]
hi @NyakudyaA @seabilwe 
could you check this ticket so we can close this?

**Comment by seabilwe** [comment]
@NyakudyaA  I have removed the aquifer productivity layer

**Comment by NyakudyaA** [comment]
@seabilwe This is now available as https://ggis.un-igrac.org/layers/34fd74d1-0194-4b1d-af05-4644014acfe4:groundwateratlas:atlas_aquifer_productivity1
