### ISSUE TITLE
Legends of remote service layers don't display

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#370]
See for instance
https://ggis.un-igrac.org/layers/httpsservicesbgrdewmsgrundwasserwhymap_gwr:0
https://ggis.un-igrac.org/layers/httpmapsrefbrgmfrwxs1ggigc35_cgmw_brgm_africa_geology:AFR_CGMW_BRGM_10M_GeologicUnits

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
The first one:
https://ggis.un-igrac.org/layers/httpsservicesbgrdewmsgrundwasserwhymap_gwr:0
I'm not sure the link of legend for that layer
it is
```
http://mapsref.brgm.fr/wxs/1GG/IGC35_CGMW_BRGM_Africa_Geology??service=WMS&version=1.3.0&request=GetLegendGraphic&format=image/png&width=20&height=20&layer=AFR_CGMW_BRGM_10M_GeologicUnits&legend_options=fontAntiAliasing:true;fontSize:12;forceLabels:on&SERVICE=WMS&VERSION=1.3.0
```
we need to find the correct url for this, but i'm not sure where
could you help here @seabilwe @NyakudyaA 

The second one has been corrected @ArnaudIGRAC

**Comment by NyakudyaA** [comment]
> hi @ArnaudIGRAC
> The first one:
> https://ggis.un-igrac.org/layers/httpsservicesbgrdewmsgrundwasserwhymap_gwr:0
> I'm not sure the link of legend for that layer
> it is
> 
> ```
> http://mapsref.brgm.fr/wxs/1GG/IGC35_CGMW_BRGM_Africa_Geology??service=WMS&version=1.3.0&request=GetLegendGraphic&format=image/png&width=20&height=20&layer=AFR_CGMW_BRGM_10M_GeologicUnits&legend_options=fontAntiAliasing:true;fontSize:12;forceLabels:on&SERVICE=WMS&VERSION=1.3.0

> ```

@meomancer here is the request http://mapsref.brgm.fr/legendes/ogg/cgmwafrica_fgeol_legend.png
> 
> we need to find the correct url for this, but i'm not sure where
> could you help here @seabilwe @NyakudyaA
> 
> The second one has been corrected @ArnaudIGRAC

**Comment by meomancer** [comment]
Done, but it is too large @NyakudyaA @ArnaudIGRAC 
https://ggis.un-igrac.org/layers/httpmapsrefbrgmfrwxs1ggigc35_cgmw_brgm_africa_geology:AFR_CGMW_BRGM_10M_GeologicUnits

i will fix the templates to make it fit to layout
but if we make it fit to layout, it will hard to see it

![Selection_063](https://user-images.githubusercontent.com/4530905/107362437-56ccb280-6b0b-11eb-8191-cece7fdb1963.png)

**Comment by NyakudyaA** [comment]
> Done, but it is too large @NyakudyaA @ArnaudIGRAC
> https://ggis.un-igrac.org/layers/httpmapsrefbrgmfrwxs1ggigc35_cgmw_brgm_africa_geology:AFR_CGMW_BRGM_10M_GeologicUnits
> 
> i will fix the templates to make it fit to layout
> but if we make it fit to layout, it will hard to see it
> 
> ![Selection_063](https://user-images.githubusercontent.com/4530905/107362437-56ccb280-6b0b-11eb-8191-cece7fdb1963.png)

It's because they are using a static image for the legend

**Comment by meomancer** [comment]
what do you think @ArnaudIGRAC @timlinux 
Should we make it fit to layout although the text will be small?

**Comment by ArnaudIGRAC** [comment]
I am not bothered if the legend doesn't fit in the layout. At least you can use the legend.

**Comment by meomancer** [comment]
is it ok @NyakudyaA @ArnaudIGRAC 
can we close it?

**Comment by NyakudyaA** [comment]
Yes, you can close @meomancer
