### ISSUE TITLE
layer used in viewer - incorrect

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#371]
I just imported this layer from remote service: https://ggis.un-igrac.org/layers/httpsservicesbgrdewmsgrundwasserwhymap_gwr:3
It says it is used in the viewer "Senegalo-Mauritanian Aquifer Basin (SMAB) / Bassin Aquifère Sénégalo-Mauritanien (BASM)" but it isn't true. I haven't added it to the viewer and I can't find it there. It looks like a bug.

**Comment by meomancer** [comment]
this bug will be fixed by : https://github.com/kartoza/geonode/commit/b1e758de03a98d3c962b94cbfd7d90902e10229a
will be released in 1.1.2 on friday

**Comment by meomancer** [comment]
this fix is deployed @ArnaudIGRAC to production
please check it
