### ISSUE TITLE
Download layer formats appear twice

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#378]
PDF, Zipped shapefile and GML 3.1.1 appear twice
![image](https://user-images.githubusercontent.com/64771599/107936572-1a71da00-6f83-11eb-838f-030d3b856487.png)
![image](https://user-images.githubusercontent.com/64771599/107936615-2493d880-6f83-11eb-87d3-4a4fca08c2fb.png)

**Comment by meomancer** [comment]
what layer is it @ArnaudIGRAC ?

**Comment by ArnaudIGRAC** [comment]
https://ggis.un-igrac.org/layers/twap.gwshare:twap.gwshare:transboundary_aquifers_basicinformation

**Comment by meomancer** [comment]
Fixed @ArnaudIGRAC
