### ISSUE TITLE
Editing layers doesn't work

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#379]
I tried to change attribute values of https://ggis.un-igrac.org/layers/twap.gwshare:twap.gwshare:transboundary_aquifers_basicinformation and got the following error message
![image](https://user-images.githubusercontent.com/64771599/107937345-185c4b00-6f84-11eb-92c6-555e0fd19fe9.png)

**Comment by meomancer** [comment]
what attribute did you change? (i need to try by myself)

**Comment by ArnaudIGRAC** [comment]
aquifer_name and aquifer_code

**Comment by meomancer** [comment]
what did you change @ArnaudIGRAC ? is it the label or descriptio or anything?
Could you describe what are you going to change?

![Selection_100](https://user-images.githubusercontent.com/4530905/107941352-2e85fd80-6fbc-11eb-87ca-3f6ddf7deb6b.png)

**Comment by meomancer** [comment]
ah, did you change the "attribute" column @ArnaudIGRAC 
i think you can't do that @ArnaudIGRAC 
just fill label, it will change the label in map

This what i did

![Selection_103](https://user-images.githubusercontent.com/4530905/107942158-70fc0a00-6fbd-11eb-8aca-d71d47865fdc.png)
![Selection_102](https://user-images.githubusercontent.com/4530905/107942134-66da0b80-6fbd-11eb-91ad-2b3c273f00f9.png)

**Comment by ArnaudIGRAC** [comment]
No, I wanted to edit values in the attribute table
![image](https://user-images.githubusercontent.com/64771599/107942364-6d4f8f80-6f8b-11eb-8954-7382849294f8.png)

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
this is not editable from geoserver. I'm not sure why, but can you confirm here @seabilwe @NyakudyaA ?

**Comment by NyakudyaA** [comment]
@ArnaudIGRAC Can you try again

**Comment by ArnaudIGRAC** [comment]
It doesn't work but the error message has changed. It says 
![image](https://user-images.githubusercontent.com/64771599/107966093-aa2b7e80-6fab-11eb-8826-7c787ad0ce2e.png)

**Comment by NyakudyaA** [comment]
@ArnaudIGRAC I testing this by uploading a layer and editing this. The editing works perfectly. However with the layers already published in GeoNode I could not edit some of them. The reason for this is because
* The majority of the layers are defined as [views](https://www.postgresqltutorial.com/postgresql-views/) in the database hence they cannot be updated. Views are partially updatable in the Database.
* So we should ideally flag all layers that are derived as views so that users can know that this is not editable

**Comment by timlinux** [comment]
Maybe we can just use the permissions framework to remove edit rights for view based layers @NyakudyaA

**Comment by NyakudyaA** [comment]
> Maybe we can just use the permissions framework to remove edit rights for view based layers @NyakudyaA

We could but we would still need a way to identify which views are exposed in GeoServer. Because these are database views GeoServer just treats them as normal tables and exposes them in the same way a table would be exposed.

**Comment by ArnaudIGRAC** [comment]
so the only way to edit the layers is to reupload them again?

**Comment by NyakudyaA** [comment]
> so the only way to edit the layers is to reupload them again?

Let me test what actually happens when you use the replace layer button when the underlying layer is a view?

**Comment by NyakudyaA** [comment]
> > so the only way to edit the layers is to reupload them again?
> 
> Let me test what actually happens when you use the replace layer button when the underlying layer is a view?

If a layer is coming from a view. You can not even use the layer replace. You will need to reupload them

**Comment by ArnaudIGRAC** [comment]
thank you Admire.
