### ISSUE TITLE
can't add layers to viewer

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#383]
I can't add these two layers to the TWAP viewer, although they both look ok.
GP: Groundwater abstraction for agricultural use, including livestock [m3/yr]
GP: Fresh water abstraction   for agricultural use, including livestock [m3/yr]
![image](https://user-images.githubusercontent.com/64771599/108185435-951a3100-710c-11eb-8eea-c21d4797c718.png)

**Comment by meomancer** [comment]
hi @seabilwe @NyakudyaA 
do you have idea this error? "Missing OGC reference metadata"

**Comment by timlinux** [comment]
Just waiting for your inputs here @NyakudyaA and @seabilwe please address ASAP

**Comment by NyakudyaA** [comment]
The main reason why this is happening is that this layer is missing metadata links that describe the metadata

A normal layer in GeoServer should look like
![metadata-fields](https://user-images.githubusercontent.com/2510900/108362531-890d9c80-71fc-11eb-8a71-ac8184c6b7e3.png)

This problem layer
![problem](https://user-images.githubusercontent.com/2510900/108362616-a6426b00-71fc-11eb-95aa-0cc3f4db1826.png)

To fix this I had to go to the layer , update the metadata and save the metadata. 

Still checking why the viewers are not working

**Comment by ArnaudIGRAC** [comment]
Any update on that issue?

**Comment by NyakudyaA** [comment]
Hi, @ArnaudIGRAC I will check it out again. I will feedback here a bit later

**Comment by NyakudyaA** [comment]
The best solution for these layers is to delete them and register them again in the system. Will do this tomorrow

**Comment by ArnaudIGRAC** [comment]
Hi Admire, are you sure it is the only way? this issue arises for several layers, including layers that we have uploaded recently. Have you been able to identify what causes this issue?

**Comment by timlinux** [comment]
Any update on this @NyakudyaA ?

**Comment by NyakudyaA** [comment]
@meomancer I think this is happening on the GeoNode side, Maybe you need to investigate this.  This is what I did to make sure the error is coming from GeoNode.
* Create a new layer in Geoserver
* Register the layer in GeoNode
* Try to add it to the viewer - It works at this point
* Update the metadata of the layer to match the original one - works 
* Update the name of the layer to match the old one - Boom it doesn't allow me to add the layer into the viewer.

Something is not working consistently in the GeoNode

**Comment by dimasciput** [comment]
@meomancer please use the fix from here https://github.com/kartoza/geonode/pull/614

**Comment by timlinux** [comment]
Thanks @dimasciput 

If any of these fixes can be upstreamed to geonode, please do so.

**Comment by meomancer** [comment]
This has been deployed on staging
please test it on staging @ArnaudIGRAC before we can deploy it on production

**Comment by meomancer** [comment]
Will be released with 1.1.5

**Comment by timlinux** [comment]
Hi @ArnaudIGRAC could you confirm if we can close this now? Thanks and greetings!

**Comment by meomancer** [comment]
This fixed deployed on 1.1.5
https://github.com/kartoza/IGRAC-GGIS/releases/tag/1.1.5

**Comment by ArnaudIGRAC** [comment]
https://ggis.un-igrac.org/layers/geonode_data:geonode:WL_end_drilling

**Comment by ArnaudIGRAC** [comment]
This layer can't be added to viewers. Please solve that issue once for all.
https://ggis.un-igrac.org/layers/geonode_data:geonode:WL_end_drilling

**Comment by ArnaudIGRAC** [comment]
Have a look here http://osgeo-org.1560.x6.nabble.com/Problem-GeoNode-OSGeoLive-13-0-Missing-OGC-reference-metadata-td5437840.html

**Comment by NyakudyaA** [comment]
Can you try again @ArnaudIGRAC

**Comment by ArnaudIGRAC** [comment]
It works fine now, thanks!
