### ISSUE TITLE
Data from the Gambia appears only when zooming in in the GGMN viewer

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#385]
It looks like this:
![image](https://user-images.githubusercontent.com/36033176/108750624-89ca6980-7541-11eb-896d-cffb57169c96.png)

and I see the data only when I zoom in in the Gambia:
![image](https://user-images.githubusercontent.com/36033176/108750762-b8484480-7541-11eb-98d4-4323919c6b18.png)

**Comment by meomancer** [comment]
hi @NyakudyaA or @seabilwe 
could you help me check this? i think it is because of cache from geoserver? I'm not sure how to recreate it

**Comment by seabilwe** [comment]
Hi @meomancer @NyakudyaA, the points in Gambia are not rendering at all even after zooming in and out of the layer

**Comment by NyakudyaA** [comment]
Maybe confirm with @clau1313 if she still experiences this behavior

**Comment by seabilwe** [comment]
> Hi @meomancer @NyakudyaA, the points in Gambia are not rendering at all even after zooming in and out of the layer

@clau1313 , are you experiencing the same issue?

**Comment by clau1313** [comment]
Hi @seabilwe, I only see the points in the Gambia when I zoom at this level:
![image](https://user-images.githubusercontent.com/36033176/109007253-3cb6d680-76ac-11eb-847d-e4e9b64d8448.png)

Less than that I don't see anything:
![image](https://user-images.githubusercontent.com/36033176/109007331-4fc9a680-76ac-11eb-985b-29d1e861f831.png)

**Comment by meomancer** [comment]
hi @NyakudyaA @seabilwe 
is this because tile cache? should we reseed?
i'm able to see the point but just on high zoom, like @clau1313 issue

**Comment by NyakudyaA** [comment]
> hi @NyakudyaA @seabilwe
> is this because tile cache? should we reseed?
> i'm able to see the point but just on high zoom, like @clau1313 issue

@meomancer I am flummoxed with what is happening here. If I download the layer and preview it in QGIS. There are no points in Gambia
![map-gamb](https://user-images.githubusercontent.com/2510900/109464091-c4b32c80-7a6e-11eb-8227-a75b1bb0f0bb.png)

Even in the GeoNode, I cannot see the points in Gambia.

**Comment by meomancer** [comment]
wait, i can see it now
https://staging.igrac.kartoza.com/view/ggmn
could you check it @NyakudyaA @clau1313 ?
![Selection_198](https://user-images.githubusercontent.com/4530905/109465012-2b9a0b00-7a9a-11eb-925c-cca8ba7b56cc.png)

**Comment by NyakudyaA** [comment]
cool @meomancer , So I just cleared the geowebcache

**Comment by clau1313** [comment]
I can see them now too, thanks @meomancer

**Comment by ArnaudIGRAC** [comment]
I can't see the Gambia data

**Comment by meomancer** [comment]
this fixed @ArnaudIGRAC @clau1313
