### ISSUE TITLE
Issues for non-admin users

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#387]
Issue 1 you can't edit keywords, the box is greyed out
![image](https://user-images.githubusercontent.com/64771599/108982318-f2266180-768d-11eb-8790-0e2fa94e59d7.png)
Issue 2 you can't upload your style file immediately after uploading the layer (clicking on Upload SLD). You get a page saying: "not allowed"
![image](https://user-images.githubusercontent.com/64771599/108982640-4df0ea80-768e-11eb-9da7-e1e0b574512d.png)
Issue 3 change languages doesn't work
![image](https://user-images.githubusercontent.com/64771599/108982923-9b6d5780-768e-11eb-8588-3a6818d566ae.png)

**Comment by meomancer** [comment]
1 & 2 i will check it

3 when did you try to change the language?
i can change the language
you can see on header 
![Capture](https://user-images.githubusercontent.com/4530905/109099497-ca023580-7755-11eb-8494-48fd0d9055f4.PNG)

**Comment by dimasciput** [comment]
@ArnaudIGRAC @meomancer 

Issue no 1 : 
This is because of the keyword setting is set to readonly for normal users : https://github.com/kartoza/IGRAC-GGIS/commit/00783877e0f062b0a03aaf554f8192a30119acc6, @meomancer was this intentional?

**Comment by NyakudyaA** [comment]
> @ArnaudIGRAC @meomancer
> 
> Issue no 1 :
> This is because of the keyword setting is set to read-only for normal users : [0078387](https://github.com/kartoza/IGRAC-GGIS/commit/00783877e0f062b0a03aaf554f8192a30119acc6), @meomancer was this intentional?

@dimasciput that was intentional. If you would like to have a nice list of curated Keywords then you need to only manage them from the Admin. If this is removed when a user uploads a layer GeoNode will extract some random keywords resulting in a messy situation

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
So i think this is not bug, and we don't need to change it
as per @NyakudyaA said, it is intentional to make everything nice

**Comment by dimasciput** [comment]
Thanks @NyakudyaA 

@ArnaudIGRAC for issue no 2, I couldn't replicate it, can you maybe try again?

**Comment by ArnaudIGRAC** [comment]
Issue 3 works indeed. Yesterday it wasn't working. 
Issue 2 is still there. Note that you need to log in as regular user.

**Comment by dimasciput** [comment]
@meomancer the issue 3 is actually still exist, it happens when you change the language from map layer page, you'll get this error : 
```
VM429:1315 Uncaught ReferenceError: setCookie is not defined
    at changeLanguage (VM429:1315)
    at HTMLSelectElement.onchange ((index):1042)

**Comment by dimasciput** [comment]
@meomancer I made a fix for issue no 3 https://github.com/kartoza/IGRAC-GGIS/pull/390, please deploy it when you got a chance

**Comment by dimasciput** [comment]
The issue 2 is because the layer is still not ready when user click edit style, @meomancer do you have any suggestions for this?

**Comment by meomancer** [comment]
thank you very much @dimasciput  for no 3

for no 2, yes, geonode is using backprocess to process the layer
my suggestion maybe are 2:
1. We can hide the buttons for now and raise ticket on geonode. We can said that "to upload sld style, you need to wait layer to be ready and upload in in layer info"
2. Disable button by default. we can create our own API to check if layer is ready or now, and make js script to check it using API. If the layer is ready, we can enable the button. (but it will take time to implement it)

what do you think @ArnaudIGRAC @timlinux ?

**Comment by ArnaudIGRAC** [comment]
Thank you Dimas and Irwan for investigating this issue. I would deactivate the button (no need for script or to inform the user about anything, button is simply not there) and inform the developers of GeoNode about the issue.

**Comment by ArnaudIGRAC** [comment]
> Thank you Dimas and Irwan for investigating this issue. I would deactivate the button (no need for script or to inform the user about anything, button is simply not there) and inform the developers of GeoNode about the issue.

have you proceeded with the change?

**Comment by ArnaudIGRAC** [comment]
> @meomancer I made a fix for issue no 3 #390, please deploy it when you got a chance

and on this?

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
number 2 and 3 has been deployed on staging
https://staging.igrac.kartoza.com/

will be included on 1.1.4 for production
which is will be released tomorrow? is it ok?

**Comment by ArnaudIGRAC** [comment]
Sure, thanks!

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
this fix has been deployed on production

**Comment by ArnaudIGRAC** [comment]
thank you!
