### ISSUE TITLE
view document

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#389]
Is it possible to view documents in GeoNode?
The user manual says _Through the document detailed page is possible to view, download and manage a document._ but afaik you can only download documents.

**Comment by NyakudyaA** [comment]
@ArnaudIGRAC you can only download the documents. Because they are a lot of formats supported by GeoNode it will be impossible to have a unified viewer to use for viewing

**Comment by ArnaudIGRAC** [comment]
thank you
