### ISSUE TITLE
style doesn't open

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#391]
This layer (https://ggis.un-igrac.org/layers/groundwater:groundwater:Groundwater_Well) has a strange style name so I wanted to open it to check. I got the following message
![image](https://user-images.githubusercontent.com/64771599/109641809-6d868800-7b52-11eb-893c-8a11c9ccafee.png)

**Comment by NyakudyaA** [comment]
@ArnaudIGRAC I can open the style fine on my side
![edit-style](https://user-images.githubusercontent.com/2510900/109642888-2f8e6180-7b5c-11eb-8179-3a7a8d1ec836.png)

**Comment by ArnaudIGRAC** [comment]
the problem is if you click on the style 
![image](https://user-images.githubusercontent.com/64771599/109643647-cf47f180-7b54-11eb-9b60-5e3bde58cce0.png)

**Comment by meomancer** [comment]
it's working now @ArnaudIGRAC 
can you check it?
