### ISSUE TITLE
Data from India don't show in GGMN

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#394]
Hi @meomancer, not sure why the groundwater levels from India don't appear in GGMN. The data are in this file:

[central-ground-water-board-india_ggmn_timeseries.zip](https://github.com/kartoza/IGRAC-GGIS/files/6089498/central-ground-water-board-india_ggmn_timeseries.zip)

**Comment by meomancer** [comment]
Hi @clau1313 
Updated on the staging and production, can you please check this?

**Comment by clau1313** [comment]
Hi @meomancer,
I see the stations and measurements only in 'well and monitoring data' but not in the GGMN viewer, both in staging and production.

**Comment by meomancer** [comment]
hi @NyakudyaA 
how did you do to remove all cache from geoserver?

on the geoserver viewer, the data on india already there
https://staging.igrac.kartoza.com/geoserver/groundwater/wms?service=WMS&version=1.1.0&request=GetMap&layers=groundwater%3AGroundwater_Well_GGMN&bbox=-159.5758333%2C-71.4605399058621%2C153.552097%2C68.3519845062498&width=768&height=342&srs=EPSG%3A4326&access_token=Keec2EDhq3VzPJA9aXS86pAcXskY2u&format=application/openlayers

![Selection_286](https://user-images.githubusercontent.com/4530905/110762723-b097d800-8283-11eb-8a42-af3a6535b623.png)

But on mapstore, still no wells in india
![Selection_287](https://user-images.githubusercontent.com/4530905/110762785-c1e0e480-8283-11eb-811b-6328db874657.png)

**Comment by NyakudyaA** [comment]
You need to go to the layer list and click the button empty cache
![empty](https://user-images.githubusercontent.com/2510900/110763403-8382ff80-825a-11eb-8a41-7406944edaaa.png)

**Comment by meomancer** [comment]
thank you very much @NyakudyaA 
@clau1313 it's fixed, could you check it?

**Comment by clau1313** [comment]
thanks @meomancer it is working now.
