### ISSUE TITLE
can't edit layer in Django - keywords is required

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#396]
Whenever I want to save my edits, I am asked to fill in Keywords. I don't know why since keywords are not mandatory. Moreover, I can't add keywords.
![image](https://user-images.githubusercontent.com/64771599/110596167-43028380-817f-11eb-9cda-5927d72783f7.png)

**Comment by ArnaudIGRAC** [comment]
Layer is https://ggis.un-igrac.org/en/admin/layers/layer/2009/change/

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
is there anything that you need to update on admin? (what i mean is metadata edit doesn't provide it)

And also, we already fix it on the staging, please try it before release it on production

**Comment by meomancer** [comment]
Will be released with 1.1.5

**Comment by meomancer** [comment]
This fix has been deployed on 1.1.5
https://github.com/kartoza/IGRAC-GGIS/releases/tag/1.1.5
