### ISSUE TITLE
new uploads disappear

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#397]
A colleague of us uploaded a few layers this morning. They appear properly in the catalog but when you try to open them, you get to the following page:
**Page Not Found
The page you requested does not exist. Perhaps you are using an outdated bookmark?**

Here is additional explanation from our colleague:
_Yeah, exacly I have found this problem as well. First of all when I click on my profile, then scroll down to "Resources" and click on any of the freshly uploaded files, I get the same message as you quoted - ALSO it logs me off from the website automatically after that. No idea why it happens. All was working so well and now... I don't know.
Also while uploading any new files I get the errors like:
Unexpected error! - error Error Code. Contact the system administrator for more information regarding this error message.
Also I have uploaded the geoTIFF for test purpose, then the .sld, all was working fine like an hour ago, and now when I click on it - there is nothing. empty map.... [IRBF_raster_qgis — IGRAC (un-igrac.org)]_

**Comment by meomancer** [comment]
could you provide the layer @ArnaudIGRAC  ?

**Comment by ArnaudIGRAC** [comment]
I don't have the layers, but I don't think the issue is with the layers. Our colleague uploaded 3 layers and none of them was uploaded properly. Btw, I don't see the layers anymore

**Comment by meomancer** [comment]
could you help to ask them the file that was uploaded, and maybe the user that was uploaded? 
It's hard to analyze the error if we can't reproduce it.

**Comment by ArnaudIGRAC** [comment]
user is krzysztof.janik
Layers were in GeoServer yesterday (look at the last uploads). One had "IBF" in its name. I wanted to access GeoServer to check myself but I can't. I am asked to login and my credentials don't work.

**Comment by meomancer** [comment]
i can't access too @ArnaudIGRAC 
let me ask @lucernae for this

**Comment by NyakudyaA** [comment]
> i can't access too @ArnaudIGRAC
> let me ask @lucernae for this

@meomancer Do you meant this layer https://ggis.un-igrac.org/geoserver/web/wicket/bookmarkable/org.geoserver.web.data.resource.ResourceConfigurationPage?9&name=Rzeki&wsName=geonode

If so the layers are still in GeoServer so I suggest just run the update commands in GeoNode and then try to replicate the issue so that it won't happen again
![geonode-layer](https://user-images.githubusercontent.com/2510900/110756539-030cd080-8253-11eb-8a10-a76bff94cc64.png)

**Comment by meomancer** [comment]
ok, i found what the error (not the cause)
https://ggis.un-igrac.org/en/admin/layers/uploadsession/
i checked all layer from krzysztof.janik, in the layer list, they gives 404 not found, but the layer are there

**Comment by NyakudyaA** [comment]
> ok, i found what the error (not the cause)
> https://ggis.un-igrac.org/en/admin/layers/uploadsession/
> i checked all layer from krzysztof.janik, in the layer list, they gives 404 not found, but the layer are there

Maybe it's an issue with the layer name, maybe they are not being encoded properly

**Comment by meomancer** [comment]
For example:
https://ggis.un-igrac.org/layers/?limit=5&offset=0&title__icontains=Suitable_area_recharge_dam0&abstract__icontains=Suitable_area_recharge_dam0&purpose__icontains=Suitable_area_recharge_dam0&f_method=or

when we click the layer, it gaves 404 not found, because the url is : https://ggis.un-igrac.org/layers/:geonode:
but the layer is there https://ggis.un-igrac.org/layers/geonode:Suitable_area_recharge_dam0

**Comment by ArnaudIGRAC** [comment]
> For example:
> https://ggis.un-igrac.org/layers/?limit=5&offset=0&title__icontains=Suitable_area_recharge_dam0&abstract__icontains=Suitable_area_recharge_dam0&purpose__icontains=Suitable_area_recharge_dam0&f_method=or
> 
> when we click the layer, it gaves 404 not found, because the url is : https://ggis.un-igrac.org/layers/:geonode:
> but the layer is there https://ggis.un-igrac.org/layers/geonode:Suitable_area_recharge_dam0

that is exactly the problem

**Comment by meomancer** [comment]
i'm not sure @NyakudyaA 
the detail url that saved is 
![Selection_285](https://user-images.githubusercontent.com/4530905/110756942-66abf380-827d-11eb-988f-cbd86c6f70e8.png)

is it ok if i change it manually for now? (so we can wait for upgrading geonode that is coming)

**Comment by ArnaudIGRAC** [comment]
> i'm not sure @NyakudyaA
> the detail url that saved is
> ![Selection_285](https://user-images.githubusercontent.com/4530905/110756942-66abf380-827d-11eb-988f-cbd86c6f70e8.png)
> 
> is it ok if i change it manually for now? (so we can wait for upgrading geonode that is coming, hopefully it can solve this issue)

this is what I wanted to do but I couldn't save my edits because of the keywords #396

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
i fixed everything
could you check it?
https://ggis.un-igrac.org/people/profile/krzysztof.janik/?limit=5&offset=0

**Comment by ArnaudIGRAC** [comment]
I don't see the layers he uploaded yesterday and the day before.

**Comment by meomancer** [comment]
what layers is it?
could we reupload @ArnaudIGRAC ? i'm not sure how to check it
because on the 
https://ggis.un-igrac.org/en/admin/layers/uploadsession/
it is basically every upload that user did
and every layer on the uploadsession already in geonode

**Comment by ArnaudIGRAC** [comment]
I don't remember the names but I could find out on GeoServer, they were there yesterday. Just give me access to GeoServer :)

**Comment by meomancer** [comment]
I sent you an email to rizky too
it contains the username/password to geoserver
can you use that?

the email title is "Geoserver Access"

**Comment by ArnaudIGRAC** [comment]
I haven't received anything (also checked my junk mail). Can you please send it again?
Also, it is not the regular procedure that I need to log in again in GeoServer... I hope it is just a temporary work around.

**Comment by meomancer** [comment]
resent @ArnaudIGRAC

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, one of the layers uploaded yesterday was 
geonode:IBF_suitability_TEST1

**Comment by meomancer** [comment]
@ArnaudIGRAC that layer has been pulled
https://ggis.un-igrac.org/layers/IBF_suitability_TEST1:geonode:IBF_suitability_TEST1
please check it

**Comment by ArnaudIGRAC** [comment]
Thanks Irwan. There were 2 additional layers uploaded yesterday or the day before. I can't remember their names. Any possibility to restore these 2? Somehow they should appear in https://ggis.un-igrac.org/en/admin/layers/uploadsession/ ....

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
I'm not sure how to restore it unless i know the layer name on geoserver
our layer on geonode is 736 layers, on the geoserver is 772
if we want to restore everything because we don't know the name, it will restore a lot of layer that i don't know it is needed on geonode or not

do you have suggestion in here @seabilwe @NyakudyaA ? is there any feature on geoserver that can sort layer per date they uploaded?

**Comment by NyakudyaA** [comment]
@meomancer All layers that are uploaded are published in the geonode workspace. You can ideally get a list of all layers in the schema and compare against the layers registered in geonode.

Alternatively just run the update command specifying the geonode workspace and skip existing registered layers. This will publish all layers to the top of the list in Geonode

**Comment by ArnaudIGRAC** [comment]
I will ask my colleague to reupload the 3 layers, I think it will take less time.
Can you please investigate on why his layers were not uploaded properly?

**Comment by meomancer** [comment]
i think as i checked the https://ggis.un-igrac.org/en/admin/layers/uploadsession/
he select multiple files for 1 upload, like directly >5 layers
maybe it is heavy that creates error for some layers
but i'm not sure

we will upgrade the geonode like on SADC, hopefully it will fix this issue

**Comment by meomancer** [comment]
1.1.5 has been deployed
https://github.com/kartoza/IGRAC-GGIS/releases/tag/1.1.5

hopefully this error will be resolved
