### ISSUE TITLE
Add record - organisation

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#398]
When you add a well and monitoring data record, default is "------". This shouldn't be an option. Like for batch upload, every upload has to be made within an organisation. 
![image](https://user-images.githubusercontent.com/64771599/110640023-a953ca00-81b0-11eb-9ba6-7c14c2b08452.png)

**Comment by meomancer** [comment]
It is empty because it is coming from ggmn API and some of well does not have organisation.

this is required on staging (will deploy it on production)
on batch upload, it is also required.
please try it on staging

**Comment by meomancer** [comment]
Will be released with 1.1.5

**Comment by meomancer** [comment]
This fixed deployed on 1.1.5
https://github.com/kartoza/IGRAC-GGIS/releases/tag/1.1.5
