### ISSUE TITLE
can't remove viewers

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#403]
I can't delete this viewer https://ggis.un-igrac.org/maps/2016

First
![image](https://user-images.githubusercontent.com/64771599/111616946-cc026600-87e2-11eb-9622-f0694288610e.png)
Then
![image](https://user-images.githubusercontent.com/64771599/111616968-d1f84700-87e2-11eb-9e48-da59923211df.png)

**Comment by ArnaudIGRAC** [comment]
I deleted it in Django, but I guess I should be able to delete it directly in GeoNode

**Comment by meomancer** [comment]
the problem was the server was down
it makes a configurations to the default, which is why it show 504
504 shows that we have reach the limit of time for connection, the default is 20 seconds
so the custom one was 2 minutes, but because server was down, it changed back to 20 seconds
