### ISSUE TITLE
upload doesn't work

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#404]
Hi Irwan,

I can't upload this layer, can you tell me why? I thought there was an issue with the coordinate system but I still have the same issue after saving the layer in WGS84.
[test deepwater.zip](https://github.com/kartoza/IGRAC-GGIS/files/6163657/test.deepwater.zip)

**Comment by meomancer** [comment]
could you check this @NyakudyaA @seabilwe ?

**Comment by seabilwe** [comment]
Hi @ArnaudIGRAC @meomancer I have uploaded the layer. The only issue is the SLD, when applied to the layer nothing is rendered
![deepwater](https://user-images.githubusercontent.com/56301949/111760748-c15dd480-88a7-11eb-817d-25971828f042.png)

**Comment by ArnaudIGRAC** [comment]
thank you Seabilwe, it also works on my side now. Maybe I couldn't upload it last week because of the server breakdown?
