### ISSUE TITLE
upload big layer

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#406]
Could you please upload this heavy layer for me?
https://we.tl/t-Z9XvAlLJK5

**Comment by meomancer** [comment]
Could you help upload this @seabilwe ?
please upload it on geoserver? because i checked it is not working on geonode because request time out, the layer is too big

**Comment by dimasciput** [comment]
@meomancer ok let me try it

**Comment by dimasciput** [comment]
@ArnaudIGRAC here's the layer https://ggis.un-igrac.org/layers/geonode_data:geonode:greece1

**Comment by ArnaudIGRAC** [comment]
thank you
