### ISSUE TITLE
Error in batch upload

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#409]
Hi @meomancer, I am trying to do a batch upload but I get an error in the ID column:
![image](https://user-images.githubusercontent.com/36033176/112490293-895f0180-8d7f-11eb-8785-95353cd645f7.png)

the file is this one:
[General_info_in_template.xlsx](https://github.com/kartoza/IGRAC-GGIS/files/6205458/General_info_in_template.xlsx)

What could be the problem? 
Thanks!

**Comment by meomancer** [comment]
hi @clau1313 
it's fixed
please try it on staging for now

if it is urgent on the production, please create new column "Country" and just let it blank

**Comment by clau1313** [comment]
hi @meomancer it is working well, thanks!
