### ISSUE TITLE
info text when fetching data from GGIS through WMS

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#411]
I tried to fetch a layer from the GGIS in the SADC-GIP. I successfully connected to the GGIS server and was able to get the layer.
However, the abstract associated to our Geoserver seems outdated: 
_Abstract: A compliant implementation of WMS plus most of the SLD extension (dynamic styling). Can also generate PDF, SVG, KML, GeoRSS. Hosted by Geodan._
Can you please update it?
![image](https://user-images.githubusercontent.com/64771599/113140219-6a9db680-9228-11eb-8eba-093a5f332ffa.png)

**Comment by NyakudyaA** [comment]
Hi @ArnaudIGRAC What would you like the text to read. I can change it for you or alternatively, you can do the following
* navigate to the GeoNode
* Click on the GeoServer icon
* log in using the auth icon
* Under services in GeoServer select the `WMS`
* Edit the text and save it.

**NB** The `WMS`,`WFS` and `WCS` need to be updated

**Comment by ArnaudIGRAC** [comment]
Thank you Admire, I will try to change it myself when I find the time.
