### ISSUE TITLE
multiple feature info appear when clicking on the map

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#413]
We had decided that only one data point would be selected when clicking on the map, so one feature box would display on the right. It doesn't seem to have been implemented.
![image](https://user-images.githubusercontent.com/64771599/113253116-1a286680-92c5-11eb-8c06-68086ec94757.png)

**Comment by meomancer** [comment]
this is on mapstore, will ask @dimasciput for this

**Comment by meomancer** [comment]
hi @ArnaudIGRAC @clau1313 
This is fixeed, can you test it on staging? i will deploy it on 1.1.7

**Comment by meomancer** [comment]
hi @ArnaudIGRAC @clau1313 
could you please this this on staging and close this so i can release it to production?
