### ISSUE TITLE
Wagtail preview

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#418]
The review button in Wagtail doesn't work

![image](https://user-images.githubusercontent.com/64771599/114884741-4c2de280-9e06-11eb-93dc-4a5f6951547f.png)

I get: 
![image](https://user-images.githubusercontent.com/64771599/114884818-5e0f8580-9e06-11eb-8035-20d96cfd8521.png)

**Comment by meomancer** [comment]
This is fixed, could you try @ArnaudIGRAC ?

**Comment by ArnaudIGRAC** [comment]
thank you Irwan!
