### ISSUE TITLE
Wagtail captions

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#419]
How can I write captions in Wagtail? Is it handled like plain text?

**Comment by meomancer** [comment]
what is this captions @ArnaudIGRAC ?

**Comment by ArnaudIGRAC** [comment]
I would like to write legends below the figures. I used italic text but I wondered if there is something special for that, like in Word.

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
I added new format of image
When you add image into page, you need to choose "Captioned" format
And put "Alt text" as the caption
![Selection_069](https://user-images.githubusercontent.com/4530905/115495003-ed96b780-a290-11eb-9f36-6f3b4c99eaa5.png)

Here is the example on staging
https://staging.igrac.kartoza.com/about/japanese-test/

i will release it on 1.1.8

**Comment by ArnaudIGRAC** [comment]
Thank you Irwan.

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
this fix has been deployed to production
could you check it and close this?
