### ISSUE TITLE
Wagtail title

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#420]
Where can I change the title of the menu tree "GGIS IGRAC Docs"?
![image](https://user-images.githubusercontent.com/64771599/114896485-aaf85980-9e10-11eb-9c27-92d54ba72e9e.png)

**Comment by meomancer** [comment]
This is hardcoded @ArnaudIGRAC 
I'm going to make it able to be setup on admin site

**Comment by ArnaudIGRAC** [comment]
"GGIS Documentation"

**Comment by meomancer** [comment]
This is fixed on staging
could you check it on staging?
I will release it on 1.1.8

**Comment by ArnaudIGRAC** [comment]
Fine!

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
this fix has been deployed to production
could you check it and close this?
