### ISSUE TITLE
no access to GeoServer

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#424]
When accessing GeoServer from GeoNode I need to log in again, but my credentials don't work.

**Comment by ArnaudIGRAC** [comment]
Any help on that issue?

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 

Your username does not exist in geoserver, that's why you can't login.
I think when changed to production, the settings were ressetted.

i send you the credential to the geoserver through email

**Comment by ArnaudIGRAC** [comment]
I can access GeoServer since the new release in production
