### ISSUE TITLE
Wagtail expand left menu

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#425]
Would it be possible to make child pages visible in the left menu? like
![image](https://user-images.githubusercontent.com/64771599/115567610-bc7fac80-a2bb-11eb-91f3-e8a05658acd3.png)
Per default all child folders are collapsed

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
Updated, could you check on the staging?

it will be released in 1.1.8

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
this fix has been deployed to production
could you check it and close this?
