### ISSUE TITLE
Download well and monitoring data doesn't work

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#429]
Dear colleagues, the download functionality of wells and monitoring data doesn't work. It keeps on loading and nothing happens.
![image](https://user-images.githubusercontent.com/64771599/117280683-232bcb00-ae63-11eb-807c-d48ba2904083.png)

**Comment by meomancer** [comment]
hi @dimasciput 
could you help me change the url on the mapstore?

![Selection_140](https://user-images.githubusercontent.com/4530905/119294871-a892e600-bc7f-11eb-82ac-a09b63098929.png)
on mapstore, it is using old url
https://ggis.un-igrac.org/groundwater/well/download/

it has been changed to
https://ggis.un-igrac.org/groundwater/record/download/

**Comment by ArnaudIGRAC** [comment]
hello colleagues, any update on that issue?

**Comment by meomancer** [comment]
hi @dimasciput 
could you help me take look for this please?

**Comment by ArnaudIGRAC** [comment]
Dear colleagues, this is pending for quite some time, let's round it off

**Comment by dimasciput** [comment]
@ArnaudIGRAC @clau1313 this issue has been resolved, please test it on staging.

**Comment by ArnaudIGRAC** [comment]
hi Dimas, it seems to work but the download is very very slow. I tried downloading this well https://staging.igrac.kartoza.com/groundwater/record/1/ 
It takes 1 min per % download on average

**Comment by dimasciput** [comment]
Hi @ArnaudIGRAC I'm not sure about that, @meomancer can you check this issue?

**Comment by meomancer** [comment]
hi @ArnaudIGRAC @dimasciput 
i will check it later this week
did you filter the data or download it all @ArnaudIGRAC ?

**Comment by ArnaudIGRAC** [comment]
I had filtered them

**Comment by ArnaudIGRAC** [comment]
Dear colleagues, any update on this? It is pending for more than 2 months now :(

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
the fix is still on staging
i will release it to production tomorrow

**Comment by meomancer** [comment]
This is deployed @ArnaudIGRAC, and now it is able to download
but we have bug that the link that show on mapstore is using staging
https://github.com/kartoza/IGRAC-GGIS/issues/445

For now please using "Well Data Download List" for now until this is fixed
![Selection_314](https://user-images.githubusercontent.com/4530905/124561430-167a2200-de68-11eb-8038-e134d8785e37.png)

**Comment by meomancer** [comment]
This is fixed, thank you @dimasciput 
Can you check it @ArnaudIGRAC ?

**Comment by ArnaudIGRAC** [comment]
it seems to be working, thank you
