### ISSUE TITLE
duplicated attributes

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#430]
The attributes of this layer https://ggis.un-igrac.org/maps/new?layer=geonode:transboundary_aquifers_basicinfo&view=True are all duplicated. Any idea why?
![image](https://user-images.githubusercontent.com/64771599/117627038-0c91b680-b178-11eb-9dfd-ccc484e527b0.png)

**Comment by meomancer** [comment]
yes, i think this is coming from geonode
but we can change it on metadata, dataset attributes
i already fix it, can you check it @ArnaudIGRAC ?

**Comment by ArnaudIGRAC** [comment]
Thank you
