### ISSUE TITLE
basemap switcher

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#431]
For now we only have OSM in the background, which is ok but quite challenging if you work in arabic or russian countries for example. Could we offer some more basemaps to our users?

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
what basemap should we add?

**Comment by ArnaudIGRAC** [comment]
Good question :D 
There is this basemap from WMO http://www.wmo.int/cpdbmap/#graybasemap/ol3. Nice but it shows only the countries.
If I remember we also had a mapbox basemap in the previous GGIS. 
Any suggestion?

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/120627548-af79df80-c45b-11eb-97b7-ee311a89d18f.png)

![image](https://user-images.githubusercontent.com/178003/120627718-da643380-c45b-11eb-9147-f0c363ac0647.png)

**Comment by NyakudyaA** [comment]
Alternative basemaps http://leaflet-extras.github.io/leaflet-providers/preview/

**Comment by timlinux** [comment]
So after discussing with @ArnaudIGRAC : 

Fix the bug where the basemap switcher does not show until you hide the side panel. Then add to the layer switcher:

![image](https://user-images.githubusercontent.com/178003/120629107-60cd4500-c45d-11eb-834c-ac0e43187550.png)

This layer:

http://www.wmo.int/cpdbmap/#graybasemap/ol3.

**Comment by ArnaudIGRAC** [comment]
Any update on this?

**Comment by dimasciput** [comment]
@ArnaudIGRAC working on it today

**Comment by dimasciput** [comment]
Hi @ArnaudIGRAC @clau1313 , I have fixed this issue, please test it on the staging site.

> There is this basemap from WMO http://www.wmo.int/cpdbmap/#graybasemap/ol3. Nice but it shows only the countries.

This link no longer exists, so I added another basemap called CartoDB - Positron, please give it a try.

**Comment by ArnaudIGRAC** [comment]
It works fine, thank you!

**Comment by ArnaudIGRAC** [comment]
Please don't forget to implement that development in production

**Comment by meomancer** [comment]
Deployed @ArnaudIGRAC
