### ISSUE TITLE
Trend analysis chart

### ISSUE THREAD

**Issue by dimasciput** [kartoza/IGRAC-GGIS#434]
Show trend linear analysis in the well monitoring chart. 

![image](https://user-images.githubusercontent.com/1979569/118607010-4a2eb900-b7e2-11eb-811a-e6f9f3888471.png)

**Comment by ArnaudIGRAC** [comment]
Dear colleagues, where do we stand on this development?

**Comment by meomancer** [comment]
hi @ArnaudIGRAC @clau1313 @dimasciput 
The trendline has been added in this commit : https://github.com/kartoza/IGRAC-WellAndMonitoringDatabase/commit/eea8b72cb94d9c6de5db81101584197c0a4b5e33

Currently it is just deployed on staging to test it
Please check the example in here:
https://staging.igrac.kartoza.com/groundwater/record/59/

The chart shows the trendline in orange color
![Selection_030](https://user-images.githubusercontent.com/4530905/129664983-e350d6ba-51c2-4a9c-9f71-e2d8a8f87abf.png)

And also it shows the step trend line too
![Selection_031](https://user-images.githubusercontent.com/4530905/129664976-6a486588-4a72-4b72-a458-ec821c3a2888.png)

**Comment by clau1313** [comment]
Hi @meomancer, thanks! the linear trend looks really good.

The step trend is not supposed to show like that. A time series has either a linear or step trend, but not both. When the data has a step trend, it should look like this:

![image](https://user-images.githubusercontent.com/36033176/129684198-b43646eb-936c-4079-b02c-319f83d770c8.png)

There are some wells with this trend, for example either https://ggis.un-igrac.org/groundwater/record/52/ or https://ggis.un-igrac.org/groundwater/record/50/ (I cannot see the graph, I just created an issue about it).

**Comment by meomancer** [comment]
hi @clau1313 
How do you calculate that step? Is there any formula that we could use for that step?

> (I cannot see the graph, I just created an issue about it).
it is still on staging, will be release after this is done

**Comment by clau1313** [comment]
In theory, the formula should be in the python code...

Please let me know if you find it (or not)

**Comment by meomancer** [comment]
I can't find it @clau1313 
the library is just provide the linear trend
or where is the website that you show on the image? maybe i can get idea from there

**Comment by clau1313** [comment]
The image comes originally from a groundwater monitoring book, page 224. The formulas to estimate a step trend are in the page before (223). 

The file is attached.

[Yangxiao Groundwater monitoring book.pdf](https://github.com/kartoza/IGRAC-GGIS/files/6998935/Yangxiao.Groundwater.monitoring.book.pdf)

**Comment by meomancer** [comment]
hi @clau1313 
i think i need time to develop it
maybe can we release the current graph for now? Maybe we can release it in future version
could you create new ticket for this step trend line?

**Comment by meomancer** [comment]
hi @clau1313 @ArnaudIGRAC 
the chart is already released with version 1.2.0
I think we can close this as per original is just trendline

The step trendline is in this ticket : https://github.com/kartoza/IGRAC-GGIS/issues/453
