### ISSUE TITLE
self-created layer

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#435]
This layer says it was created on 15/5 by me, but I didn't. Very strange!
https://ggis.un-igrac.org/layers/httpmapsrefbrgmfrwxs1ggigc35_cgmw_brgm_africa_geology:AFR_CGMW_BRGM_10M_Oceanic_cob

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
i'm not sure how to check this. 
Maybe someone use your account and create it?
Or maybe someone that is admin create that layer and change the responsibility to you?

CC @seabilwe @NyakudyaA @clau1313 
did one of you create it? 

thank you
