### ISSUE TITLE
Do "empty tiled-layer cache" automatically for GGMN app

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#437]
When new data is added in the database via the GGMN app, it does not show on the GGMN platform yet, because the layer is using cache to increase performance. To refresh it, somebody needs to go to https://ggis.un-igrac.org/layers/groundwater:groundwater:Groundwater_Well_GGMN and do "Empty Tiled-Layer Cache" manually.

This process should be done automatically.

**Comment by timlinux** [comment]
@meomancer and @NyakudyaA Maybe we can just disable the cache and see how the performance is? Alternatively can we trigger a cache rebuild on inserts to the database?

**Comment by NyakudyaA** [comment]
The best solution would be a python function in the DB that is called on each insert to flush the gwc cache otherwise we can disable the cache for that layer provided the styling is optimised properly and the layer doesn't contain a lot of data.

Should I disable the cache for this layer and see how the performance is for this specific layer @timlinux

**Comment by clau1313** [comment]
Hello everyone, are there any news about this?

Thanks!

**Comment by meomancer** [comment]
hi @timlinux @NyakudyaA @clau1313 
i already disabled the cache
could you check the peformance?
https://ggis.un-igrac.org/view/well-and-monitoring-data

we can compare with staging that is still in cache
https://staging.igrac.kartoza.com/view/well-and-monitoring-data

is this correct that i just turn this off? @NyakudyaA 
![image](https://user-images.githubusercontent.com/4530905/121628183-f6428780-caa2-11eb-8868-f244b53cc7f8.png)

If the peformance is bad, i can call recache for everytime well is created/removed

**Comment by NyakudyaA** [comment]
That's correct @meomancer

**Comment by clau1313** [comment]
I tried the app again and it seems that the problem is solved :) thank you!

**Comment by meomancer** [comment]
could we close this @clau1313 ?
