### ISSUE TITLE
Getting data from Sweden automatically 

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#440]
Hi @timlinux, @meomancer, @dimasciput, @ArnaudIGRAC

The platform from Sweden: https://www.sgu.se/grundvatten/grundvattennivaer/matstationer/
The Geological Survey of Sweden (SGU) is in charge of it.
Here is some information about how to retrieve and download data from the system, but it is all in Swedish: https://www.sgu.se/produkter/geologiska-data/oppna-data/grundvatten-oppna-data/grundvattennivaer-tidsserier/ (automatic translation of the page via e.g. google translate works quite well)
My contact at SGU is Bo Thunholm (Bo.Thunholm@sgu.se). He told me that the connection can be made via a system called ATOM but I don't know it...

Please let me know if you need anything else :)

**Comment by clau1313** [comment]
Hi everyone, is there any update?

**Comment by meomancer** [comment]
hi @clau1313 
What is the organisation for the incoming data?

**Comment by meomancer** [comment]
Child of https://github.com/kartoza/IGRAC-GGIS/issues/449

**Comment by meomancer** [comment]
NOTE for me:
Data can be fetch using this:
https://resource.sgu.se/oppnadata/grundvatten/api/grundvattennivaer/nivaer/lan/03?format=json
but needs to use region code from table in : https://www.sgu.se/produkter/geologiska-data/oppna-data/grundvatten-oppna-data/grundvattennivaer-tidsserier/

**Comment by meomancer** [comment]
Could you help me understanding this data @clau1313 ?
```json
{
  "omrade-_och_stationsnummer": "101_1",
  "stationens_namn": "Balsta_1",
  "startdatum_for_matning": "1998-09-29",
  "jordart": "sand",
  "akvifertyp": "berg , öppet magasin",
  "topografiskt_lage": "inströmningsområde",
  "referensniva_for_roroverkant_m_o.h.": 15.3100,
  "rorhojd_ovan_mark_m": 0.9500,
  "total_rorlangd_m": 32.0000,
  "metod_for_matning": "klucklod",
  "kommunkod": "0305",
  "stationsanmarkning": "nivån anses opåverkad",
  "Mätningar": [
    {
      "datum_for_matning": "1998-09-29",
      "grundvattenniva_cm_u._roroverkant": 1495.0000,
      "grundvattenniva_m_o.h.": 0.3600,
      "grundvattenniva_m_under_markyta": 14.0000,
      "nivaanmarkning": "ej kontrollerad"
    }
  ]
}
```

I don't know the meaning of the most keys on this json

**Comment by meomancer** [comment]
PR is here : https://github.com/kartoza/IGRAC-WellAndMonitoringDatabase/pull/90

Hi @clau1313 @ArnaudIGRAC 
could you confirm this is correct based on the data that returned?

```
stationens_namn = name
referensniva_for_roroverkant_m_o.h. = top_of_well_elevation (in meters)
rorhojd_ovan_mark_m = height_of_tube (in meters)
ground_surface_elevation = top_of_well_elevation - height_of_tube
````

and also what is the organisation for this one?
I would like to test it on staging, what organisation is it?

**Comment by clau1313** [comment]
I don't recognize this station (101_1). We should retrieve from the swedish system the same stations that are already in the GGMN. 

All wells from Sweden should be associated with the organisation: "Geological Survey of Sweden (Sweden)"

I just realised that there are some wells from Sweden that are not associated to the right organisation, for example https://ggis.un-igrac.org/groundwater/record/69/edit   I saw this problem before with other wells, and I solved "by hand" (one by one, stations from Germnay and the Gambia).

If I give you a list of the stations that belong to Sweden, could you associate them to the right organisation all at once?

**Comment by meomancer** [comment]
HI @clau1313 
That station 101_1 is coming from the API
The name is Balsta_1
https://resource.sgu.se/oppnadata/grundvatten/api/grundvattennivaer/nivaer/lan/03?format=json
So we need to just get the measurements data for the well/station that are already in our ggmn data?
Is it same with Canada and Norway?

> If I give you a list of the stations that belong to Sweden, could you associate them to the right organisation all at once?

Yes, please @clau1313

**Comment by clau1313** [comment]
With Canada and Norway we should get only the stations that are already in the system.

With Canada we can get all of them

Attached is the list with the stations from Sweden.

[Wells Sweden.xls](https://github.com/kartoza/IGRAC-GGIS/files/6999041/Wells.Sweden.xls)

**Comment by clau1313** [comment]
Hi @meomancer, is there any update?

**Comment by meomancer** [comment]
hi @clau1313 
it is finished but need to test and deploy it on staging to be tested
I will do it on my next igrac time

**Comment by clau1313** [comment]
hi @meomancer, thanks, please let me know how it goes

**Comment by clau1313** [comment]
It is ok! Thanks @meomancer
