### ISSUE TITLE
Change charting library

### ISSUE THREAD

**Issue by dimasciput** [kartoza/IGRAC-GGIS#442]
Previously we used chart.js as a charting library, it doesn't work well with large data that the system has.
So we are going to change the library to highcharts instead.
See some demo here : https://www.highcharts.com/demo.

@ArnaudIGRAC or @clau1313 needs to buy the license to use this library.

**Comment by ArnaudIGRAC** [comment]
Hi Dimas, We are a non-profit organization so we are allowed to use the code free of charge under the license Creative Commons Attribution-NonCommercial 3.0 (I have already requested and received a license for IGRAC). You can go on with this development.

**Comment by dimasciput** [comment]
@ArnaudIGRAC that's a great news

**Comment by meomancer** [comment]
hi @ArnaudIGRAC @clau1313 @dimasciput 

Staging updated using highchart
It is already returns everydata (without min/max, per year, per month like before)

This well has the highest number of level measurement in our staging (140k)
https://staging.igrac.kartoza.com/groundwater/record/9571/read

Please check it for the performance and also some input
And also, it is using cache that will be generated if we save a measurement on specific well

When this comment written, number of well that already generated for cache is 6439/29038
so some of well is still not having cache (it will show no data)

This also fix https://github.com/kartoza/IGRAC-GGIS/issues/433

![Selection_339](https://user-images.githubusercontent.com/4530905/125412308-fc50be80-e3e8-11eb-8e2a-012afc370cb3.png)

**Comment by ArnaudIGRAC** [comment]
Thank you Irwan, I find it great! It looks very clear and it took no more than 6 sec to show the entire chart. @clau1313 what do you think?

**Comment by clau1313** [comment]
Hi @meomancer and @ArnaudIGRAC, it looks great! The chart loaded really fast for me as well

**Comment by meomancer** [comment]
hi @clau1313 @ArnaudIGRAC
the new chart is already released with version 1.2.0
Please check it on https://ggis.un-igrac.org/
