### ISSUE TITLE
Deleting wells from GGMN

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#443]
Good afternoon, I would like to delete wells from Switzerland that are in the GGMN, but I cannot find a way to do so... can you please help me? 

I see this:

![image](https://user-images.githubusercontent.com/36033176/124137452-ffad8700-da85-11eb-9d20-86e2c047e85e.png)

There should be a button somewhere to delete the selected well, no?

Can you please help me? Thank you

**Comment by meomancer** [comment]
hi @clau1313 
To delete selected one, click bottom selection and there will be selection like this
![Selection_292](https://user-images.githubusercontent.com/4530905/124140721-ed960d80-dab2-11eb-957d-470115b8def3.png)

After that click go
![Selection_292](https://user-images.githubusercontent.com/4530905/124140764-f7b80c00-dab2-11eb-81b6-44178b629297.png)

**Comment by clau1313** [comment]
Thanks @meomancer!!
