### ISSUE TITLE
[ggis.un-igrac.org] A user has requested access to the site

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#450]
We have received several requests to access the GGIS lately. Some of them are obvious spams, I am not sure for the others. Why do we receive requests sometimes and sometimes not?

**Comment by ArnaudIGRAC** [comment]
Any answer? I keep on receiving a lot of requests. It was not the case before. Why? Do these people/spams need my approval to reach the website?

**Comment by NyakudyaA** [comment]
@ArnaudIGRAC I have seen that they are over 400 users registered in the system. Is this number supposed to be this big. If not What criteria can I use to cleanup the users so that afterwards we can then monitor what is happening

**Comment by ArnaudIGRAC** [comment]
Hi Admire, apparently I receive a request for every new user in the GGIS. It was not the case before. I haven't replied any of these requests but these users appear nonetheless in the system as Active. So I wonder what use those request emails are for.

I cleaned the list of users 2 weeks ago. Our policy is that everybody can register in the GGIS as long as they provide their real name/surname. But very few users comply, because this rule doesn't appear in the registration form, only in the documentation.  Would it be possible to update the registration form with a message like: "Please provide your name and surname. Unidentified users will be deleted." ?

**Comment by ArnaudIGRAC** [comment]
I wonder if these people register in the website or in the app...

**Comment by NyakudyaA** [comment]
@ArnaudIGRAC I have just tested this and I see that a user self registers on the site but they are automatically logged in. It seems that the approval workflow is not setup or is not working correctly. So what we need to do is the following

* To stop yourself from receiving notifications you need to deactivate them from https://ggis.un-igrac.org/notifications/settings/

## Approval Workflow
* User visits the site and registers to login
* Admins will receive a notification indicating that specific users need to access the site. You will then grant or reject the access to the site
* Once approved a user will then get a notification to let him know that he can now login to the site

**Note** This will work only if SMTP is setup on the server

Yes , a message can be added to indicate this as you have described it "" Once logged in, please update your username, surname and other additional requirements through the user profile menu (https://ggis.un-igrac.org/people/profile/testuser/?limit=5&offset=0). Unidentified users will be deleted." ?

**Comment by ArnaudIGRAC** [comment]
Thank you Admire, let's do that! I am not sure whether SMTP is setup though (#360)...

**Comment by NyakudyaA** [comment]
> Thank you Admire, let's do that! I am not sure whether SMTP is setup though (#360)...

@lucernae Can you take over this and just make sure the approval workflow is working. It seems the env variable 
`ACCOUNT_APPROVAL_REQUIRED` is not set on the server

**Comment by lucernae** [comment]
I can set this, however note that newly registered users will still send email to request for approval.

**Comment by ArnaudIGRAC** [comment]
> I can set this, however note that newly registered users will still send email to request for approval.

Have you implemented it? 

Please don't forget to add the following message in the registration window:
"Once logged in, please update your user profile with your name, affiliation and any other relevant information. Unidentified users will be deleted."

**Comment by ArnaudIGRAC** [comment]
Dear colleagues, I noticed two issues:

1. When an account is activated, the notification email falls in the spam box. Can you do something about that? If not, could you at least warn users that the notification email could end up in their spam box?

2. New users are not given the possibility to provide their full name and affiliation before I activate them or not. This means that I have very little clue to determine whether a new user is a potential spam. What do you suggest? Is it possible to let users enter their full name and affiliation before I make them active? If not, we might as well activate all users automatically. Would that be a risk for us and for other users?

**Comment by ArnaudIGRAC** [comment]
I forgot to mention, related to issue #1, that the content of notification email should be revised. Here is what I received:

> Your account has been approved and is now active. (test_register)<br/>
You can use the login form at: http://IGRAC

**Comment by meomancer** [comment]
> When an account is activated, the notification email falls in the spam box. Can you do something about that? If not, could you at least warn users that the notification email could end up in their spam box?

The spam email problem is closed by this ticket
https://github.com/kartoza/IGRAC-GGIS/issues/360#issuecomment-781312751
We can do create warning to make user to check the spam 

> New users are not given the possibility to provide their full name and affiliation before I activate them or not. This means that I have very little clue to determine whether a new user is a potential spam. What do you suggest? Is it possible to let users enter their full name and affiliation before I make them active? If not, we might as well activate all users automatically. Would that be a risk for us and for other users?

I need to check this on the library if it is possible or not

**Comment by ArnaudIGRAC** [comment]
> > New users are not given the possibility to provide their full name and affiliation before I activate them or not. This means that I have very little clue to determine whether a new user is a potential spam. What do you suggest? Is it possible to let users enter their full name and affiliation before I make them active? If not, we might as well activate all users automatically. Would that be a risk for us and for other users?
> 
> I need to check this on the library if it is possible or not

Please do, it would really be the best option if new users could provide their full name and affiliation at the moment of signing up. When do you think you could do that?



> > When an account is activated, the notification email falls in the spam box. Can you do something about that? If not, could you at least warn users that the notification email could end up in their spam box?
> 
> The spam email problem is closed by this ticket [#360 (comment)](https://github.com/kartoza/IGRAC-GGIS/issues/360#issuecomment-781312751) We can do create warning to make user to check the spam

We will address that later, once you have figured out the previous point above.

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
adding firstname and lastname on registration is doable 
i'm going to deploy the update tomorrow

**Comment by ArnaudIGRAC** [comment]
Great! Please also include the organization!

What we need is :
- First name
- Last name
- Email address
- Organization Name

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
Deployed
![Selection_024](https://user-images.githubusercontent.com/4530905/152456056-7a1cc076-58ff-4024-80d3-71d788dfc479.png)

**Comment by ArnaudIGRAC** [comment]
Thank you Irwan! In order to round this off, could you please modify the content of the notification email, which is currently:

> Your account has been approved and is now active. (test_register)<br/>
You can use the login form at: http://igrac/

where test_register is the username I created. 

I would replace it with:

> Your account has been approved and is now active: test_register
Discover the GGIS and update your user profile at https://ggis.un-igrac.org/

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
This will be fixed with : https://github.com/kartoza/IGRAC-GGIS/commit/ecf803e6046117052030b891b4b1891f21594cc2

Will deploy it in 1.4.5
