### ISSUE TITLE
Time series graphs do not appear in GGMN

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#451]
Good morning @meomancer. I don't see any graphs in the GGMN, from any well. This is an example from well https://ggis.un-igrac.org/groundwater/record/3167/

![image](https://user-images.githubusercontent.com/36033176/129683430-748958d6-3281-45e2-9f05-db81ac2e31ba.png)
 
Graphs dont show both in the GGMN main page and in the form

**Comment by meomancer** [comment]
hi @clau1313 
this is not released yet
i will release it after everything about chart is done
(We just release it once for a new feature)

**Comment by meomancer** [comment]
hi @clau1313 
this is already released
please check it
