### ISSUE TITLE
dataset attributes 

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#455]
Why can I not set up the attributes of this layer? The only option is to use a custom template
https://ggis.un-igrac.org/layers/geonode:transboundary_aquifers_basicinfo/metadata

**Comment by meomancer** [comment]
i'm not sure, could you help me check it @seabilwe ?

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
i'm sorry but @seabilwe and i can check this next week

**Comment by ArnaudIGRAC** [comment]
No hurry Irwan, next week is fine

**Comment by seabilwe** [comment]
Hi @ArnaudIGRAC cc @meomancer. I think this is what you are looking for (in GIF below). The option you mentioned above is mostly for the metadata and whenever I need to edit the attribute table of a layer or add features to the attribute table, I use the Edit data button in the Editing tools. 


![editing attribute table](https://user-images.githubusercontent.com/56301949/134009351-84fcc995-9b0c-46dd-8c91-fa59ffc15c30.gif)

**Comment by ArnaudIGRAC** [comment]
Hi Seabilwe, I want to edit the labels of the attributes, which you can usually do in section 4 of the metadata wizard
![image](https://user-images.githubusercontent.com/64771599/134010182-5b640124-7e94-4ac8-b853-43ccd7aaa669.png)
but it doesn't work for this layer https://ggis.un-igrac.org/layers/geonode:transboundary_aquifers_basicinfo/metadata

**Comment by seabilwe** [comment]
> Hi Seabilwe, I want to edit the labels of the attributes, which you can usually do in section 4 of the metadata wizard
> ![image](https://user-images.githubusercontent.com/64771599/134010182-5b640124-7e94-4ac8-b853-43ccd7aaa669.png)
> but it doesn't work for this layer https://ggis.un-igrac.org/layers/geonode:transboundary_aquifers_basicinfo/metadata

@meomancer I had a look a number of layers randomly on the instance and so far none of them show this, where we can't see the attribute table when the **Use a custom template** button is turned off as shown by @ArnaudIGRAC in the image. 

I compared it with the Somaliland instance, and one of the layers have a similar issue where the attribute is not appearing.

When I click the button, I am supposed to see this
![Peek 2021-09-20 15-40](https://user-images.githubusercontent.com/56301949/134014677-3945cbf1-9b9a-4f1d-8319-bce02c0a790b.gif)

Instead, I am not getting a table that does not show the attributes associated with the layer.
![Peek 2021-09-20 15-41](https://user-images.githubusercontent.com/56301949/134014747-989be63e-6a52-4125-a393-293f2b8c6782.gif)

**Comment by seabilwe** [comment]
I'll continue to have a look at the layers randomly in the instance to see if I cannot find a similar issue.
