### ISSUE TITLE
Getting more data from Norway

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#461]
Hi @meomancer, I have another question related to the data from Norway.

As I mentioned before, they are happy with this development, and now they would like to share even more data. They offer me to send me a list with the stations and metadata they would like to share.

Would this be very time consuming/an extra development? I don't know if this could be included in the original development "getting data from Norway".

Also, some of the stations in Norway include other time of data (for example, temperature) so to the previous request we could add getting this type of data as well.

Please let me know what you think. Thanks!

**Comment by meomancer** [comment]
hi @clau1313 
After i checked the API, we don't need the last part because there is no "12.343.12.5130.2" in the API
The API just has 3 sections (12.343.12)

> So, my question is: when I add the new wells, shall I also cut the last part of the ID, o shall I add the whole thing? for instance, for the new well "Ørskogfjellet" (second line in the Excel file) the ID should be 101.4.1 or 101.4.1.5130.1?

They has 101.4.1
101.4.1.5130.1 is not found on API

The script already rerun
I make it manually run now because the process is really big and can make server down
I will make it rerun every weekend later

**Comment by clau1313** [comment]
hi @meomancer, thanks for your answer. I just uploaded the new wells.
I also checked the other wells, and I see that there is updated data.
One more question: if you make the re run on the weekend, could we see groundwater levels in the new wells next week?

**Comment by meomancer** [comment]
yes @clau1313 
please create new wells so i can run the script

**Comment by clau1313** [comment]
hi @meomancer, I already created them. Do you need also a list with their names?

**Comment by meomancer** [comment]
hi @clau1313 
I have run the script
They are already pulled
Could you check it?

Some notes from me

Wells below does not found on the list of station on the API
- 12.345.1
- 139.41.3
- 166.17.2
- 20.34.2
- 209.9.2

Wells below : Does not have data for water level. It is just temperature (not fetched yet)
- 185.2.3

Wells below : API is not working
- 2.714.1 : https://hydapi.nve.no/api/v1/Observations?StationId=2.714.1&Parameter=5130&ResolutionTime=1440&ReferenceTime=2003-09-28T11:00:00Z/2021-10-28T11:00:00Z

**Comment by clau1313** [comment]
Hi @meomancer, I forwarded your comments to NVE and this is what they replied:

12.345.1 this station is abandoned, no data after 2018
139.41.3 not real-time transfer of data after 2018
166.17.2 abandoned, but replaced by 166.17.3 (note that the last digit is different). This new station has a data series that is connected to the data series of 166.17.2, so that this series has the ID 166.17.3.5130.0
20.34.2 abandoned
209.9.2 abandoned
2.714.1 this should be active and with real-time transfer; check that the last digit in the ID is 2 (2.714.1.5130.2)
185.2.3 data for groundwater stage are coming in to NVE. Please check that the last digit in the ID is 2 also here

Is it possible to retrieve data from stations that are not longer active? (so, retrieve the old data once). Or are this stations not online anymore?

Thanks!

**Comment by meomancer** [comment]
I'm not sure how to retrieve the data @clau1313 
could you ask them to explain how to retrieve the data for every stations?

**Comment by clau1313** [comment]
hi @meomancer, I asked them and now I am waiting for their answer. I will let you know when I know more!
