### ISSUE TITLE
Add permanent layers to GGMN viewer

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#464]
hi @meomancer, I would like to add some permanent layers to the GGMN viewer, so when it is opened the layers are there but turned off, like this:

![image](https://user-images.githubusercontent.com/36033176/140302292-acd2ebb2-0cda-4958-9b83-8ef13eb6118a.png)

I heard that it is easy to do but I don't know how... can you explain it to me please? Thanks!

Cheers,
Claudia

**Comment by meomancer** [comment]
hi @clau1313 
i think you need to save it?
which layer and what server is it?

**Comment by clau1313** [comment]
hi @meomancer, the layers are "2015 - Transboundary Aquifers of the World" and "Groundwater resources and recharge (mm/a)" (by the way, I cannot add this last one any more, it appears unavailable - but ast Thursday it was there....), and the portal is the GGMN: https://ggis.un-igrac.org/view/ggmn 

Maybe in the future I would like to add more layers, that's why I would like to learn how to do it myself if possible...

**Comment by meomancer** [comment]
i understand now
@clau1313 
the /view/ is just the view with just read only (i think we need to remove editing ability in there)

to edit that map, you need to access here
https://ggis.un-igrac.org/maps/1838/edit

if you edit there, the https://ggis.un-igrac.org/view/ggmn will be edited too
basically https://ggis.un-igrac.org/view/ggmn is just read only
https://ggis.un-igrac.org/maps/1838/edit is for editing

**Comment by clau1313** [comment]
hi @meomancer, thanks, but I don't understand how to keep the changes at https://ggis.un-igrac.org/maps/1838/edit... once I add the layer I want to keep, how can I save it? when I leave the page and come back again, the changes are not there anymore....

**Comment by meomancer** [comment]
hi @clau1313 
to save it, click here (top-right)
![Selection_305](https://user-images.githubusercontent.com/4530905/141884337-29a12275-aff4-4e9a-9562-59389936b0fe.png)

It will show option to save it
![Selection_304](https://user-images.githubusercontent.com/4530905/141884358-a5ccaec0-8fb3-4036-8748-992a92c9e45c.png)

**Comment by clau1313** [comment]
hi @meomancer, thanks!
