### ISSUE TITLE
"Data out of date" message when dowloading data

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#468]
hi @meomancer, there is a user trying to download all data from the Well and Monitoring site in GGIS. She tried a couple of times, but whe she reaches 80% it stops and get the message "data out of date". Do you know what could be the problem? Thanks!

![image](https://user-images.githubusercontent.com/36033176/147232257-ebb99582-ec35-4493-877b-43d2bca07313.png)

**Comment by meomancer** [comment]
hi @clau1313 
i think when in progress, the server was down, making the progress stopped
Data out of date means that when downloading, the data was 14 December. But when we look into it now, the new data is already 23 December. So meaning that when downloading, the data that will be downloaded is data up to 14 december

Could you ask her to redownload?

**Comment by clau1313** [comment]
hi @meomancer, thanks! I think it worked out at the end. 

by the way, happy new year 2022!! :)
