### ISSUE TITLE
new user IGRAC-GGIS

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#472]
Can you please include this github user to the project, so he can raise issues? thank you
IGRAC-GGIS

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
I can't find the user
https://github.com/IGRAC-GGIS

Could you provide the link to the github user?

**Comment by ArnaudIGRAC** [comment]
Sorry Irwan, the user name is GGIS-IGRAC, not IGRAC-GGIS...
https://github.com/GGIS-IGRAC

**Comment by meomancer** [comment]
Invitation sent @ArnaudIGRAC

**Comment by ArnaudIGRAC** [comment]
> Invitation sent @ArnaudIGRAC

?? I signed in as GGIS-IGRAC but I am still unable to assign you or anybody to issues under our Kartoza/IGRAC-GGIS project.

**Comment by meomancer** [comment]
i think you need to accept inviation @ArnaudIGRAC 
![Selection_016](https://user-images.githubusercontent.com/4530905/151763802-713fbb04-d19c-4a41-a111-4780a7f61f29.png)

there should be email or notification in the bell icon on the top-right

**Comment by GGIS-IGRAC** [comment]
Thank you Irwan, it works now!
