### ISSUE TITLE
GGIS and SADC-GIP unavailable

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#473]
Error message is 
503 Service Temporarily Unavailable

**Comment by NyakudyaA** [comment]
igrac is back up. Seems the sadc has corrupted volume so busy looking at it

**Comment by NyakudyaA** [comment]
> igrac is back up. Seems the sadc has corrupted volume so busy looking at it

@ArnaudIGRAC The SADC GIP was fixed yesterday by @dominicschaff . The server had run out of space. Going forward we are going to mount extra storage space on the server then split the geoserver data directory and the geowebache to be on different storage drives
