### ISSUE TITLE
Activate users - batch

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#475]
Would it be possible to make several users active in one click instead of activating them one by one?

![image](https://user-images.githubusercontent.com/64771599/152761620-922d562a-1c7f-4b14-9cad-5514d25f62aa.png)

**Comment by meomancer** [comment]
This will be fixed by https://github.com/kartoza/IGRAC-GGIS/commit/139b0600542e187091ade7b223a52ad65cf80bb1
