### ISSUE TITLE
headers GGMN attribute table

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#476]
1. The headers of the GGMN attribute table are not the "clean" ones that appear in the feature box, can you please update it?

OK
![image](https://user-images.githubusercontent.com/64771599/153851047-8941d964-47ff-4a63-8e96-0d832419284c.png)

NOT OK
![image](https://user-images.githubusercontent.com/64771599/153850879-1b68d16f-c5ca-4ff0-b219-fe98f0c8ec15.png)

2. The "id" field (forst one in the attribute table) is always empty and should be removed

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
Currently it is just working in
https://ggis.un-igrac.org/view/well-and-monitoring-data

For the GGMN i need @dimasciput to update this

**Comment by ArnaudIGRAC** [comment]
@clau1313 remarked that the attribute table should not open per default, but only if the user opens it. The GGMN viewer should appear normally, with the layer box on the left. Can you please update it?

Current:
![image](https://user-images.githubusercontent.com/64771599/158178528-70652777-fdf1-4556-84d4-29a590aa7899.png)

Should be:
![image](https://user-images.githubusercontent.com/64771599/158178608-883e8c5d-0e4d-48c7-823a-e2ab97fb7bdb.png)

**Comment by ArnaudIGRAC** [comment]
Any update on this? We are organizing a workshop next week on the GGMN, so we would like it be ready by then

**Comment by meomancer** [comment]
thank you @dimasciput 

Released 1.4.6 : fix this issue
Can you check it @ArnaudIGRAC ?

**Comment by ArnaudIGRAC** [comment]
The issue now is the initial scale of the map, with empty spaces on the sides and Antartica taking a lot of space.
![image](https://user-images.githubusercontent.com/64771599/159882556-c6e8d573-c856-4826-a9ea-e1ea47028e53.png)
While trying to modify the initial view, I found out that https://ggis.un-igrac.org/maps/1838 and https://ggis.un-igrac.org/view/ggmn are not connected anymore. 

- https://ggis.un-igrac.org/view/ggmn: headers ok but initial view not ok
- https://ggis.un-igrac.org/maps/1838: headers not ok but view ok

**Comment by dimasciput** [comment]
@ArnaudIGRAC they are connected, but the header only shows up in the ggmn view. Is that okay or do you wan to show the updated header in the maps view too?

**Comment by ArnaudIGRAC** [comment]
@dimasciput it is okay, no need to update the headers. But the view is an issue, how can I change that?

**Comment by ArnaudIGRAC** [comment]
dear colleagues, we still have an issue with the scale of the GGMN viewer and the Well and Monitoring Data viewer
https://ggis.un-igrac.org/view/ggmn
https://ggis.un-igrac.org/view/well-and-monitoring-data
When you reach these viewers, the map appears at the right scale but ater a few seconds it gets smaller (see screenshot in previous post). Can you please resolve this problem?

**Comment by ArnaudIGRAC** [comment]
Hi @dimasciput and @meomancer Let's use this round of developments to finally solve this issue.

**Comment by ArnaudIGRAC** [comment]
Hi colleagues, we are happy with the view of the GGMN viewer. Please make sure that it remains like that when moving repro to production. Please also align the view of the "Well and monitoirng data" viewer on the "GGMN viewer", the scale is right but we see too much of the southern hemisphere and not enough of the northern hemisphere.

- GGMN (OK)

![image](https://user-images.githubusercontent.com/64771599/205637832-473e976d-59fb-4e1b-a7d1-2ab8b538cea5.png)

- Well and monitoring data (central point too far south)

![image](https://user-images.githubusercontent.com/64771599/205637947-642f0e6e-cc1b-41f8-9027-69a5a297451a.png)

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
I have fixed the Well and monitoring data extent
Could you check it? it is just change the extent on https://ggis.un-igrac.org/maps/56/edit#/

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, the headers of the attribute table of the GGMN viewer are not what they used to be:
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/f8c95dce-6546-4b06-b62d-b16a39312e69)

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
This is fixed, please try it
