### ISSUE TITLE
GGIS unavailable

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#478]
503 Service Temporarily Unavailable

**Comment by ArnaudIGRAC** [comment]
Back online, but please check #470

**Comment by ArnaudIGRAC** [comment]
503 Service Temporarily Unavailable
nginx/1.17.10

**Comment by NyakudyaA** [comment]
Hi @ArnaudIGRAC The site is up. Can you ping me and @tharanathkartoza for a quick response

**Comment by ArnaudIGRAC** [comment]
the GGIS is unavailable again, this time with the following notification
![image](https://user-images.githubusercontent.com/64771599/175238840-aa0ee588-7d67-4331-b3a5-490db240e18c.png)

**Comment by NyakudyaA** [comment]
Checking @ArnaudIGRAC

**Comment by ArnaudIGRAC** [comment]
our website is also unavailable, so the issue could be on this side

**Comment by NyakudyaA** [comment]
It looks good on our side here. Can you check the DNS part
