### ISSUE TITLE
Issues with ggmn data download

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#479]
There are issues with the download of well and monitoring data and ggmn data.

1. When logged in as dummy_user (no admin rights) and trying to download data, this is how the progress of the download looks like
![image](https://user-images.githubusercontent.com/64771599/153866924-92df1e69-0818-4f6a-9c03-2eb4dd6bfd1c.png)
https://ggis.un-igrac.org/groundwater/download?task_id=447bb19d-1b00-4476-be90-10d6784e705d
Note that this download has started on Feb. 10, 2022, 2:47 p.m., so 4 days ago, at a time when I didn't download data as dummy_user... very strange!

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
download progress is done on background
i think the problem is when the progress is still running, the server was down and making the progress stop

it is because this
https://github.com/kartoza/IGRAC-GGIS/issues/470

**Comment by ArnaudIGRAC** [comment]
Thanks Irwan, let's address #470 
Would it be possible to also use cache for the download of the full well and monitoring dataset?

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, some update from my side. Yesterday I started the download of the full database using my account "arnaud". I checked the progress of the download several times and it went very slowly. I just checked now and found out that the download is stuck, quite interestingly at 79%, like in my previous attempt using "dummy_user" (see above). Any idea why? 
I get an error message saying `Data out of date`
![image](https://user-images.githubusercontent.com/64771599/154073674-745b1e65-2e9a-4a9b-8e96-fa9fb6a378b5.png)

**Comment by ArnaudIGRAC** [comment]
If you look at all download sessions, you will notice that download sessions initiated by the same users stop at the same percentage (79% for me), 68/69% for user 617...
![image](https://user-images.githubusercontent.com/64771599/154079184-584b156b-3ed8-4c94-9fcb-86e2b94c75fa.png)

I tried ot download one single data point but it is also increadibly low... 8% after almost 20 minutes

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, we could do as you suggest. However, some users might want to download the entire set of data (including monitoring data) for which they have permission. I have one such request pending. Could you please provide us with a download file containing all the data?

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
Note this is using my local data, so the data is just little
But the example will be like this

**1. If we download from map**
[5957df30-4a0e-40ff-9ad3-81facf0b02d2.zip](https://github.com/kartoza/IGRAC-GGIS/files/8115159/5957df30-4a0e-40ff-9ad3-81facf0b02d2.zip)

**2. If we download from a well map (which download all well data)**
[c75d6e87-35ff-47d3-83ad-e85dde156e85.zip](https://github.com/kartoza/IGRAC-GGIS/files/8115162/c75d6e87-35ff-47d3-83ad-e85dde156e85.zip)

**Comment by ArnaudIGRAC** [comment]
It looks ok. 
But in the future we might have issues with the Excel format, because the maximum number of rows is about 1,000,000 I think. Is csv not a better option?

**Comment by meomancer** [comment]
it is different with the original request that using excel and has different tab
csv does not using tab @ArnaudIGRAC, so there is development to change everything

but i think it is save now, because wells number is still lesser than 1.000.000
and 1 well has measurement that is still lesser than 1.000.000

**Comment by ArnaudIGRAC** [comment]
Ok then! Can you please proceed with the update and provide me with the data dump?

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
what data dump do you mean? is it the database? 

ok, i will release with the other updates tomorrow

**Comment by ArnaudIGRAC** [comment]
Yes, I would like a copy of the entire database, which I can share on request. Thanks
