### ISSUE TITLE
Update upload file

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#482]
Hello Irwan,

Claudia informed me that the upload file needs to be updated, to match the architecture of the database, i.e. the fields "Feature type" and "Country" need to be updated. Can you please replace the current upload file with this one?
[New upload file.xlsx](https://github.com/kartoza/IGRAC-GGIS/files/8316219/New.upload.file.xlsx)

**Comment by meomancer** [comment]
hi @ArnaudIGRAC @clau1313 
This ticket needs development for updating it
Because it will also change the code

i will ask time to @timlinux for this

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, in fact I only changed the headers of the excel file, the overall structure hasn't changed, so it is only a matter of replacing the old file with the new one. Is development required for that? @clau1313 correct me if I am wrong.

**Comment by meomancer** [comment]
ok @ArnaudIGRAC 
if it is just change the headers and also keep the value on the excel like the old one, i can replace it tomorrow

**Comment by ArnaudIGRAC** [comment]
hi Irwan, @clau1313 noticed that the upload file has not been updated here https://ggis.un-igrac.org/groundwater/batch-upload
Can you please round this off?
