### ISSUE TITLE
We need to update materialized views

### ISSUE THREAD

**Issue by meomancer** [kartoza/IGRAC-GGIS#484]
The MVs:
- mv_well_with_uuid
- mv_well_ggmn

We can refresh it on:
- By code : when well is updated
- On celery
- On cron job

**Comment by NyakudyaA** [comment]
You will need to run something like below

```
CREATE OR REPLACE FUNCTION update_mv()
RETURNS trigger LANGUAGE plpgsql
AS
$$
BEGIN
  Referesh materialized view mv_well_ggmm;
  RETURN NEW;
END ; 
$$;

-- Create a trigger to populate to update the mview
CREATE TRIGGER mv_update_well
  BEFORE INSERT
  ON well_table
  FOR EACH ROW
  EXECUTE PROCEDURE update_mv()
````

if your views have a column with a unique value and an additional unique index then you should use `REFRESH MATERIALIZED VIEW CONCURRENTLY`

**Comment by meomancer** [comment]
thank you @NyakudyaA 
will do it

**Comment by meomancer** [comment]
Added by @NyakudyaA suggestion
