### ISSUE TITLE
Error when creating new well in GGMN

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#485]
I get the following error: 
![image](https://user-images.githubusercontent.com/36033176/164458174-42def5e5-8399-46ec-83fa-ab36bdefd12c.png)

I already checked if the mandatory fields are filled in (original ID, name, feature type, latitude, longitude, and organisation).. What could it be?

**Comment by meomancer** [comment]
Could you retry @clau1313 ?

**Comment by ArnaudIGRAC** [comment]
Hi @clau1313, is it working now?
