### ISSUE TITLE
Help with error in batch upload

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#486]
I tried to do a batch upload but it didn't work (I think I know what was the error, I included "/" in the date column instead of "-"). But the problem is that now the tool has been stucked for more than one hour, and I don't have the option of uploading anything anymore. It looks like this:

![image](https://user-images.githubusercontent.com/36033176/164503226-122345d5-c14a-4f44-82e8-0926202e0404.png)

Can you please "reset" it so I can upload the file again? Or is there something I can do? Thank you.

**Comment by meomancer** [comment]
Could you retry @clau1313 ?

**Comment by clau1313** [comment]
Hi @meomancer, I just tried. I have several files to upload, so I tried with the first one and it worked fine, but with the second one I got the same error: it looks like the system is stuck again.

By the way, I realised that the file I was trying to upload the other day was finally uploaded with no problems. So it seems that the problem didn't occur because of the file.

PS: I don't know why I didn't get an email from github saying that you replied to my message 7 days ago, strange...

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, do you have an answer to Claudia's question?

**Comment by meomancer** [comment]
hi @clau1313 
I have checked the code and it is correct and i also have checked on my local and it is also working fine
I want to test it but needs a good data (not sample data)
Maybe in future could you provide me several files for batch upload? so i can check it?
