### ISSUE TITLE
#1 Permission levels

### ISSUE THREAD

**Issue by meomancer** [kartoza/IGRAC-GGIS#487]
When developing the new GGIS, significant efforts were made to accommodate different permission levels for viewing and downloading well and monitoring data. The reason is that the GGIS used to support the exchange of data between countries sharing transboundary aquifers, and data were often considered sensitive by the countries. However, in the last few years, the GGIS has not been used in TBA projects. 

On the contrary, IGRAC has supported and will be supporting the creation of independent data sharing platforms like the SADC-GIP, under the responsibility of local institutions like river basin organizations. These permission levels have become rather obsolete and in opposition IGRAC’s views on open data. In the meantime, they make the upload and download of data more complicated. In order to simplify the system for administrators, data providers and data users, it is suggested to simplify the permissions as follow:

![Selection_053](https://user-images.githubusercontent.com/4530905/171351638-89570bf9-af65-4c3b-b51f-ab95bf7afc59.png)

**Comment by ArnaudIGRAC** [comment]
Hello Irwan, I am checking the staging website and monitoring data are not available 
![image](https://user-images.githubusercontent.com/64771599/187466850-7d8df693-42df-459f-ba61-8c4adb44f1ed.png)

**Comment by ArnaudIGRAC** [comment]
The _who can view_ and _is it downloadable_ options must be removed because anybody will have these two permissions
![image](https://user-images.githubusercontent.com/64771599/187467306-512d4abf-511a-420a-9c61-455cf05e75d4.png)

**Comment by ArnaudIGRAC** [comment]
Also for batch upload 
![image](https://user-images.githubusercontent.com/64771599/187469497-7177f6c9-ccf0-411c-993f-78509ed1d8b6.png)
where we need instead the following options (just like for adding single records)
![image](https://user-images.githubusercontent.com/64771599/187469659-0262b5ab-1512-467f-a950-cc9e414fa7df.png)

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
This has been updated, could you check it?

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, in the batch upload panel it should be "Restrictions other" instead of "Constraints other"
![image](https://user-images.githubusercontent.com/64771599/187869046-626bf947-7c3c-4d85-92ee-c87ff9f0f36f.png)

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
Updated, please check it

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, the upload panels have been updated but the permissions have not been implemented, see for instance
![image](https://user-images.githubusercontent.com/64771599/187891591-d3bbb2cc-9878-4669-843e-e6221580cc63.png)
I can't access this well without logging in

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
Fixed
