### ISSUE TITLE
#5 Registering

### ISSUE THREAD

**Issue by meomancer** [kartoza/IGRAC-GGIS#490]
In the current configuration, new users need to be validated in the admin section of the GGIS, based on name, surname, email address and affiliation. This is to avoid bots to sneak in the website. However, the validation step takes time and it is often not easy to recognize real users: e.g. many users don’t have an affiliation (they write in their name), or they write in foreign languages. 

Since the well and monitoring data become available to all users, only data providers will need to register in the GGIS. The register form should clearly state that registering is useless except for the upload of data. The register form should include additional mandatory fields, such as position (in their organization) and location. In addition, they should tell why they want to join the GGIS (this would be only for internal use, so admins can eventually filter).

In addition, the register form should clearly state that the reply from admins (whether their registration is validated or not) might take a few days and end up in spam box.

**Comment by ArnaudIGRAC** [comment]
Here are a few edits to the sign up page:
![image](https://user-images.githubusercontent.com/64771599/187473006-172d2ffe-d98b-4274-aa45-0dee6e4fc7bf.png)

**Comment by meomancer** [comment]
@ArnaudIGRAC 
This is updated, please check it

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, it seems like you haven't made all the edits, only the "username" field has been moved.

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
Updated, please check it

**Comment by ArnaudIGRAC** [comment]
Thank you Irwan. If you allow me to be picky, I would like to align this part

> Sign up 
> Registering in the GGIS is for users who want to upload data or use advanced functionalities like joining user groups or creating maps.
> Please note that the activation of your account might take a couple of days, and the notification email could end up in your spam box.

with the fields below.

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
Do you mean is above "Sign Up" button?

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
Updated

**Comment by ArnaudIGRAC** [comment]
![image](https://user-images.githubusercontent.com/64771599/196883393-9c350aca-cee9-42f7-a55d-83112a86e54b.png)
P should be capitalized in "position"

**Comment by ArnaudIGRAC** [comment]
For the sake of consitency, can we add a "Type of organization" field to the registration page, like in the data request page?
![image](https://user-images.githubusercontent.com/64771599/197722251-30718bcd-ba83-4c79-9a3d-4b8031e5c06e.png)

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
This is fixed
