### ISSUE TITLE
create subset of GGMN data

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#496]
Dear colleagues, would it be possible to create a layer containing the GGMN data from one country only, the Gambia? Could you do that before Thursday 30/6?

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
Here is the layer of GGMN for Gambia

https://ggis.un-igrac.org/layers/groundwater:groundwater:Groundwater_Well_GGMN_Gambia

**Comment by ArnaudIGRAC** [comment]
Very nice, thank you!
