### ISSUE TITLE
#7 Connect with additional servers

### ISSUE THREAD

**Issue by meomancer** [kartoza/IGRAC-GGIS#497]
The GGIS is currently retrieving monitoring data automatically from the servers of Canada, Norway and Sweden. Many more connections could be made

**Comment by meomancer** [comment]
- [ ] Argentina

URL : http://www.azul.bdh.org.ar/bdh3/leaflet/index.html

1. Wells geojson can be checked in here:
http://www.azul.bdh.org.ar/bdh3/leaflet/datos/estaciones.js
We need to format it as geojson because it is javascript

2. More information:
http://www.azul.bdh.org.ar/bdh3/aguasubterranea_master.php?idpoint=7900&xgap_historial=clear
Replace idpoint with id of geojson
Just get Tipo=Pozo

3. Levels are provided in:
http://www.azul.bdh.org.ar/bdh3/nivel_listado.php?idpoint=7900&xgap_param_idpoint=7900&retorno=aguasubterranea_master.php

**Comment by meomancer** [comment]
- [ ] Australia

URL : http://www.bom.gov.au/water/groundwater/insight/#/bore/locationwater

Can't find the API to retrieve the data.
It is using wms

**Comment by meomancer** [comment]
- [ ] Austria

URL : https://www.ehyd.gv.at/

Can't find the API to retrieve the data.
It is using wms

**Comment by meomancer** [comment]
- [ ] Belgium

URL : https://www.dov.vlaanderen.be/portaal/?module=verkenner&bm=9bba534d-0745-46ef-aa95-c31788c2266a

Can't find the API to retrieve the data.
It is using wms

**Comment by meomancer** [comment]
- [ ] Bolivia

URL : http://ide.sergeomin.gob.bo/wsihibo/

Website can't be opened

**Comment by meomancer** [comment]
- [ ] Brazil

URL : http://rimasweb.cprm.gov.br/layout/visualizar_mapa.php

Can't find the API to retrieve the data.
It is using wms

**Comment by meomancer** [comment]
File progress : https://docs.google.com/spreadsheets/u/1/d/1HwOA6hd7jAP4XKeLQIIEiTt2Nh4FoFsgYHgE9BxSloU/edit?usp=sharing&urp=gmail_link

**Comment by meomancer** [comment]
hi @ArnaudIGRAC @clau1313 

For Argentina:
Could you check the flow of data?

I get the stations from : http://www.azul.bdh.org.ar/bdh3/leaflet/index.html
I filter just "POZO" type
![Selection_053](https://user-images.githubusercontent.com/4530905/187410469-40ec5305-b171-4975-99fa-76c66987ed73.png)

Then click : Ampliar Información

It will show the details
![Selection_054](https://user-images.githubusercontent.com/4530905/187410793-855401a0-c05b-48db-85bc-eef071a793de.png)
Latitud=Latitude
Longitud=Longitude
Cota de boca de pozo [m]=top of well elevation masl
Cota de terreno [m]=ground surface elevation masl
Acuífero=Aquifer name
Propietario/Responsable=Owner

Then for levels, click "Niveles"
![Selection_055](https://user-images.githubusercontent.com/4530905/187411115-9e85fa05-2412-4d76-894a-77a21785c5cd.png)
Fecha=Date
Valor [m]=Level in meter from ground surface elevation

**Comment by meomancer** [comment]
For Norway
Get list in here : https://sildre.nve.no/list
Then the data is on https://sildre.nve.no/station/2.1088.0?2.1088.0.1001_period=fullPeriod&2.1088.0.1001_res=0&2.1088.0.1001_to=2022-03-27&2.1088.0.1001_from=2008-06-14&2.1088.0.1000_period=P1Y&2.1088.0.1000_res=0&2.1088.0.1000_to=2022-09-27&2.1088.0.1000_from=2021-09-27&2.1088.0.1003_period=P1Y&2.1088.0.1003_res=0&2.1088.0.1003_to=2022-09-27&2.1088.0.1003_from=2021-09-27&2.1088.0.17_period=fullPeriod&2.1088.0.17_res=0&2.1088.0.17_to=2022-03-27&2.1088.0.17_from=2008-06-11

**Comment by ArnaudIGRAC** [comment]
@clau1313 Can you please tell Irwan which parameters he must import?

**Comment by meomancer** [comment]
- [ ] All the stations from the US that I tried have data only until 2018. They don’t seem to be updated. Also, are you pulling all data for each well, or only the missing data? The last time these wells were (manually) updated was in 2018.
- [ ] I can’t see any time series data from Ireland, only the stations.
- [ ] For France I only see some wells (for which the records end in 2012), but I can’t see time series for most of them. I guess these are the stations that were already in the GGMN. Are there no updates in these stations from 2012 to now?
- [ ] I can’t find the new data from Norway. How can I see in which wells there is new groundwater quality data? Also, did you have the chance to check why the groundwater level data is not updated? (please see question in my previous email).
- [ ] In New Zealand I can see the groundwater quality data as a table, but not as a graph. For instance, for EC

**Comment by meomancer** [comment]
For groundwater level monitoring data:
- [ ] US https://cida.usgs.gov/ngwmn/index.jsp
- [ ] Austria https://www.ehyd.gv.at/# - Using TSTP or FTP or SFTP
- [ ] France :https://hubeau.eaufrance.fr/page/api-piezometrie
- [ ] Ireland https://epawebapp.epa.ie/hydronet/#Groundwater 
- [ ] Belgium (Flanders): https://www.dov.vlaanderen.be/portaal/?module=verkenner 

For groundwater quality monitoring data:
- [ ] New Zealand https://www.gns.cri.nz/Home/Our-Science/Environment-and-Climate/Groundwater/Research-Programmes/National-Groundwater-Monitoring-Programme-NGMP
- [ ] Norway https://sildre.nve.no/map?lang=en&x=380400&y=7228000&zoom=4

**Comment by meomancer** [comment]
On Prod : 
Add unit = m³/s
add to Abstraction, Spring discharge and Yield

**Comment by meomancer** [comment]
TODO :
- Austria connection
- Improve harvester : 
  Not generate cache when no new data added.
  Just save data when there is measurement saved.
  Skip the well if last run is less then 1 day old, this is handled for harvester that are stopped and need to rerun again, or for multiple harvester that are run twice.

**Comment by meomancer** [comment]
I think we can close this as the remaining one is eHYD : https://github.com/kartoza/IGRAC-GGIS/issues/598
