### ISSUE TITLE
upload layers doesn't work

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#499]
The procedure for uploading layers seems to have changed. After uploading the files I get this message
![image](https://user-images.githubusercontent.com/64771599/189909893-46668c9b-5e27-4369-8a3d-bf56c9958da5.png)
Clicking on "Continue"brings me to another page where I must select a coordinate reference system, although I uploaded the .prg file with the shapefile.
![image](https://user-images.githubusercontent.com/64771599/189910114-381b3403-49fb-4df7-8268-61262ed3b22e.png)
After selecting WGS84, I eventually recieve this error message
![image](https://user-images.githubusercontent.com/64771599/189910253-299edf05-a240-4386-b52a-1eeaaaa1ba06.png)
Can you please help me? I tried several files.

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
Could you provide the files?
Because for projection, the extension of file should be .prj

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, the shapefiles are in this folder
[Burundi.zip](https://github.com/kartoza/IGRAC-GGIS/files/9557878/Burundi.zip)

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
It seems it is missing or has wrong format projection
What i have done is load it on qgis, and export it again to shapefile

Here what i have loaded on staging : https://staging.igrac.kartoza.com/layers/geonode_data:geonode:Burundi_HG0

Here is the files that i have re-exported from qgis
[Burundi.zip](https://github.com/kartoza/IGRAC-GGIS/files/9561882/Burundi.zip)

**Comment by ArnaudIGRAC** [comment]
Thank you Irwan!
