### ISSUE TITLE
Upgrade Geonode

### ISSUE THREAD

**Issue by meomancer** [kartoza/IGRAC-GGIS#504]
We decide to upgrade the goenode to version 3
To enable geostories and fix some bugs

PR https://github.com/kartoza/IGRAC-GGIS/pull/503

TODO:
- [x] Deploy this on Staging
- [x] Test it
- [x] Release it to production

---------------------------
Could you provide notes how to upgrade it @dimasciput ?

**Comment by dimasciput** [comment]
For now it should be normal upgrade process : 
- Build from https://github.com/kartoza/IGRAC-GGIS/pull/503
- Deploy using that image
- Do migration

**Comment by meomancer** [comment]
This has been deployed
