### ISSUE TITLE
Move geostories menu

### ISSUE THREAD

**Issue by timlinux** [kartoza/IGRAC-GGIS#505]
![image](https://user-images.githubusercontent.com/178003/195580894-20bb09b0-05f4-4ebd-9f3a-58bd1445ba77.png)

@ArnaudIGRAC also please indicate where you would like to put the link / button for the featured story.

**Comment by ArnaudIGRAC** [comment]
The only thing I can think about is a button right under the banner, leading the user to the GeoStory. Something like that
![image](https://user-images.githubusercontent.com/64771599/195639382-a0e8dd5a-0609-4094-8d4a-d3cc4f3e5849.png)

But I am open to any other suggestion! Note that this button will be needed only when our GeoStory is ready, so we have a bit of time to think about it

**Comment by meomancer** [comment]
I think this is fixed

**Comment by ArnaudIGRAC** [comment]
We need to remove this button 
![image](https://user-images.githubusercontent.com/64771599/196887628-c254a002-52ce-4d2d-b1ab-ad021e77c8ec.png)
for now. it will be needed only when our Groundwater GeoStory is finalized.

**Comment by meomancer** [comment]
This has been updated @ArnaudIGRAC 
Please check it
