### ISSUE TITLE
Slight change viewers?

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#511]
Dear colleagues, I have the feeling that the map viewers have slightly changed.

1. The url address of the viewers now contains a "#" sign, see e.g. https://ggis.un-igrac.org/maps/1838/view#/
2. The cursor is a hand, I think ti was an arrow before.

**Comment by meomancer** [comment]
Could you check this @dimasciput ?

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
This is fixed by @dimasciput 
It is already deployed on staging, could you check it? https://staging.igrac.kartoza.com/view/ggmn

**Comment by ArnaudIGRAC** [comment]
Just noticed that the cursor is now a cross (should be an arrow)

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
Should be like this?
![Selection_014](https://user-images.githubusercontent.com/4530905/214522190-c832fed5-1e5d-446a-877a-b6a52de45af9.png)

**Comment by ArnaudIGRAC** [comment]
Sorry, it should be a white hand

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
it is updated now

**Comment by ArnaudIGRAC** [comment]
Thank you!
