### ISSUE TITLE
Organisation doesn't appear in filter

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#514]
I am trying to apply a filter to the GGMN layer, but the new organisation "Wells for G3P evaluation" doesn't appear:

![image](https://user-images.githubusercontent.com/36033176/213172879-c4e6101e-cc4e-41a6-9db3-cdbc7c3ddfa4.png)

This happens both in the GGMN viewer and the G3P viewer (I guess because the GGMN layer is the same one for both). Do you know what can be the problem?

**Comment by meomancer** [comment]
This is fixed @clau1313

**Comment by clau1313** [comment]
Thanks!
