### ISSUE TITLE
Download of raster layers with time dimension

### ISSUE THREAD

**Issue by SterckxArnaud** [kartoza/IGRAC-GGIS#518]
Downloading raster layers with time dimension only gives you the data associated with the last time step. Try for instance
https://ggis.un-igrac.org/layers/groundwater:GWSA

**Comment by dimasciput** [comment]
Hi @ArnaudIGRAC so do you want to select the date when downloading the layer? Currently Geoserver does not support downloading all rasters at once, you need to specify the time.
Or you want to download the netcdf file instead?

**Comment by ArnaudIGRAC** [comment]
Hi @dimasciput, where can you specify the timestep when downloading the layer? I don't see that option in GeoNode.
In order to download all timesteps at once, the download of the netcdf file would be fine. How would you implement that? Simply upload the netcdf file in the document section?

**Comment by dimasciput** [comment]
@ArnaudIGRAC 
> Hi @dimasciput, where can you specify the timestep when downloading the layer?

No, we need to add this feature in igrac, might take 3-5 hours.

> In order to download all timesteps at once, the download of the netcdf file would be fine. How would you implement that? Simply upload the netcdf file in the document section?

Yes, and we can add a link to that file in the layer download here : https://ggis.un-igrac.org/en/admin/base/link/add/

**Comment by ArnaudIGRAC** [comment]
Thank you Dimas. No need for that development now, we will consider it for a subsequent contract. Please upload the netcdf file as you suggest

**Comment by dimasciput** [comment]
Hi @ArnaudIGRAC , @meomancer has added the download link to the layers. 
![image](https://user-images.githubusercontent.com/1979569/214789849-830b196f-a845-40c8-9713-8c7536a8a143.png)

**Comment by ArnaudIGRAC** [comment]
Very good!

**Comment by ArnaudIGRAC** [comment]
The download of raster data with time is not working anymore:
https://ggis.un-igrac.org/catalogue/#/dataset/2236

**Comment by NyakudyaA** [comment]
This seems to be working
![Screenshot from 2023-09-26 15-09-32](https://github.com/kartoza/IGRAC-GGIS/assets/2510900/991b5a55-03b6-43f9-b016-79a14e79d23b)

The one in the layer preview is not working
https://ggis.un-igrac.org/catalogue/#/dataset/2236

**Comment by ArnaudIGRAC** [comment]
Any update on this issue?

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
The error is
![Selection_008](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/49ec6b28-ddb7-4703-876f-fa6f965986b9)

It is same with https://github.com/kartoza/IGRAC-GGIS/issues/556#issuecomment-1727181619
So we need to upgrade geoserver for fixing this error

**Comment by ArnaudIGRAC** [comment]
Thank you Irwan. When will the upgrade of GeoServer take place?

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
I will check with @timlinux and @MarinaKartoza 
But from my planning, the task for migrating to new infra is around 1st Nov

**Comment by meomancer** [comment]
Hi @SterckxArnaud
This is fixed with current deployment (geoserver:2.23.0-geo-v2023.09.15)
Could you check it?

**Comment by meomancer** [comment]
Hi @NyakudyaA 
Could you answer @SterckxArnaud question?

Thank you

**Comment by NyakudyaA** [comment]
@meomancer The layer specified in the link is not available anymore, which other raster has time dimension

**Comment by meomancer** [comment]
hi @NyakudyaA 
i think this one : https://ggis.un-igrac.org/catalogue/#/dataset/2236

**Comment by meomancer** [comment]
Hi @Jeremy-Prior @ThiashaV 
Could you help me check this?

**Comment by EliVolsch** [comment]
@robertohuru have you been able to take a look at this ticket?

**Comment by meomancer** [comment]
Download time dimension
https://ggis.un-igrac.org/geoserver/ows?request=GetCoverage&service=WCS&version=2.0.1&coverageId=groundwater:GWSA&Format=application/x-netcdf&subset=http://www.opengis.net/def/axis/OGC/0/time("2020-10-01T00:00:00.000Z","2020-11-01T00:00:00.000Z")

**Comment by meomancer** [comment]
Hi @SterckxArnaud @robertohuru @EliVolsch 
This changes is already released on production
Now we have "NetCDF" option type and we can select date to subset it
It will download the netcdf file

Please check it
![Selection_051](https://github.com/user-attachments/assets/a6c8555a-4467-4756-8dc2-e739e922a47d)
