### ISSUE TITLE
Accidentaly duplicated a map viewer?

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#520]
In the G3P viewer, I wanted to show the GGMN layer displaying only data from the organisation "Well for G3P evaluation", but it seems that I created another map viewer...

1) G3P viewer: https://ggis.un-igrac.org/maps/2241/view#/
2) G3P viewer with the filtered layer: https://ggis.un-igrac.org/maps/2249/edit#/

Can you help me with this? I would like that the first one shows the GGMN layer filtered, and keeps its URL (and that it's not duplicated). Thanks!

**Comment by meomancer** [comment]
Hi @clau1313 
I have deleted : https://ggis.un-igrac.org/maps/2249/edit/

Also i changed the layer to filter on organisation "Well for G3P evaluation" on https://ggis.un-igrac.org/maps/2241/view/

**Comment by clau1313** [comment]
Thanks!
