### ISSUE TITLE
Not show an organisation in GGMN

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#521]
Is it possible to not show the wells belonging to an organisation in GGMN? I would like to not show the wells that belong to "Wells for G3P evaluation"

I know that it is possible to show the layer filtered, which is what I was trying to do in G3P viewer (showing only the wells from "Wells for G3P evlauation").  I would like to have the oppossite in the GGMN (all wells except those from that organisation). I know that I can do it if I apply multiple filters to show the wells from each other organisation, but is there a more straighforward way? 

In general, can organisations belong to only certain viewers? That would be the best way, since in the future we would like to have organisations that show only for example in the Well and Monitoring data viewer: https://ggis.un-igrac.org/view/well-and-monitoring-data#/ and not in the GGMN viewer.

**Comment by meomancer** [comment]
Hi @clau1313 
You can change "any" to "none"
![Selection_003](https://user-images.githubusercontent.com/4530905/214200713-183f9990-3531-474c-8142-e929f974f5dc.png)

> In general, can organisations belong to only certain viewers?
We don't have this permission anymore, so we can't do that now
All of data are public : https://github.com/kartoza/IGRAC-GGIS/issues/487

**Comment by meomancer** [comment]
Hi @clau1313 
Is it working?

**Comment by clau1313** [comment]
Hi @meomancer, it's working, thanks. 

How can I keep it this way? I am afraid that if I click in "save as" I will create a copy of the viewer (as I did a couple of days ago with the G3P viewer...).

![image](https://user-images.githubusercontent.com/36033176/214572076-b6799bfd-d069-495c-a78c-4fb275c56de0.png)

**Comment by meomancer** [comment]
hi @clau1313 what map are you want to update?

**Comment by ArnaudIGRAC** [comment]
dear @meomancer, we will follow up on that issue in a subsequent development phase
