### ISSUE TITLE
Change name of map viewer

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#524]
Hi @ArnaudIGRAC, before I forget, can you change the name of this map viewer https://ggis.un-igrac.org/maps/2241/view#/ to https://ggis.un-igrac.org/G3P or https://ggis.un-igrac.org/maps/G3P or something similar? or can you teach me how to do it?

**Comment by meomancer** [comment]
hi @clau1313 
You can go to https://ggis.un-igrac.org/en/admin/igrac/mapslugmapping/
![Selection_018](https://user-images.githubusercontent.com/4530905/214756895-936bc47f-5979-4724-ba6c-f8e27d2f953a.png)

Find the map name that is the target map, which is "[G3P v1.5 data by ggis-admin](https://ggis.un-igrac.org/en/admin/igrac/mapslugmapping/216/change/)"

Then change it (https://ggis.un-igrac.org/en/admin/igrac/mapslugmapping/216/change/)
Change the slug name to "G3P"
and check the "featured" checkbox

Then it will show on
![Selection_020](https://user-images.githubusercontent.com/4530905/214757349-92133a7d-f79a-4021-82fc-8c4ab9481f82.png)
The map can be checked in here : https://ggis.un-igrac.org/view/G3P

**Comment by ArnaudIGRAC** [comment]
Thank you @meomancer ! @clau1313 , don't forget to add a description of the viewer in the metadata. Currently it is written "GWSA".

**Comment by clau1313** [comment]
Great! Thanks @meomancer.

And yes @ArnaudIGRAC I will add a description to the viewer.
