### ISSUE TITLE
Add shortcut for data download in the menu

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#532]
Dear colleagues, while upgrading to GeoNode 4.1, could you please add a menu item "Download Well and Monitoring Data", directing to this page: https://ggis.un-igrac.org/groundwater/record/download-request

The new menu item should be placed right below "Upload Well and Monitoring Data"
![image](https://user-images.githubusercontent.com/64771599/225551978-8e7309b7-e3a1-4ef9-aeb1-70f847c1eb20.png)

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
Currently it is also in here
![Selection_014](https://user-images.githubusercontent.com/4530905/225561010-2bbb596c-aeed-4a82-bd69-692c6f7eb9b0.png)

Should we remove above and move it to below "Upload Well and Monitoring Data"?

**Comment by meomancer** [comment]
This is done on staging, could you check it @ArnaudIGRAC ?
