### ISSUE TITLE
Batch upload groundwater levels

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#537]
Hello Irwan, I have uploaded a series of new wells. Upload session https://ggis.un-igrac.org/en/admin/gwml2/uploadsession/149/change/

Now I want to upload the water levels associated to these wells, but it fails (https://ggis.un-igrac.org/en/admin/gwml2/uploadsession/150/change/). It says that the Sheet 'General Information' is needed. Can you please assist?

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
Did you upload file using "Monitoring Data" tab?
To upload monitoring data, you need to upload it using that tab
![Selection_016](https://user-images.githubusercontent.com/4530905/226578677-4fff06be-4458-4c1e-8500-70d9de602fc0.png)

**Comment by ArnaudIGRAC** [comment]
Dear Irwan, I tried again to upload those 5 data, but it doesn't work. I need your assistance. Here is the file with the 5 data. 
[Israel_202303_gwl - skipped data.zip](https://github.com/kartoza/IGRAC-GGIS/files/11038907/Israel_202303_gwl.-.skipped.data.zip)

**Comment by ArnaudIGRAC** [comment]
Thank you Irwan, indeed I can see the data in the database. But I wonder why I was told those 5 data were skipped when I first uploaded them...
