### ISSUE TITLE
download data Gambia - empty files

### ISSUE THREAD

**Issue by SterckxArnaud** [kartoza/IGRAC-GGIS#540]
I downloaded the GGMN data from the Gambia. The monitoring file contains 47 files, 11 of which are not in the GGMN (there are only 36 wells in the Gambia). These additional files are empty and have a different naming (see below). Can you please address this issue?

![image](https://user-images.githubusercontent.com/64771599/228500908-57efe19e-f045-49b2-928f-f27e829ec745.png)

**Comment by ArnaudIGRAC** [comment]
I have the same issue with Brazil, please address it asap because I need these data files urgently!

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
This is fixed, could you check it?

**Comment by ArnaudIGRAC** [comment]
It is working, thank you
