### ISSUE TITLE
GGMN charts - time axis is not linear 

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#541]
The time axis (x-axis) is not linear on the charts. See this well for example (https://ggis.un-igrac.org/groundwater/record/2426), the space between Jul 2015 and Jan 2016 is larger than between Jan 2016 and Jan 2022.
![image](https://user-images.githubusercontent.com/64771599/228503769-8de63154-a369-4eff-9e89-a033b5342e21.png)

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
This is fixed, but it is still just on staging. So production will be fixed on geonode 4 release

Please check here: https://staging.igrac.kartoza.com/groundwater/record/29162/#level-measurement

Before
![Selection_001](https://user-images.githubusercontent.com/4530905/231685245-681f56d2-ebd8-450e-b964-5572d2ce8a6c.png)

After
![Selection_002](https://user-images.githubusercontent.com/4530905/231685277-751116f2-3e05-40ca-b900-dfbd80f375dd.png)

**Comment by ArnaudIGRAC** [comment]
Thank you Irwan!
