### ISSUE TITLE
Request time out on returning batch upload detail

### ISSUE THREAD

**Issue by meomancer** [kartoza/IGRAC-GGIS#546]
# Problem
Example: https://ggis.un-igrac.org/groundwater/upload-session/161/detail

# Solution
- Paginate request

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, any update on this issue?

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
I haven't looked to this ticket
I will address it on the next session

**Comment by meomancer** [comment]
This is fixed
Report is now on excel file, so we can download and see the error in there
