### ISSUE TITLE
slug maps not working in new GGIS

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#552]
I noticed that the slug maps do not correspond with the setting in admin
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/5813bf6f-ec1d-4c7f-ac91-822d681f760f)
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/62cae1a2-0180-47af-b1f5-20ea236b3422)

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
This is fixed and released, please check it
