### ISSUE TITLE
invalid map layer extension

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#555]
This layer does not display properly, it has apparently an extension issue. I checked the data coordinates and everything seems in good order though...
https://ggis.un-igrac.org/catalogue/#/dataset/1810
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/44af601c-761a-4b22-b278-1b6a5cc2d881)

I must share this layer with some colleagues, can you please look at it asap?

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
I have fixed the bbox

![Selection_012](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/ce08fa01-6a57-4553-8712-4fa85d6ed154)

I fixed it on geoserver
It seems that now, should be around -180 -90, 90 180
And above layer bbox was more than that

**Comment by ArnaudIGRAC** [comment]
thanks Irwan, but how can I fix the extent of the layer on the screen? It is now a small boz in the middle of the screen, I would rather extend it like here
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/e3917c15-82c0-484c-9d14-120f33b37ff9)

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
I re-updated it

Currently we need to update the bbox on geoserver
I will check why when we save layer, the extent is not saved

**Comment by ArnaudIGRAC** [comment]
Very good, thank you. I keep this thread open until the wider issue is solved

**Comment by ArnaudIGRAC** [comment]
I noticed the same issue with that layer
https://ggis.un-igrac.org/catalogue/#/dataset/293

**Comment by meomancer** [comment]
Fixed @ArnaudIGRAC

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
This is fixed, please try it
The layers has empty bbox, now i put every layes to be -180 -90, 180 90 if it does not have bbox

**Comment by ArnaudIGRAC** [comment]
I have this issue with the following layer 
https://ggis.un-igrac.org/catalogue/#/dataset/426
I edit the bbox in GeoServer but it does not synchronize with GeoNode
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/8e5cb5fa-4255-423d-bb6e-3e693ef99a6b)
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/f24f17be-bc81-458b-ba49-7c07ddecd548)

**Comment by NyakudyaA** [comment]
I think by default if you make changes to GeoServer configuration GeoNode does not know about them until you issue an update command. This can be done through the https://ggis.un-igrac.org/en-us/admin/management_commands_http/managementcommandjob/add/

```
updatelayers -f name_of_geoserver_layer
```
as positional arguments

https://docs.geonode.org/en/master/admin/mgmt_commands/index.html#async-execution-over-http

**Comment by ArnaudIGRAC** [comment]
Thanks Admire, shall I use the _**updatelayers**_ command? or another command?

**Comment by NyakudyaA** [comment]
Update layers and make sure you pass the argument `-f name_of_geoserver_layer` otherwise all the layers will be updated

**Comment by ArnaudIGRAC** [comment]
It doesn't seem to be working? Maybe I didn't pass the arguments correctly?
https://ggis.un-igrac.org/en-us/admin/management_commands_http/managementcommandjob/1/change/

**Comment by NyakudyaA** [comment]
https://ggis.un-igrac.org/en-us/admin/management_commands_http/managementcommandjob/2/change/
