### ISSUE TITLE
Implement IstSOS

### ISSUE THREAD

**Issue by meomancer** [kartoza/IGRAC-GGIS#560]
We decide to try to use SOS to serve the data.

TODO:
- [x] Add istsos to the infrastructure
- [x] Add registering form get the api key of sos

**Comment by meomancer** [comment]
- [ ] Add "This data was made available by Organisation XYZ under the CC-by-SA license." in GetFeatureInfo and GetMeasurements
- [ ] Add cache, especially for GetCapabilities

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, can you please explain the arguments in the GetObservation request?
urn:ogc:def:parameter:x-igrac:1.0:Level%20Measurement:Water%20level%20elevation%20a.m.s.l.
I think it requires a bit of explanation for our clients to use the SOS

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
That is the parameter id that we want to fetch
The list is on the DescribeSensor

https://ggis.un-igrac.org/istsos?service=SOS&version=1.0.0&request=DescribeSensor&procedure=bc.mon.59381&outputFormat=text/xml;subtype=%22sensorML/1.0.1%22&api-key=724df1163f0a99f81af89f3b446d76281d07d3ac

![Selection_001](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/0597ff0e-5360-45da-878b-849f5c7ab12b)

Example:
If we want to fetch measurement "Quality Measurement" -> "T"
We can request "urn:ogc:def:parameter:x-igrac:1.0:Quality Measurement:T"

**Comment by SterckxArnaud** [comment]
I will close this ticket for now. We can always reopen it in case the colleagues from WMO raise other issues.
