### ISSUE TITLE
Assign organisations to specific viewers

### ISSUE THREAD

**Issue by meomancer** [kartoza/IGRAC-GGIS#561]
# Problem
We need a layer or a map to just show specific data for specific organisation
Example:
- There is view "View A" and it should has data that belong to "Organisation A, Organisation B, Organisation C"
- When user open View A, it should show well data that just belong to Organisation A,B,C 
(not pre-filter on side bar on map, but directly on data)

Solution:
- Please check if we can duplicate layer and apply group on there
- If not possible, we can apply group on view

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
This is deployed on Staging
Could you try it?
Based on conversation in : https://github.com/kartoza/IGRAC-GGIS/pull/564#issuecomment-1576582217

**Comment by ArnaudIGRAC** [comment]
I can create the layer but the attribute table is not the one we have developed for well and monitoring data. We miss the measurements charts, among others. 

In Admin, I would rename _groundwater layers_ into _Well and monitoring data layers_

**Comment by meomancer** [comment]
ok @ArnaudIGRAC 
I will fix it

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
Fixed, now the feature info is same with the original Well and Monitoring Data Layer
