### ISSUE TITLE
Add license column on the download data

### ISSUE THREAD

**Issue by meomancer** [kartoza/IGRAC-GGIS#563]
Put new column on excel data for download

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
Is this good?

[wells.xlsx](https://github.com/kartoza/IGRAC-GGIS/files/11571384/wells.xlsx)

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, when will you implement this development?

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
The update is deployed to staging
Please check it
https://staging.igrac.kartoza.com/groundwater/batch-upload

For monitoring data, the license will be hidden

And also, please download it, the license columns are on the management sheet

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, please use the download template that we agreed about

> Hi @ArnaudIGRAC Is this good?
> 
> [wells.xlsx](https://github.com/kartoza/IGRAC-GGIS/files/11571384/wells.xlsx)

Could you then please move it to production?

**Comment by meomancer** [comment]
ah, yes, let me check @ArnaudIGRAC for the template

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
Staging is already using correct template
The license is in general sheet

For releasing to production, it will also release the other features/bug fixing too until now (except sos)

**Comment by ArnaudIGRAC** [comment]
Thank you Irwan. When do you plan to release it to production? It is relatively urgent that the download integrates the license information.

**Comment by meomancer** [comment]
i will release it tomorrow @ArnaudIGRAC

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
It is released, but currently i'm running the re-cache for download data with new templates, i will ping if it is done

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
The cache has been recreated
Could you check it on download data?
