### ISSUE TITLE
Editing permissions of geostory does not work

### ISSUE THREAD

**Issue by seabilwe** [kartoza/IGRAC-GGIS#572]
Issue reported in support portal: https://kartoza.com/app/issue/ISS-2023-00014

We are unable to edit the permissions of the Geostory [https://ggis.un-igrac.org/catalogue/#/geostory/2311.](https://ggis.un-igrac.org/catalogue#/geostory/2311.) It keeps buffering.
![image](https://github.com/kartoza/IGRAC-GGIS/assets/56301949/213df864-dc4d-4d69-845d-d6ec4e3368a2)

I have already reported several issues with the new GGIS. We are currently unable to work with the GGIS because of these issues. Please attend them ASAP.

Priority: High

**Comment by NyakudyaA** [comment]
@meomancer Can you update the uwsgi conf based on the other ticket I commented on

**Comment by meomancer** [comment]
hi @NyakudyaA 
I have update and deployed uwsgi : https://github.com/kartoza/IGRAC-GGIS/blob/develop/deployment/docker/uwsgi.conf

**Comment by NyakudyaA** [comment]
Thanks, I will check the issues again

**Comment by ArnaudIGRAC** [comment]
Dear colleagues, any update on that issue?

**Comment by MarinaKartoza** [comment]
My apologies for the delay. We will assign someone immediately to have another look at this. You will receive a response soon.

**Comment by NyakudyaA** [comment]
@ArnaudIGRAC Does the issue happen when you select users to assign to groups or at saving.
![image](https://github.com/kartoza/IGRAC-GGIS/assets/2510900/62be8cd8-e05c-40b9-b1fb-2a01ca96be23)

**Comment by meomancer** [comment]
hi @ArnaudIGRAC and @NyakudyaA 
I have updated the uwsgi config to production, maybe it affects this ticket also
