### ISSUE TITLE
Staff status - no access to Admin

### ISSUE THREAD

**Issue by seabilwe** [kartoza/IGRAC-GGIS#573]
Issue reported in the support portal: https://kartoza.com/app/issue/ISS-2023-00015

I have registered a new user (ID = 2093) with a staff status, however the user has no access to Admin. Could you please check?

![image](https://github.com/kartoza/IGRAC-GGIS/assets/56301949/e76af319-4b18-4f67-b829-e3699c2c2040)

Priority: High

**Comment by NyakudyaA** [comment]
The issue here is the admin panel does not show in the UI, If you navigate to https://ggis.un-igrac.org/en-us/admin/ you can still access a single aspect of the admin panel
![image](https://github.com/kartoza/IGRAC-GGIS/assets/2510900/7203e61e-e053-4d1f-8626-23db64b73c18)

**Comment by meomancer** [comment]
Yes, it can access admin but no link on UI
i will fix it
