### ISSUE TITLE
Download file issue - American Samoa

### ISSUE THREAD

**Issue by seabilwe** [kartoza/IGRAC-GGIS#575]
Issue reported in the support portal: https://kartoza.com/app/issue/ISS-2023-00016
 
Download data are sorted per country. Each country is identified by the iso code, except American Samoa which is there under ASM... but also as American Samoa... The latter contains demo/test data. I suggest that this file and test data in general are removed from the download.

![image](https://github.com/kartoza/IGRAC-GGIS/assets/56301949/671d2784-6874-4546-92ed-407438bb8056)

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
This is fixed, i have removed the test from download
