### ISSUE TITLE
add attribute columns on data availability

### ISSUE THREAD

**Issue by SterckxArnaud** [kartoza/IGRAC-GGIS#576]
We would like to add in the attribute table of well and monitoring data (as well as subsets like the GGMN dataset) 3 columns indicating whether a borehole has groundwater level data, groundwater quality data, and groundwater abstraction data. These attributes would be automatically populated with the number of data stored in the database. For example, if a borehole has 10 water level measurements, then the attribute "Groundwater level data" would be 10.

![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/e37e3a58-8596-4672-b687-db2b98e19561)

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, could you please estimate how much time is needed for that?

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
It should be 5-8 hours (i have sized it)

**Comment by meomancer** [comment]
Hi @SterckxArnaud 
This is implemented, could you check it?
