### ISSUE TITLE
GW quality monitoring not available anymore

### ISSUE THREAD

**Issue by seabilwe** [kartoza/IGRAC-GGIS#577]
In the well and monitoring data section, users can see which variables have been monitored and which one of those they want to plot on the chart. This is not possible anymore. See for example the monitoring stations in New-Zealand, they contain exclusively quality data.
![image](https://github.com/kartoza/IGRAC-GGIS/assets/56301949/942acf9e-675e-43a8-9499-fd610e9f3aef)

Ticket reported here: https://kartoza.com/app/issue/ISS-2023-00023

Priority of the issue: **High**

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
Fixed
