### ISSUE TITLE
Metadata not available

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#580]
Two issues with the metadata of maps have been reported to us.

1. Metadata cannot be fetched when in slug maps
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/b733c2d6-6f8c-4881-9797-e4fa3c95a96c)
2. Metadata pages are empty, see for instance https://ggis.un-igrac.org/catalogue/#/map/1231/metadata_detail

**Comment by ArnaudIGRAC** [comment]
Any update?

**Comment by meomancer** [comment]
This is fixed and deployed on production @ArnaudIGRAC

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, metadata pages are still empty (the second issue I reported above). See for instance
https://ggis.un-igrac.org/catalogue/#/map/2248/metadata_detail

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
I'm sorry, but where did you get above link? That link is not working

It should be : https://ggis.un-igrac.org/maps/2248/metadata_detail

And on the map
https://ggis.un-igrac.org/catalogue/#/map/2248
![Selection_020](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/0e73c6c7-c4d5-4ac1-8422-d7b6dfd4d22e)

**Comment by ArnaudIGRAC** [comment]
In the metadata box, there is hyperlink for detailed metadata, which leads to empty pages.

**Comment by meomancer** [comment]
I found it
![Selection_024](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/b068f78c-c229-4edd-984c-83377546b65d)

This is bug from geonode. I have checked on other geonode instance, they are same.
Should we raise the ticket or fix by ourself?

cc @timlinux

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
I have fixed link on the metadata box
