### ISSUE TITLE
can't save map layer extent

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#581]
I changed the extent (scale) of this layer (https://ggis.un-igrac.org/catalogue/#/dataset/425), then save it. However, when I reopen it again the extent is back to original.

**Comment by MarinaKartoza** [comment]
Good afternoon @ArnaudIGRAC. I have scheduled @meomancer (Irwan) to attend to this on Friday, 18 August. I trust that you will be okay with that?

**Comment by ArnaudIGRAC** [comment]
Any update on this issue?

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
After i checked, we can't save extent on the Dataset
We can just save extent on map, because Dataset is coming from geoserver
The extent is automatically created by geoserver, but we can change the extent on geoserver and run command to update it on geonode

**Comment by ArnaudIGRAC** [comment]
OK, thank you
