### ISSUE TITLE
TWAP documents not available!

### ISSUE THREAD

**Issue by seabilwe** [kartoza/IGRAC-GGIS#585]
Ticket added through the support portal: https://kartoza.com/app/issue/ISS-2023-00030

The documents from the TWAP project are not available: [https://ggis.un-igrac.org/catalogue/#/search/?f=document&q=twap](https://ggis.un-igrac.org/catalogue#/search/?f=document&q=twap)

Ticket priority: High

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
I'm really sorry, but what is this documents from TWAP project?
I don't have any knowledge about this document

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, they are pdf files belonging to the group TWAP (over 200 in total). The issue is that these files can not be accessed or downloaded anymore.

**Comment by meomancer** [comment]
Ah, i understand @ArnaudIGRAC 
The file is like this https://ggis.un-igrac.org/documents/1773/link
But we can't see it in https://ggis.un-igrac.org/catalogue/#/document/1773, and download it also

**Comment by ArnaudIGRAC** [comment]
Yes, that is the problem.

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
Are those document are from remote service?
Because it has url from external url

Example: https://ggis.un-igrac.org/en-us/admin/documents/document/1773/change/?_changelist_filters=q%3Dtwap
![Selection_023](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/0291d676-a0f5-43ae-a955-2c5df9313107)

Url : https://services.geodan.nl/public/document/AGRC0001XXXX/api/data/AGRC0001XXXX/mim/AF53_20170515.pdf_dbjrqmmyq

If it was uploaded manually, i could remove that url (maybe there was bug when migrating to geonode version 4)

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, all documents were uploaded manually by Seabilwe. You can remove the url

**Comment by ArnaudIGRAC** [comment]
I noticed that the documents can be accessed with this url 
https://ggis.un-igrac.org/documents/1690/download

**Comment by meomancer** [comment]
Great, thank you
I will fix those files

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
This is fixed, could you check it?

Thank you

**Comment by ArnaudIGRAC** [comment]
It doesn't work

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
Which one is not working?
I test it using https://ggis.un-igrac.org/catalogue/#/document/1773

![Selection_019](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/ea2a2545-9c19-48ef-82a1-c06c50a8faa1)

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
Could you provide 1 of example document link that does not working?
I can access document from : [https://ggis.un-igrac.org/catalogue/#/search/?f=document&q=twap](https://ggis.un-igrac.org/catalogue#/search/?f=document&q=twap)

![Selection_021](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/b9602774-1029-4f5b-8f28-3698e7db8c97)
![Selection_022](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/fb90a395-2a9a-4f4d-aa72-a9b3377b6e9c)

**Comment by ArnaudIGRAC** [comment]
How weird, this document doesn't work here 
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/31b6f8dd-0d13-45a0-ba06-96c6710cc25c)

**Comment by ArnaudIGRAC** [comment]
I noticed that when I click on a document I get this url https://ggis.un-igrac.org/catalogue/#/?f=document&page=5&d=1773%3Bdocument, which is not the same as you have

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
- [ ] It seems there is bug on the clicking process

- [ ] And also, yes, it also does not working on my browser for this screenshot
https://github.com/kartoza/IGRAC-GGIS/issues/585#issuecomment-1706730131

I will check it on Friday

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC, this is fixed, could you check it?
