### ISSUE TITLE
Sorting "less recent" does not work

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#587]
"Less recent" sorting of datasets does not work. The url switches from 
https://ggis.un-igrac.org/catalogue/#/?f=dataset&sort=-date to https://ggis.un-igrac.org/catalogue/#/?f=dataset&sort=date, but the datasets are not reorganized in chronological order as they should.

**Comment by NyakudyaA** [comment]
Maybe this is related to https://github.com/GeoNode/geonode-mapstore-client/issues/1551 which was fixed last week

**Comment by meomancer** [comment]
Thank you @NyakudyaA for pointing out
Confirmed that changes fix it

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
This is fixed and released
