### ISSUE TITLE
Uploading compressed files does not work

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#588]
7z and zip files are not uploading. The green progress bar goes to 100% but then we receive an error message saying that the file has not been uploaded.

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
It is working fine from my side
Could you share the file?

**Comment by ArnaudIGRAC** [comment]
[Methodology Report.zip](https://github.com/kartoza/IGRAC-GGIS/files/12682752/Methodology.Report.zip)

**Comment by meomancer** [comment]
Thank you @ArnaudIGRAC 
I will check it

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, could you please attend this issue right ahead? We urgently need to upload this file

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
I can't reproduce it on my local machine
It seems that we can just be able to upload file for max 2.5MB

I need to ask @NyakudyaA and our devops team

**Comment by ArnaudIGRAC** [comment]
Thank you Irwan. I tried to upload a very light zip file and it works fine indeed. However the GeoNode documentation says files up to 100 MB can be uploaded.

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
I found the bug and it is fixed, one of our settings is not correct
Could you try it? It should be up to 100MB now

Thank you
