### ISSUE TITLE
Data cannot be deleted in GGMN

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#591]
Hello @meomancer, I am trying to delete the wells and associated data from the organisation "Czech Hydrometeorological Institute (Czech Republic)", but it doesn't work. Me and my colleague @eliegergesgerges tried several times yesterday and today.

Can you please check what is the problem, and also, delete the wells from this organisation? Thanks.

**Comment by meomancer** [comment]
hi @clau1313 
Could you try delete the data here?
https://ggis.un-igrac.org/en-us/admin/gwml2/well/?organisation__id__exact=13

And please do one by one, because the data is quite big when delete in batch

**Comment by clau1313** [comment]
Hi @meomancer, yes it works one by one, and I could do it in this case, but what if I have 300 wells? We shouldn't be deleting them manually. Is there not a way of at least delete them in groups?

Perhaps @ArnaudIGRAC wants to join the conversation.

**Comment by meomancer** [comment]
Yes, we can delete it in batch
But in the django admin, it will show the related data of the wells before we delete it, it is for confirmation
![Selection_021](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/dd434315-507e-4675-a27f-1410a26fbaf2)

If the measurements is big, it will eventually show 502 connection time out because django trying to show all of data that related to it

My suggestions is we need to have our own page for listing wells, and can delete it without showing related data.
So, the process will be faster.

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, I tested it also on my side. It takes a bit of time for Django to produce the list of data, indeed, but it eventually does it alright. The issue is when you click on "Yes, I am sure". This is when the systems stops answering.

**Comment by meomancer** [comment]
Yes @ArnaudIGRAC 
When we do "Yes, I'm sure", basically django is doing deleting, but it needs time to delete it (it depend on the number of measurements)

If we create new specific page for wells, we can control it, doing deleting on background (showing the progress of delete)

**Comment by ArnaudIGRAC** [comment]
Ok, it sounds like a plan! When can it be done?

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
I will ask time for addressing this

**Comment by clau1313** [comment]
Hi @meomancer, in the meantime is there any solution for this? We need to update the data for Czech Republic. Please let me know. Thanks.

**Comment by meomancer** [comment]
Hi @clau1313 
Could you describe what is the goal?
Maybe i could help by delete it on database directly

**Comment by clau1313** [comment]
hi @meomancer I simply want to delete all data from a organisation (Czech Hydrometeorological Institute (Czech Republic)) without having to do it one by one. Now I am trying to do it one by one because we are wasting a lot of time waiting for a solution. But even this is not working now, I get a "504 bad gateway" message.

In the future we will need to do this again for other organisations with a lot more data, and we need to have a plan (because our computers keeps crashing when we try to delete data all at once).

Again, I just want to be able to delete data in the database, that's all.

**Comment by meomancer** [comment]
Hi @clau1313 
I forgot we have feature "organisation is active or not"
https://ggis.un-igrac.org/en-us/admin/gwml2/organisation/

![Selection_034](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/00cfc8ea-cd3d-4116-985a-9ae8ccf6e0f9)

I don't delete the data on that organisation, instead i rename the organisation and make it "inactive"
It will not show on the ggmn or well and measurement layer

After that, we can create new organisation (with same name before)
And use that new organisation to upload new one

![Selection_035](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/09e56671-f7a5-468c-8c1f-736ebc6127d8)
