### ISSUE TITLE
Adding colleague to the group

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#593]
Hi @meomancer, @eliegergesgerges (Elie) is our new colleague and I would like to include him in this group, so that he can also send requests and assign people. Can you please help me with this or is this something I can do myself? Thanks.

**Comment by meomancer** [comment]
To adding user to a group
You can go here: https://ggis.un-igrac.org/groups/?limit=5&offset=0
![Selection_022](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/cdebb363-0608-4ee7-90bd-70545fc64ed3)

Select a group
Then "manage group member"
![Selection_023](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/bf4d78eb-6890-4460-ac68-c2045cc8f446)

Find the user in here, click the user (until it's blue)
And click "Add Group Members"
![Selection_024](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/10a045a0-3dd6-47c0-9303-e32b12675b03)

I haven't added it yet, just show how to do it

**Comment by Eliegergesgerges** [comment]
Hello Irwan, 

thank you for your help. I have added myself to the IGRAC group. However, I can't add assign in the issues

**Comment by meomancer** [comment]
Hi @Eliegergesgerges 
You mean that assign the issue in github?

**Comment by Eliegergesgerges** [comment]
Yes

**Comment by meomancer** [comment]
I have invited you

Have you received it?
https://github.com/kartoza/IGRAC-GGIS/invitations

**Comment by Eliegergesgerges** [comment]
Yes, Thank you! now it works
