### ISSUE TITLE
Migrating to new infrastructure and using kubernetes

### ISSUE THREAD

**Issue by meomancer** [kartoza/IGRAC-GGIS#594]
This ticket is for our notes for any technical issue when migrating it to new server

1. We need to migrate it to kubernetes
2. Deploy it to new server without data
3. Upgrade geoserver to kartoza/geoserver:2.23.0-geo, the issue here is we use spcgeonode approach, we need to make sure it is migrating well
4. Migrate geonode database
5. Migrate geoserver database

Please add anything here @tharanathkartoza @NyakudyaA

**Comment by NyakudyaA** [comment]
@meomancer What is in the `spcgeoserver` that is needed in the newer image

**Comment by meomancer** [comment]
Todo irwan:
- [ ] https://github.com/kartoza/IGRAC-GGIS/issues/710
- [ ] https://github.com/kartoza/IGRAC-GGIS/issues/711

**Comment by lgkgh** [comment]
IGRAC GGIS has been migrated to a dedicated cluster on DO.
