### ISSUE TITLE
Countries with automatic connection

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#595]
Hello @meomancer, I am doing an inventory and I just wanted to confirm with you that the following countries have an automatic connection with the GGMN:

- Canada
- France
- Ireland
- New Zealand
- Norway
- Sweden
- United States
- Austria and Belgium no, right? or yes?

Are there other countries missing?
Thanks!

**Comment by meomancer** [comment]
Hi @clau1313 
We can check it in here
https://ggis.un-igrac.org/en-us/admin/gwml2/harvester/

![Selection_004](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/55b65015-d483-46fb-8953-e903c1107b77)

**Comment by clau1313** [comment]
Great! Thank you

**Comment by clau1313** [comment]
@meomancer what does it mean a red cross under "is run"?

**Comment by meomancer** [comment]
`is run` menaing the harvester is running
if it is red cross, basically it is already finished (stop), it is waiting for next schedule

**Comment by clau1313** [comment]
thanks!
