### ISSUE TITLE
Seing data from different organisations in GGMN and Well and Monitoring Data

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#596]
Hello @meomancer, I would like to know if it is possible to see data from a certain organisation only in Well and Monitoring Data, and not in the GGMN. A concrete example: I would like to see the time series from the organisation "Wells for G3P evaluation" only in well and Monitoring Data and not in GGMN, by default for all users. How can arrange that?

**Comment by meomancer** [comment]
Hi @clau1313 
It was issued by @ArnaudIGRAC before
https://github.com/kartoza/IGRAC-GGIS/issues/561

You need to create new layer for that
Go to here : https://ggis.un-igrac.org/en-us/admin/igrac/groundwaterlayer/
Create new one, select 1 or more organisations
And create the layer name

![Selection_005](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/3018bf03-ceda-4ac6-b7a7-42d07546277d)

**Comment by clau1313** [comment]
Ah ok thanks! Does this mean that I can also remove organisations shown in the GGMN?

**Comment by meomancer** [comment]
yes @clau1313 you can just select the necessary organisation, and it will filter the data just for that organisation

**Comment by clau1313** [comment]
Hi @meomancer, thanks. But I am not sure if this is enough to achieve what I need.

The solution you propose is that I create a new layer with my seleccion, but this layer do not replace the original layer shown in the GGMN portal (or how can I do that?). In summary:

- in the GGMN portal (https://ggis.un-igrac.org/view/ggmn/) I want to see one single layer that shows data from only a selection of organisations by default.
- in Well and monitoring data (https://ggis.un-igrac.org/view/well-and-monitoring-data/) I want to see all our monitoring data.

If I understand correctly, what we need to do is:
- to replace the current GGMN layer (https://ggis.un-igrac.org/catalogue/#/dataset/1837) by a layer that includes only the selection (how do I do that?).

Also, these two layers are connected, right? If we change the GGMN layer, would this affect the well and monitoring layer?
https://ggis.un-igrac.org/catalogue/#/dataset/55
https://ggis.un-igrac.org/catalogue/#/dataset/1837

**Comment by meomancer** [comment]
Hi @clau1313 
> in the GGMN portal (https://ggis.un-igrac.org/view/ggmn/) I want to see one single layer that shows data from only a selection of organisations by default.

by default in here you mean that it should just show data by selected organisations? and it is fixed right? 
What i mean it can't select any other organisations, just fix by the selected organisations?

> Also, these two layers are connected, right? If we change the GGMN layer, would this affect the well and monitoring layer?
https://ggis.un-igrac.org/catalogue/#/dataset/55
https://ggis.un-igrac.org/catalogue/#/dataset/1837

It does not connected, but we should not delete or edit it
We can just duplicate layer from them 

My suggestion, if we just care for the portal:
The portal https://ggis.un-igrac.org/view/ggmn/ is based on the map.
The map is here: https://ggis.un-igrac.org/catalogue/#/map/1838

We can create new layer using this steps : https://github.com/kartoza/IGRAC-GGIS/issues/596#issuecomment-1757680617
After that on the map, we can remove the original ggmn layer and add the new layer
Or maybe we can just let the original ggmn, but turned off
And the new GGMN (duplicated with selected organisation) is added and turned on.

**Comment by clau1313** [comment]
Hi @meomancer, thanks! I agree with your suggestion.

I created a new layer called "Global Groundwater Monitoring Network (GGMN)". Then please remove the original ggmn layer and replace it with this new one. Also, just to confirm, it is possible to modify this layer in the future, right?

**Comment by clau1313** [comment]
Hi @meomancer, is there any update? Thanks

**Comment by clau1313** [comment]
Hi @meomancer, any update? Thank you.

**Comment by meomancer** [comment]
Hi @clau1313 
I have updated it, could you check it?
https://ggis.un-igrac.org/view/ggmn/

> Also, just to confirm, it is possible to modify this layer in the future, right?

Yes, we can do that, but unfortunately, for now, it is just through geoserver.

**Comment by clau1313** [comment]
Hi @meomancer, thanks! I checked it, and I see the new layer in the GGMN.
