### ISSUE TITLE
Automatic connection with Austrian service (eHYD)

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#598]
Hi @meomancer, from this link you provided: https://ggis.un-igrac.org/en-us/admin/gwml2/harvester/ I understand that we have an automatic connection with eHYD. However, the 462 wells are empty (no timeseries found). Why?

**Comment by meomancer** [comment]
Hi @clau1313 
That harvester is using file that pushed by ehyd team.

They are still have problem to connect to our server and push their files to there.
There is already email thread discussing about this
I have forwarded to you

**Comment by meomancer** [comment]
Blocked because eHYD still can't push their file to our sftp server

**Comment by meomancer** [comment]
Blocked : Waiting link for older data from eHYD

**Comment by meomancer** [comment]
Unblocked : Harvester is running now

**Comment by meomancer** [comment]
@SterckxArnaud @clau1313 
The harvester is done
Older data has been fetched
