### ISSUE TITLE
group not available

### ISSUE THREAD

**Issue by SterckxArnaud** [kartoza/IGRAC-GGIS#601]
I can't open the page of the group **DEEPWATER - Central Europe** Could you please have a look?
https://ggis.un-igrac.org/groups/group/deepwater-central-europe/

![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/2307a5b2-0f72-4587-81b2-be9394c1d39b)

**Comment by meomancer** [comment]
This is fixed
https://ggis.un-igrac.org/
