### ISSUE TITLE
Missing "export layer data" and "create widget" functionalities in some viewers

### ISSUE THREAD

**Issue by SterckxArnaud** [kartoza/IGRAC-GGIS#608]
Why are "export layer data" and "create widget" functionalities absent from some viewers?

Example of viewer with these functionalities: https://ggis.un-igrac.org/view/tba/
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/f3597371-fa4b-48f0-814c-a8cdc9b691f8)

Example of viewer where these functionalities are missing: https://ggis.un-igrac.org/view/marportal/
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/c7b45d16-1b11-4086-b847-d61527182d12)

**Comment by meomancer** [comment]
Could you check this @NyakudyaA ?

**Comment by meomancer** [comment]
Found, this is bug when we have multiple layer with same dataset (different styles), the permission will be assign to the first layer for the dataset.

I think because it is a changes from geonode 4, but i could create fix for this.

**Comment by SterckxArnaud** [comment]
Thank you Irwan. Is it something that can be fixed in GeoNode itself, or will it require some tailor-made development?

**Comment by meomancer** [comment]
Hi @SterckxArnaud 
I'm not sure, but i will create ticket on GeoNode
Meanwhile i will update it on our igrac

**Comment by meomancer** [comment]
Hi @SterckxArnaud 
This is fixed and deployed
