### ISSUE TITLE
Can't Add Map Layer to G3P Viewer 

### ISSUE THREAD

**Issue by Elie114** [kartoza/IGRAC-GGIS#609]
Hello, 

I am trying to add a map layer called "G3P Aquifers set 1v1" to the viewer "G3P v1.5". The map layer is added but when I try to save it, there is a pop-up indicating "Network error cannot save the current map" 

Please can you assist me with this task? 

Regards,
Elie

**Comment by meomancer** [comment]
Hi @NyakudyaA 
It is error from geoserver

Could you help me check it?
https://ggis.un-igrac.org/geoserver/rest/layers/geonode:g3p_aquifers_set1_updated_v1.xml

**Comment by NyakudyaA** [comment]
Can you try again, this should be fixed

**Comment by meomancer** [comment]
Thank you @NyakudyaA 
This is fixed now

Could you check it @Elie114 ?
I have tried adding the layer to map, and it is working fine
https://ggis.un-igrac.org/catalogue/#/map/2241

**Comment by Elie114** [comment]
Yes, guys! it works. 

Thank you 👍
