### ISSUE TITLE
Adding new layer via WMS to GGIS viewer

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#612]
Hi @meomancer, I would like to add the layer called "Global Fluoride (2020)" from here: https://www.gapmaps.org/Home/Public# in our viewer Global Groundwater Quality: https://ggis.un-igrac.org/view/groundwater-quality/. We are already retrieving two layers from this service:
 - Global Arsenic (2020)
 - Global Fluoride (2008)
 
Can you please help us? What would you need to make it happen? Thanks!

**Comment by meomancer** [comment]
Hi @clau1313 
We can pull layer through here : https://ggis.un-igrac.org/services/2208/
And do "Import Service Resources"

But the website is slow, returns request time out.
https://www.gapmaps.org/geoserver/wms?service=wms&version=1.1.1&request=GetCapabilities

For now it is not possible to pull the layer, unless they fix their geoserver request

**Comment by meomancer** [comment]
This is duplication of https://github.com/kartoza/IGRAC-GGIS/issues/618
