### ISSUE TITLE
Question about deleting organisation

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#614]
Hi @meomancer, if I delete an organisation from the system (from here https://ggis.un-igrac.org/en-us/admin/gwml2/organisation/) would also the data associated be deleted? (in this case, the wells and time series associated with that organisation?).

**Comment by meomancer** [comment]
Hi @clau1313 
Yes, it will delete all data associated with the organisation

**Comment by clau1313** [comment]
Thanks @meomancer
