### ISSUE TITLE
missing datasets

### ISSUE THREAD

**Issue by SterckxArnaud** [kartoza/IGRAC-GGIS#619]
We are missing the following layers:
- [x] https://ggis.un-igrac.org/catalogue/#/dataset/1533
- [x] https://ggis.un-igrac.org/catalogue/#/dataset/1392
- [x] https://ggis.un-igrac.org/catalogue/#/dataset/1294
- [x] https://ggis.un-igrac.org/catalogue/#/dataset/498
- [ ] https://ggis.un-igrac.org/catalogue/#/dataset/842

Could you please have a look?

**Comment by meomancer** [comment]
hi @NyakudyaA 
Could you help me check this?
https://ggis.un-igrac.org/catalogue/#/dataset/842

**Comment by NyakudyaA** [comment]
I can't find the following layer https://ggis.un-igrac.org/catalogue/#/dataset/842 in both staging DB and production. Can we get the original layer and load into the DB

**Comment by SterckxArnaud** [comment]
I deleted the missing layer (https://ggis.un-igrac.org/catalogue/#/dataset/842). It was not an important one.
