### ISSUE TITLE
Errors when uploading Excel file

### ISSUE THREAD

**Issue by seabilwe** [kartoza/IGRAC-GGIS#620]
Hi @meomancer 

Please see a ticket that has been logged through the support portal: https://kartoza.com/app/issue/ISS-2023-00034

**Priority: Medium**

See the attachment below from the ticket
[00_UK_wells.report.xlsx](https://github.com/kartoza/IGRAC-GGIS/files/13725697/00_UK_wells.report.xlsx)

**Comment by meomancer** [comment]
Hi @clau1313 

Please ignore the error on the empty row, i will check and fix it on Friday.

For the rows that has data, the error is "Country does not exist"
The value should be 'United Kingdom' or 'GBR'. We don't have any country named 'UK'.

**Comment by clau1313** [comment]
Hi @meomancer, oh sorry I should have seen the errors in the country column. Thanks for your help!

**Comment by meomancer** [comment]
Hi @clau1313 
Uploader is updated, now it will skip the empty rows

**Comment by clau1313** [comment]
Thanks @meomancer!
