### ISSUE TITLE
Error display layers

### ISSUE THREAD

**Issue by seabilwe** [kartoza/IGRAC-GGIS#621]
Hi @meomancer 

Please see this ticket logged in the support portal:https://kartoza.com/app/issue/ISS-2023-00035

**Priority: Medium**

**Comment by meomancer** [comment]
Some layers don't display properly. See for instance in the viewer [https://ggis.un-igrac.org/catalogue/#/map/1238](https://ggis.un-igrac.org/catalogue#/map/1238)

**Comment by meomancer** [comment]
Hi @SterckxArnaud 
This is fixed, could you check it?
