### ISSUE TITLE
Batch upload question

### ISSUE THREAD

**Issue by seabilwe** [kartoza/IGRAC-GGIS#622]
Hi @meomancer please see the ticket logged in from the support portal: https://kartoza.com/app/issue/ISS-2023-00036
Priority: Medium

cc @clau1313

**Comment by meomancer** [comment]
Good morning!

As you may know, we had a bit of trouble in the past uploading a file called "00 CZ all gwl 2023". I tried again just now, and I got a message saying "Sheet 'General Information' is needed". What does this mean? (that sheet was included in the file that includes the well locations, but I don't know what could be the issue with it now. The file is called "00 Location CZ wells").

After this, I checked the wells via Admin and it seems that the data was uploaded after all, perhaps in one of the previous sessions. Is there a way to be 100% sure that all the data from this file was uploaded?

Thank you!

Cheers,
Claudia

**Comment by meomancer** [comment]
hi @clau1313 

I think you were using General Information tab, not on the Monitoring Data

> Sheet 'General Information' is needed

Means that you are uploading using "General Information", but actually you are uploading Monitoring Data.
I will fix the error message to make it more understanding, but could you reupload using "Monitoring Data" tab?

**Comment by clau1313** [comment]
Hi @meomancer, thanks! I am uploading another file now but I will try again when that one is done.

**Comment by meomancer** [comment]
hi @clau1313 
Uploader is updated. The error message is more detailed.
![Selection_014](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/38eb945d-1d27-4aff-ab2b-fb558050e53a)

**Comment by clau1313** [comment]
Hi @meomancer, thank you. Regarding my other question, is there a way to be 100% sure that all the data from this file was uploaded?

**Comment by meomancer** [comment]
Hi @clau1313 
Currently usually for me, download the well for the country, and check it
For the data if it is saved or not, we can just reupload. If they are all skipped, everything is already saved

Or do you have any suggestion so i can implement it?

**Comment by meomancer** [comment]
We can close this
