### ISSUE TITLE
Error When choosing an organisation

### ISSUE THREAD

**Issue by seabilwe** [kartoza/IGRAC-GGIS#625]
Hi @meomancer a ticket has been opened in the support portal.
https://kartoza.com/app/issue/ISS-2024-00001

Hi,

it's Elie From IGRAC.
After creating an organization and adding the data to the organization, I am trying to make the organization available to see on the GGMN. However, when saving we have the following error pop up: b'The CQL source expression for attribute groundwater_level_data refers to attributes unavailable in the data source: [groundwater_level_data]'

I have added a screenshot too.

https://kartoza.com/files/Screenshot%202024-01-11%20102818.png

Priority: High

**Comment by MarinaKartoza** [comment]
Good morning! Since Irwan is on leave and this issue is critical, I have assigned Danang to look at this and give feedback/resolve the issue in Irwan's absence.

**Comment by MarinaKartoza** [comment]
Dear Ellie and IGRAC team

We had two resources looking into the error. Unfortunately we couldn't resolve.

Irwan will be working on Monday morning (15/1) to look into the issue and attempt to fix the error.
I trust this will be acceptable?

**Comment by meomancer** [comment]
Hi @clau1313 @Eliegergesgerges 
This is fixed, could you check it?

**Comment by meomancer** [comment]
I think we can close this for now
