### ISSUE TITLE
Map layers are not showing 

### ISSUE THREAD

**Issue by seabilwe** [kartoza/IGRAC-GGIS#628]
Issue sent through the support portal: https://kartoza.com/app/issue/ISS-2024-00002

Dear All,

It appears that none of our maps and map layers are visible on Geonode! We have a meeting scheduled in an hour and a half, and the maps are not displaying. What could be causing this issue?

Additionally, it's crucial to ensure that this problem is resolved promptly, and measures should be taken to prevent its recurrence in the future.
Can you manage to solve it now?

**Comment by NyakudyaA** [comment]
This is resolved now. All layers are rendering

**Comment by seabilwe** [comment]
Thanks @NyakudyaA 

cc @Eliegergesgerges

**Comment by Elie114** [comment]
Okey Thank you.

**Comment by SterckxArnaud** [comment]
Layers are back but I understand from Marina that it is a temporary fix, we need something permanent

**Comment by NyakudyaA** [comment]
@SterckxArnaud This is not a temporary fix, the server had some storage issues and this caused GeoServer to revert to an older version. That has been fixed

**Comment by SterckxArnaud** [comment]
Good to know, thank you Admire!
