### ISSUE TITLE
No Categorized Style Allowed!

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/IGRAC-GGIS#630]
Hello,

This is very urgent, we are uploading a map layer of wells. and we have a style based on categories for the slopes. However, when I upload the SLD style, all the data disappears and even when I was trying to edit it manually on the map layer on the geonode the category style.

we need the SLD file to work. Please A very early deadline!!!

Priority: High

**Comment by NyakudyaA** [comment]
@EliVolsch Can they share the SLD and the name of the layer they are trying to style

**Comment by Elie114** [comment]
YEs i will share it but also I was trying to change the color from a different layer which was already on the website, and we couldn't change the style (just the color) ! so it's not this SLD in specific

**Comment by Elie114** [comment]
[SenSlope_wells.zip](https://github.com/kartoza/IGRAC-GGIS/files/14039480/SenSlope_wells.zip)

**Comment by NyakudyaA** [comment]
@Elie114 Have you already uploaded the layer to the GeoNode, please share the link with me

**Comment by Elie114** [comment]
https://ggis.un-igrac.org/catalogue/#/dataset/2500

**Comment by NyakudyaA** [comment]
The uploaded layer is different to the shapefile
![image](https://github.com/kartoza/IGRAC-GGIS/assets/2510900/1d7402f0-e40d-4cee-a082-bb66650b6f3e)

vs shapefile
![image](https://github.com/kartoza/IGRAC-GGIS/assets/2510900/f8b64c5d-b7ae-4cca-8e42-0405e94e1fdd)

We missing the column `TheilSen s`

**Comment by NyakudyaA** [comment]
Is it not https://ggis.un-igrac.org/catalogue/#/dataset/2499 ?

**Comment by Elie114** [comment]
Yes the other link. Sorry for that

**Comment by NyakudyaA** [comment]
@Elie114 The layer still doesn't contain the column `TheilSen s`
![image](https://github.com/kartoza/IGRAC-GGIS/assets/2510900/7722f498-e396-4c81-85a0-d4f530d4e23e)

Each time you upload a layer to GeoNode, by convention it converts all the column names to lower case i.e `Station` becomes `station` so you need to make sure that your SLD is adjusted to those values. You can open the SLD in a text editor
and update `TheilSen s` to become `theilsen s`

**Comment by Elie114** [comment]
So i should delete the map layer and re-upload it ?

**Comment by Elie114** [comment]
https://ggis.un-igrac.org/catalogue/#/dataset/2500 

in this example, if i put edit style and i change the color or the symbol or anything and click apply it will not happen. I have an error.

**Comment by Elie114** [comment]
I am changing it manually using visual editor

**Comment by Elie114** [comment]
and Now i can't upload any layers anymore 
![Uploading WhatsApp Image 2024-01-24 at 4.52.45 PM.jpeg…]()

**Comment by meomancer** [comment]
Hi @Elie114 
It seems the error is you can't upload new layer with the same file name
It will gives error

The problem are:
1. The property name is "TheilSen s", it changed to "senslop" on the geoserver, that is because there is space in there (need to make sure no uppercase and space in the name)
2. The style also needs to change to correcy one

Please delete the current layers and reupload it using below file
[SenSlope_dataset.zip](https://github.com/kartoza/IGRAC-GGIS/files/14045761/SenSlope_dataset.zip)

- I changed "TheilSen s" to "theilsen_s"
- I changed also on sld file

![Selection_003](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/edfb6ad5-c913-478d-980c-d30d542e0f06)

**Comment by Elie114** [comment]
Thank you, Irwan for clarifying! 

So for the future, the attributes in the shapefile should all be lowercase and without spaces. Right?

**Comment by meomancer** [comment]
Yes @Elie114 
Because the data will be saved on database
But the column of database can't contains space

It seems geoserver rename the column because there is space

So to be safe, please use lowercase and without space

**Comment by Elie114** [comment]
https://ggis.un-igrac.org/catalogue/#/dataset/2503 

can you check this layer. I am trying to change the style just the color or the shape and I can't. Why ?

**Comment by meomancer** [comment]
Hi @Elie114 
It is using default style, so we can't change it (It is because of this ticket) : https://github.com/kartoza/IGRAC-GGIS/issues/326
Please upload with new sld for the style

**Comment by meomancer** [comment]
Hi @Elie114 
Could you confirm if this ticket is resolved or not?
For this comment https://github.com/kartoza/IGRAC-GGIS/issues/630#issuecomment-1909782508, 
please change style using sld upload.

**Comment by Elie114** [comment]
yes Irwan, it can be closed

**Comment by meomancer** [comment]
Thank you @Elie114
