### ISSUE TITLE
Add Salinity Tab in Excel file

### ISSUE THREAD

**Issue by seabilwe** [kartoza/IGRAC-GGIS#642]
Please see the ticket logged through the support portal: https://kartoza.com/app/issue/ISS-2024-00009

Dear Sir/Madam,

When uploading data to the GGMN, we use Excel. In the "Groundwater Quality" sheet, we would like to include the parameters "Salinity" with units in g/L. Since these parameters are not currently listed, we have the data available for them and can't upload them.

https://kartoza.com/private/files/Screenshot%202024-02-12%20134304.png

Best regards,
Elie

Priority: Medium

cc  @Elie114

**Comment by Elie114** [comment]
Hi @meomancer, 

Yes the upload is successful. 
Thank you, you can close this issue. By the way, why I can't close an issue by myself?
