### ISSUE TITLE
Dataset not downloadable

### ISSUE THREAD

**Issue by seabilwe** [kartoza/IGRAC-GGIS#643]
Issue logged in through the support portal: https://kartoza.com/app/issue/ISS-2024-00011

Dear colleagues, I get an error message when I try to download this dataset ([https://ggis.un-igrac.org/catalogue/#/dataset/2507)](https://ggis.un-igrac.org/catalogue#/dataset/2507))

![image](https://github.com/kartoza/IGRAC-GGIS/assets/56301949/24171022-d7ef-4f6c-a11b-2ad3dafd7483)

Priority: Medium

cc @SterckxArnaud

**Comment by meomancer** [comment]
Hi @NyakudyaA 
Could you help me check this ticket?
The error "Download Limits Exceeded."

**Comment by meomancer** [comment]
Hi @SterckxArnaud 

@NyakudyaA already checked and it seem the layer has illegal character
The layer name is groundwater:Dataset_(Jasechko_et_al._2024)

Could you change the layer name?

Thank you

**Comment by SterckxArnaud** [comment]
Thanks Irwan and Admire. What is the illegal character? the dot "."?

**Comment by meomancer** [comment]
Yes @SterckxArnaud , i think so

**Comment by SterckxArnaud** [comment]
We changed the name but it doesn't work neither. We tried without dot, without numbers...
We realized that the same issue occurs with the layer https://ggis.un-igrac.org/catalogue/#/dataset/2502

Moreover, the layers that we have created and subsequently deleted to test alternative layer names are still available in the GGIS:
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/e384b263-8880-484e-818c-d320ce905ed1)

![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/690b5109-b10a-403d-afe6-9d3fdc64e1ad)

**Comment by SterckxArnaud** [comment]
We still have an error when we try to download the layer

**Comment by meomancer** [comment]
Hi @SterckxArnaud 
This is fixed, could you try it?

**Comment by meomancer** [comment]
Please check the config change to default when geoserver is restarted

**Comment by meomancer** [comment]
Need geoserver expert to check how to make config persist
The config is for WPS is here
![Selection_120](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/f5f1887b-109d-47c7-ac8f-f4215285aba3)

**Comment by Jeremy-Prior** [comment]
@meomancer, going through the [geoserver documentation](https://docs.geoserver.org/main/en/user/services/wps/install.html#configuring-wps), it appears that the `maximum features` for the WPS are the same as those for WFS. 

![image](https://github.com/kartoza/IGRAC-GGIS/assets/100694811/0431a314-ca1d-411a-a760-772ae464e73a)

We could try setting the limit as 0 for the WFS?

**Comment by meomancer** [comment]
Hi @Jeremy-Prior 
Yes, that is the solution
https://github.com/kartoza/IGRAC-GGIS/issues/643#issuecomment-2014612472

The problem is we need to make it persistence, because every time geoserver is restarted, it will change back to default settings
I think we need to check with devops also

**Comment by meomancer** [comment]
Solution : https://github.com/kartoza/IGRAC-GGIS/issues/718
cc @EliVolsch 
We have updated and fixed it as @robertohuru suggestions
