### ISSUE TITLE
"Data download" instead of "Data request"

### ISSUE THREAD

**Issue by seabilwe** [kartoza/IGRAC-GGIS#644]
Issue logged in through the support portal: https://kartoza.com/app/issue/ISS-2024-00010

Dear colleagues, could you please edit the data download page as follow?

![image](https://github.com/kartoza/IGRAC-GGIS/assets/56301949/84be123f-99b2-4ee6-aa53-7a8fa566bf47)

Could you please also edit the url "https://ggis.un-igrac.org/groundwater/record/download-request" into "[https://ggis.un-igrac.org/groundwater/record/download"?](https://ggis.un-igrac.org/groundwater/record/download%22)

This is because the dataset is open since our last developments, and therefore it is no longer necessary to "request" the data.

Priority: Low

cc @SterckxArnaud

**Comment by SterckxArnaud** [comment]
I realize that the download bar is still called "Request" instead of "Download"
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/594ab443-423f-45cd-9696-622ea277273d)

**Comment by meomancer** [comment]
Hi @SterckxArnaud Updated and fixed on staging
