### ISSUE TITLE
GWML2

### ISSUE THREAD

**Issue by seabilwe** [kartoza/IGRAC-GGIS#645]
Issue logged through the support portal: https://kartoza.com/app/issue/ISS-2024-00013

Dear colleagues, a user asked us if the well and monitoring database in the GGIS complies with the GWML2, a derivative of the OGC WaterML standard. I remember that we considered the GWML2 when we built the database but eventually we deviated from it because a lot of GWML2 fields were not relevant for us. So our database does not follow the GWML2, however it could be mapped with the GWML2, like we did with SOS when developing our IstSOS service. Is that correct?

Priority: Medium

**Comment by meomancer** [comment]
Hi @SterckxArnaud 
Yes, we could mapping our data to gwml2 standard
But i'm not familiar with gwml2, is there any example or method for this?
And also as i remember istsos already provides gwml2 schema, maybe we also could implement it on istsos
