### ISSUE TITLE
Well and monitoring download file + ReadMe file

### ISSUE THREAD

**Issue by seabilwe** [kartoza/IGRAC-GGIS#646]
Issue logged in through the support portal: https://kartoza.com/app/issue/ISS-2024-00014

Dear colleagues, we would like our well and monitoring data download files to include a ReadMe file. Would it be possible to:
i) write and edit the content of the ReadMe file ourselves in Django?
ii) include in the ReadMe file an automatically-generated list of data providers (i.e. organizations)?

Priority: Medium

**Comment by meomancer** [comment]
> include in the ReadMe file an automatically-generated list of data providers (i.e. organizations)?

@SterckxArnaud 
Do you mean we need to generate Readme file per organisation? Or just put the list of organisation as content file?
Maybe it would be best if you could provide the example of content of Readme with data providers

**Comment by SterckxArnaud** [comment]
Hi Irwan, please find attached a draft ReadMe file. It includes a piece of text, that we would like to edit ourselves in Django, as well as a list of organizations, that could be automatically generated. 
[Readme.txt](https://github.com/kartoza/IGRAC-GGIS/files/14372532/Readme.txt)

**Comment by SterckxArnaud** [comment]
Thanks Irwan. @clau1313 and @Eliegergesgerges, can you please update the ReadMe file accordingly?

**Comment by clau1313** [comment]
@SterckxArnaud done!
