### ISSUE TITLE
Download well and monitoring data by data provider

### ISSUE THREAD

**Issue by seabilwe** [kartoza/IGRAC-GGIS#647]
Issue logged in through the support portal: https://kartoza.com/app/issue/ISS-2024-00015

Dear colleagues, when downloading well and monitoring data, you can define i) whether you want GGMN data or all well and monitoring data, and ii) for which country you want the data. Could we also let the user define from which data provider (i.e. organization) the data must be downloaded?

Priority:Medium

**Comment by meomancer** [comment]
Yes, we could @SterckxArnaud

**Comment by SterckxArnaud** [comment]
Where can I find the provisional developments?
