### ISSUE TITLE
Hide register button

### ISSUE THREAD

**Issue by seabilwe** [kartoza/IGRAC-GGIS#648]
Issue logged in through the support portal: https://kartoza.com/app/issue/ISS-2024-00016

Dear colleagues, we don't want the users to register in the GGIS unless they are close partners who want to upload data. This is clearly written in the registration page, however we still receive many registration applications. Would it be possible to hide the registration page, and to share the page only with users that we want to register?

Priority: Medium

**Comment by meomancer** [comment]
Hi @SterckxArnaud 
I think we could do like this?
1. Admin generate register page to someone with random url
2. We share the url
3. They register, the page is invalidated (because already being used)
4. And we hide current register page

What do you think?

**Comment by meomancer** [comment]
Hi @SterckxArnaud 
Still in PR

Now we can create link on django admin
![Selection_101](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/37af0b98-2393-4e1b-b512-f3ae1a2e9bb1)

When created we can just share the **Registration URL**
![Selection_103](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/144dbb78-2536-4500-8d0b-e8e2fca8dc5d)

Here is the example of url
![Selection_098](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/06b39489-958b-4aea-9988-e969bdb0b0f7)

When user is accessing older code that already being used
![Selection_100](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/9334584e-60d9-47b2-af2b-bb2ac6990718)

When user just access register url without code from admin, it will show
![Selection_099](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/22b49b99-cd32-4071-b941-1509588a0e15)

**NOTE**:
Currently i keep the link REGISTER url on navbar, so when user click it, it will show above page, to notify user that they need to request registration link

**Comment by SterckxArnaud** [comment]
Thanks Irwan, I would suggest the following text:

**Registration page is not valid**
Please request a valid registration link to the website administrator: ggis@un-igrac.org

**Registration page on request only**
Registration is only for data providers. It is not required to access and download the resources available in the GGIS. If you are from a partner organization and you have data that could be shared in the GGIS, please reach out to the website administrator: ggis@un-igrac.org

**Comment by meomancer** [comment]
Hi @SterckxArnaud 
Updated and deployed to production
