### ISSUE TITLE
Improve access to well and monitoring download

### ISSUE THREAD

**Issue by seabilwe** [kartoza/IGRAC-GGIS#649]
Issue logged in through the support portal: https://kartoza.com/app/issue/ISS-2024-00017

Dear colleagues, when consulting the well and monitoring datasets in the GGIS, our users are provided with a standard download button. However, this download button will only provide them with a shapefile of the layer, not with the well and monitoring data. For that, the users need to go to a specific page, under the Data tab. We are concern that some of our users might not find their way to this page. Is there a way we could improve that?

![E3oQskV](https://github.com/kartoza/IGRAC-GGIS/assets/56301949/28646af1-0b23-4e0a-9cd1-dd6579b375d8)

Priority: Medium

**Comment by meomancer** [comment]
hi @SterckxArnaud 
Maybe on that button, we can redirect them to the download page

**Comment by SterckxArnaud** [comment]
That would be great! However this redirect should apply only to the map layers created out of the Well and Monitoring Database.
