### ISSUE TITLE
APi France

### ISSUE THREAD

**Issue by seabilwe** [kartoza/IGRAC-GGIS#650]
Issue logged in through the support portal: https://kartoza.com/app/issue/ISS-2024-00018

Dear colleagues, we set up an automatic connection to fetch groundwater monitoring data from France automatically, in 2022. However, we only have the data after the connection was made. I looked at the documentation on the French website and it seems that it is also possible to fetch historical data (prior to 2022). See for instance [https://hubeau.eaufrance.fr/sites/default/files/api/demo/piezo/piezo.htm?code_dpt=01&code_bss=06027X0001%2FF.](https://hubeau.eaufrance.fr/sites/default/files/api/demo/piezo/piezo.htm?code_bss=06027X0001%2FF.&code_dpt=01) We just need to use a different request, which is described under "2. Récupérer la chronique piézométrique complète du piézomètre 06252X0063/PZ1 identifié à l'étape précédente" in the page https://hubeau.eaufrance.fr/page/api-piezometrie. Could you please have a look? 
In addition, the connection currently retrieves data from all observation wells. Our colleagues from the French Geological Survey have advised us to use a subset of the observation wells (see attached). Could you please restrict the data to these particular wells?

[Selected wells.xlsx](https://github.com/kartoza/IGRAC-GGIS/files/14296126/Selected.wells.xlsx)

Priority: Medium

**Comment by meomancer** [comment]
Hi @SterckxArnaud 
Currently we are using this API:
https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques_tr?fields=date_mesure,profondeur_nappe&code_bss=04808X0027/N11&sort=desc&page=1

It provides hourly data (we already save it), but it just provide data in last 1 year

For fetching older data, we can use
https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques?fields=date_mesure,profondeur_nappe&code_bss=04808X0027/N11&sort=desc&page=1

But it just provides daily data

What do you think? Should we keep the daily data to get older data? 
And keep the latest data with hourly data?

**Comment by meomancer** [comment]
Hi @SterckxArnaud 
The data is quite strange
It is for **08635X0015/LZG211**

Here is the data hourly:
https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques_tr?fields=date_mesure,profondeur_nappe&code_bss=08635X0015/LZG211&sort=desc&page=1&date_fin_mesure=2024-01-14&date_debut_mesure=2024-01-13

```
{"date_mesure":"2024-01-13T23:00:00Z","profondeur_nappe":0.134},
{"date_mesure":"2024-01-13T22:00:00Z","profondeur_nappe":0.133},
{"date_mesure":"2024-01-13T21:00:00Z","profondeur_nappe":0.133},
{"date_mesure":"2024-01-13T20:00:00Z","profondeur_nappe":0.133},
{"date_mesure":"2024-01-13T19:00:00Z","profondeur_nappe":0.133},
{"date_mesure":"2024-01-13T18:00:00Z","profondeur_nappe":0.133},
{"date_mesure":"2024-01-13T17:00:00Z","profondeur_nappe":0.132},
{"date_mesure":"2024-01-13T16:00:00Z","profondeur_nappe":0.133},
{"date_mesure":"2024-01-13T15:00:00Z","profondeur_nappe":0.133},
{"date_mesure":"2024-01-13T14:00:00Z","profondeur_nappe":0.133},
{"date_mesure":"2024-01-13T13:00:00Z","profondeur_nappe":0.133},
{"date_mesure":"2024-01-13T12:00:00Z","profondeur_nappe":0.133},
{"date_mesure":"2024-01-13T11:00:00Z","profondeur_nappe":0.133},
{"date_mesure":"2024-01-13T10:00:00Z","profondeur_nappe":0.133},
{"date_mesure":"2024-01-13T09:00:00Z","profondeur_nappe":0.133},
{"date_mesure":"2024-01-13T08:00:00Z","profondeur_nappe":0.133},
{"date_mesure":"2024-01-13T07:00:00Z","profondeur_nappe":0.132},
{"date_mesure":"2024-01-13T06:00:00Z","profondeur_nappe":0.133},
{"date_mesure":"2024-01-13T05:00:00Z","profondeur_nappe":0.134},
{"date_mesure":"2024-01-13T04:00:00Z","profondeur_nappe":0.134},
{"date_mesure":"2024-01-13T03:00:00Z","profondeur_nappe":0.133},
{"date_mesure":"2024-01-13T02:00:00Z","profondeur_nappe":0.134},
{"date_mesure":"2024-01-13T01:00:00Z","profondeur_nappe":0.134},
{"date_mesure":"2024-01-13T00:00:00Z","profondeur_nappe":0.133}
```

But using data daily (for older data), the data is negative
https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques?fields=date_mesure,profondeur_nappe&code_bss=08635X0015/LZG211&sort=desc&page=1&date_fin_mesure=2024-01-14&date_debut_mesure=2024-01-13
```
{"date_mesure":"2024-01-13","profondeur_nappe":-0.13}
```

Could we confirm with them?
What data should we use? 
- The daily (that contains older data)
- The hourly (just the last 3 months)

If we decide using daily, i think we need to clean all measurements on france to make it consistence. Current data in our server is hourly.

**Comment by SterckxArnaud** [comment]
Hi Irwan, daily data is more than enough, we don't need hourly data. I believe the data is negative because that request expresses water table depth in negative values, whereas the previous request expresses it in positive values.

**Comment by meomancer** [comment]
Ok @SterckxArnaud 
Because there is different data between daily and hourly, i will delete all of measurements and refetch everything for daily data
To prevent issue on graph above
What do you think?

**Comment by SterckxArnaud** [comment]
> Ok @SterckxArnaud Because there is different data between daily and hourly, i will delete all of measurements and refetch everything for daily data To prevent issue on graph above
> 
Yes!
> And also on this ticket, we need to limit wells by the codes by this [file](https://github.com/kartoza/IGRAC-GGIS/files/14296126/Selected.wells.xlsx). Should we also delete wells that are not in this wells? I think currently we save all of wells.
> 
Let's keep all the wells (sorry for this last minute change of mind)

**Comment by meomancer** [comment]
> Let's keep all the wells (sorry for this last minute change of mind)

No worries @SterckxArnaud 
I have made the settings on django admin if we need to limit the wells

**Comment by SterckxArnaud** [comment]
Hi Irwan, I had a look at the data from France and I see that many wells have records only from 1st of October 2022 onwards. With the new request we should see data prior to 1/10/2022. Are you sure it works properly?

**Comment by meomancer** [comment]
Hi @SterckxArnaud 
Here is the API that we are using for france for getting stations
https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/stations?format=json&nb_mesures_piezo_min=2&size=10&page=1

**Comment by meomancer** [comment]
Hi @SterckxArnaud 
Maybe we can ask the list of stations?
Our harvester is already able to filter stations by the list of **code_bss**

**Comment by meomancer** [comment]
Hi @SterckxArnaud The harvester is still running, i will ping in this ticket after it is done
The time to finish the harvester should be fast in future
Currently it is slow because we need to delete the old data and refetch everything

**Comment by SterckxArnaud** [comment]
Hi Irwan, you put this ticket under Review, is the data harvesting job done? We currently have 13219 wells with a least 2 measurements (excepted one with 1 measurement, 1192C30040/SD1BA)

**Comment by meomancer** [comment]
Hi @SterckxArnaud I'm sorry, it is not done yet
I put it to correct column again
Will put to review if it is done to be checked

**Comment by SterckxArnaud** [comment]
Hi Irwan, can you please estimate the time left before the entire dataset becomes available in the GGIS? We have an important deadline coming up for which we need these data.

**Comment by meomancer** [comment]
Hi @SterckxArnaud 
Harvester is still running, hopefully can be done in 6 hours
Currently when i write this comments, the stations that are saved is 14.977 of 15.076

I also found there is consistency from their API

Example for code **00191X0293/PZ5**

On the stations API, it returns with the minimum 2 measurements
On the response it has 77 measurements
https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/stations?code_bss=00191X0293/PZ5&format=json&nb_mesures_piezo_min=2&page=1&size=20

Meanwhile on the measurements API, it does not have any measurements
https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques?size=500&fields=date_mesure,profondeur_nappe&code_bss=00191X0293/PZ5&sort=asc

So for france, there will be some of wells that we are saved but does not have measurements

> We currently have 13219 wells with a least 2 measurements (excepted one with 1 measurement, 1192C30040/SD1BA)
Now it has 4 measurements :
https://ggis.un-igrac.org/en-us/admin/gwml2/well/?q=1192C30040%2FSD1BA&o=3.1&organisation__id__exact=21

**Comment by meomancer** [comment]
Hi @SterckxArnaud 
The harvesting is done

The total wells that are saved is 15.074 of 15.076
There are 2 wells that does not have geometry
1129ZZ0012/SAF1
1129ZZ0013/SAF2

On well and monitoring data
![Selection_005](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/f95608bf-ae36-4616-804d-33b1d0b6b1e2)

On ggmn
![Selection_004](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/b46212f2-d19c-4234-9482-6e0ac3b5f6c5)
