### ISSUE TITLE
Problem with United States Data

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/IGRAC-GGIS#653]
Hi,

When I download the data from the GGMN for the United States and try to unzip the folder, it gives me an error: saying the compressed file is empty. However, the size is 500 MBs.
Please this is urgent as we are processing a report and we need the data from the United states.

Regards,
Elie

**Comment by meomancer** [comment]
Hi @Eliegergesgerges 
It is fixed, could you try redownload?

**Comment by meomancer** [comment]
hi @Eliegergesgerges 
Is it fixed? Could we close it?

**Comment by Elie114** [comment]
Yes, it is fixed! You can close it 

Thanks
