### ISSUE TITLE
Data In GGMN: Sweden

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/IGRAC-GGIS#657]
I can see on the GGMN, that some points in Sweden go until February 2024.
However, when I download the data it goes maximum till mid-2023. We need the data for a report and also the user should be able to download what he sees.

**Comment by meomancer** [comment]
Hi @Eliegergesgerges 
I have fixed the download data, could you check it?

There is bug on harvester that it does not run the data cache for being downloaded
I will fix it tomorrow and also release it

**Comment by Elie114** [comment]
Yes, Thank you! 
I have the data now.

**Comment by meomancer** [comment]
I have fixed the harvester
But we need to check it after wednesday to check if download contains latest data (the harvesters run every wednesday midnight)

**Comment by SterckxArnaud** [comment]
@Elie114, can you please check and close the ticket if everything ok?

**Comment by Elie114** [comment]
@SterckxArnaud Yes it is good now! 
However, I can't close tickets still :D
