### ISSUE TITLE
GGMN: Well for US in China

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/IGRAC-GGIS#660]
I found a problem on GGMN - there's a well in China listed as belonging to the United States, and it's empty. I'm not sure if it's from our API, but it would be great if we could check and remove it. I have attached a screenshot.

**Comment by meomancer** [comment]
I have deleted it
I think there was error on cida and they already deleted it
This is the original url from cida: https://cida.usgs.gov/ngwmn/provider/MWA/site/3847/ which is not found anymore
