### ISSUE TITLE
Data From United States through API

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/IGRAC-GGIS#663]
Issue logged in through the support portal: [https://kartoza.erpnext.com/app/issue/ISS-2024-00027](https://kartoza.erpnext.com/app/issue/ISS-2024-00027)

Priority: Medium

I have received this email from USGS to whom the GGMN is connecting to their data through API:

Great to hear from you. It'd help to know a bit about how you are hitting our API - and what data you're requesting. It sounds like you may only be querying sites owned by USSGS - but again I can't be sure. Can you share how you're hitting our services? 

Can you please help me to answer her question, How are we hitting their API?

**Comment by meomancer** [comment]
Hi @Eliegergesgerges 
We are using this one
https://cida.usgs.gov/ngwmn/geoserver/wfs?request=GetFeature&SERVICE=WFS&VERSION=1.0.0&srsName=EPSG%3A4326&outputFormat=GML2&typeName=ngwmn%3AVW_GWDP_GEOSERVER&CQL_FILTER=((WL_SN_FLAG%20%3D%20%271%27)%20AND%20(WL_WELL_TYPE%20%3D%20%272%27))

Which is just **Water Level** and just **Monitor Category = Trend**

![Selection_119](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/4b47ff2f-3673-49d7-bd99-ddeb9e9d52e8)

Do we need to also fetch all category?
If all category, the well is around 17.659

**Comment by Elie114** [comment]
Yes, we need to get all the wells if possible.

**Comment by meomancer** [comment]
As per discussuon, we just fetch surveillance and trend

**Comment by Elie114** [comment]
ok Great

**Comment by SterckxArnaud** [comment]
We are supposed to fetch 12.784 wells, at the moment we have only 11.341 of them.
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/d3d33acf-6a5a-4ebe-b888-65b4355111c1)

**Comment by SterckxArnaud** [comment]
When you download the GGMN data from the United States, you get 7648 wells. Is the harvester still running? Is the cache being generated?

**Comment by meomancer** [comment]
Hi @SterckxArnaud The harvester is still running, i will ping after it is done

**Comment by meomancer** [comment]
Hi @SterckxArnaud 
harvesting is done, but the number of well being saved is 11.606
i will check the missing one on my next igrac time

**Comment by SterckxArnaud** [comment]
Thank you Irwan, it seems that we are getting there. We should not be storing data that are no longer on the data provider's server. Is there a way our harvester can handle that?

**Comment by meomancer** [comment]
Hi @SterckxArnaud 

TODO:
I will update harvesters to clean the wells before harvesting
By checking all of wells on providers and remove the missing one on our server

**Comment by meomancer** [comment]
Hi @SterckxArnaud 
Now the data is already correct
Harvester will unassign the wells that are not on the remote server to empty organisation (not delete it)

This is on well and monitoring data
![Selection_001](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/b08d439d-21c4-47f5-84b3-ee61bcd6a524)

This is ggmn
![Selection_002](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/0dee08bd-52c9-4c7f-ad7e-75415f50ed92)

GGMN are not same with well and monitoring data because there are wells that does not have measurement, because our rule for ggmn is the wells that have measurement
