### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/IGRAC-GGIS#664]
Hi,

I am trying to create a dashboard for the GGMN. I add the map first, then I would like to add a widget, chart, and table .... linked to the GGMN map. However, I can't. I have attached the error.

Priority: Medium

![image](https://github.com/kartoza/IGRAC-GGIS/assets/107027990/28a1df33-368c-4ddd-8f3e-50ad38d1a33f)

**Comment by meomancer** [comment]
Hi @Eliegergesgerges 
What layer that you were selected on above image?

I see that you are able to create chart, is that the error before?
https://ggis.un-igrac.org/catalogue/#/dashboard/2506

**Comment by meomancer** [comment]
Hi @Eliegergesgerges 
This is fixed, could you check it?

**Comment by Elie114** [comment]
Yes, it works we can close this one
