### ISSUE TITLE
monitoring wells in wrong country

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/IGRAC-GGIS#675]
Priority: Medium

At the moment, the country in which a well is located is determined based on its location (as far as I can remember). However, some wells located near the border are assigned to the neighbouring country. See for example [https://ggis.un-igrac.org/groundwater/record/5657/.](https://ggis.un-igrac.org/groundwater/record/5657) It is in Canada, monitored by the Canadian geological survey, but the GGIS says it is in the US. Maybe we need to improve the resolution of the country border map that is used in the background?

**Comment by meomancer** [comment]
Hi @SterckxArnaud @clau1313 @Eliegergesgerges 
This is fixed, could you check it?

**Comment by SterckxArnaud** [comment]
Hi Irwan, this one well is fixed but it was only one example, there are issues with other wells (see for instance https://ggis.un-igrac.org/groundwater/record/393518/). What would be your strategy to fix this?

**Comment by meomancer** [comment]
Hi @SterckxArnaud 
The data is coming from the server
That well is : https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/stations?code_bss=04461X0015%2FECH&format=json&size=20

The location = [7.56697633644756,47.6331104173063]
On the map : https://www.google.com/maps/search/47.6331104173063+7.56697633644756?sa=X&ved=1t:242&ictx=111
It falls on germany instead france

![Selection_138](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/9637a461-4765-4c0c-852a-9891f51e8f80)

So in here not sure how to fix it, maybe we need to change it manually
When the country of well changed manually, it will not be changed anymore by harvester

**Comment by SterckxArnaud** [comment]
We could maybe determine the country based on the data provider, but there must have been a reason why we didn't do that in the first place when we developed the GGIS. @clau1313, can you remember something about the country location of the wells?

**Comment by meomancer** [comment]
hi @SterckxArnaud @SterckxArnaud 
Yes, we could develop it, but there also some data provider that are in multiple countries
That why it does not doing like that in first place 

Maybe we could develop, if the provider has country, it will assign all of data to that country

**Comment by meomancer** [comment]
Hi @SterckxArnaud @clau1313 
This already being developed and deployed to staging

On organisation on django admin, we can assign a country to it.
If it is being assigned, all of well will be assigned to that country. If not, it will use geometry of country to check the well.

![Selection_003](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/5dfbcfd4-7b77-4941-a8a8-a73e537f61b5)

**Comment by SterckxArnaud** [comment]
Thank you Irwan, I tested it and it works fine! @Eliegergesgerges, could you please assign their countries to the national organizations?

**Comment by meomancer** [comment]
Hi @SterckxArnaud @Eliegergesgerges 
I will ping after it is deployed to production

**Comment by Eliegergesgerges** [comment]
Hi, 
I have attached a screenshot, I  don't have the country feature. 
<img width="823" alt="Screenshot 2024-05-01 092638" src="https://github.com/kartoza/IGRAC-GGIS/assets/147037867/a31517a9-72b5-4fa4-83e6-c279fc52615a">

**Comment by SterckxArnaud** [comment]
Sorry Elie, it is not yet in the production environment, it will be released very soon.

**Comment by SterckxArnaud** [comment]
Hi @Eliegergesgerges, it is in production now. Could you please update the country for each organization? It would also be the opportunity to edit the description of each organization, telling our users what data are available from each organization (in particular if we don't have the full dataset in the GGMN).
