### ISSUE TITLE
Data from Austria - eHYD

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/IGRAC-GGIS#676]
There are 231 wells in the GGMN coming from eHYD, but it seems that we are receiving data from only 96 of them. Can you please have a look at this? Thanks.

**Comment by meomancer** [comment]
hi @SterckxArnaud @clau1313 Will check it on harvester

**Comment by meomancer** [comment]
hi @SterckxArnaud @clau1313 
It is coming from the files

For example for number 4002603
On all of the files, the measurement is just
`26.03.2024 00:00:00 RWLuecke`

![Selection_139](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/c9c3e872-fc57-4f43-aef3-65758e7d7489)

That why it is empty

Should we ask eHYD why there is no measurements for specific station on files?
Everyting is just **RWLuecke**

**Comment by SterckxArnaud** [comment]
RW Luecke is a data gap. I suppose that the station has not been measured.
