### ISSUE TITLE
Change files to ods instead xlsx

### ISSUE THREAD

**Issue by meomancer** [kartoza/IGRAC-GGIS#684]
This is based on requests:
https://github.com/kartoza/IGRAC-GGIS/issues/583#issuecomment-1976301091

We need to change using ods instead xlsx
The places:
- Download data
- Batch upload

I think we can update the above while working on updating ods

**Comment by meomancer** [comment]
Hi @clau1313 @SterckxArnaud 
I have tried find the good open source library
When we convert or use ods, the styling is disappeared.
So i'm not sure we could use ods

From this (xlsx)
![Selection_010](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/ee20ff2b-9d51-4050-9eb7-70ac47822e91)

To this (ods)
![Selection_011](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/685cccf5-04bd-4811-a622-ba1afdc1f7f9)

**Comment by SterckxArnaud** [comment]
Hi Irwan, upload files are now in ods format, good! However the download files are still in xlsx format.

**Comment by meomancer** [comment]
Hi @SterckxArnaud 
Fixed on staging, but the cache generator is still running, will be finished the end of today
