### ISSUE TITLE
Changing the GGIS style

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/IGRAC-GGIS#692]
Good morning,
IGRAC is changing its brand image, and this means that some styles changes need to be applied in the GGIS. These are: replacing the logo, changing the color palette and changing the typeface.
To start making a rough plan, I would like to know if it would be possible to make these changes by next Thursday and Friday (16-17 May). We will send you the details of the exact changes once he hear from you. Thank you!
PS: In the meantime, which file type do you need for logo?

**Comment by meomancer** [comment]
Hi @SterckxArnaud @clau1313 @EliVolsch 
Yes, it is possible, i could spend 1 or 2 days to work on it.
I have slot for IGRAC 2 days before 16-17 May, and i could move it after i get the details of changes

**Comment by clau1313** [comment]
Hi @Irwan, great! @Stefansiepman can you please include here the details of the changes?

**Comment by Stefansiepman** [comment]
Hi @meomancer, I'll come back with a doc with typeface and colour usage guidelines, but hereby already the logo kit. 
[Uploading logo_colour_RGB.zip…]()

**Comment by meomancer** [comment]
Hi @Stefansiepman 
I think the above file is still uploading
Could you reupload?

**Comment by Stefansiepman** [comment]
[logo_colour_RGB.zip](https://github.com/kartoza/IGRAC-GGIS/files/15291004/logo_colour_RGB.zip)

**Comment by meomancer** [comment]
Thank you @Stefansiepman 
Could you provide the details for this tickets? cc @clau1313

**Comment by Stefansiepman** [comment]
[GGIS_visual-identity.xlsx](https://github.com/kartoza/IGRAC-GGIS/files/15304591/GGIS_visual-identity.xlsx)
Hi Irwan, I hope this gives some clarity. If not, feel free to let me know and we could walk through it together in a video call. Other question, when do you think these changes will be submitted? Friday? Because then we plan all other changes and communications around the same day.

**Comment by meomancer** [comment]
Hi @Stefansiepman it is hard for me to identify it using text
Could you maybe help me provide using sigma?
Or could you provide screenshot and and use text to tell which and how it should changes?

**Comment by meomancer** [comment]
> Other question, when do you think these changes will be submitted? Friday? Because then we plan all other changes and communications around the same day.

It depend, if i got the details (from above comment), i could work on it tomorrow
We can deploy and test it on Thursday and release it on Friday

**Comment by Stefansiepman** [comment]
![GGIS_visual-identity_01](https://github.com/kartoza/IGRAC-GGIS/assets/64906896/e5e60f08-0db3-42d2-b1bc-88bed768da11)
![GGIS_visual-identity_02](https://github.com/kartoza/IGRAC-GGIS/assets/64906896/399b5c3b-bca7-4983-933a-23b6b5fe953a)
![GGIS_visual-identity_03](https://github.com/kartoza/IGRAC-GGIS/assets/64906896/361c8e9d-8627-438d-8f17-4d372bd14347)
![GGIS_visual-identity_04](https://github.com/kartoza/IGRAC-GGIS/assets/64906896/94908b3b-c9d0-45eb-bf3f-facf6e70230f)
![GGIS_visual-identity_05](https://github.com/kartoza/IGRAC-GGIS/assets/64906896/da90dd9a-887a-45e2-989f-0dd35b92f17d)
![GGIS_visual-identity_06](https://github.com/kartoza/IGRAC-GGIS/assets/64906896/f843016b-72c6-4c2b-9d55-256f50488594)
[GGIS_visual-identity.xlsx](https://github.com/kartoza/IGRAC-GGIS/files/15305272/GGIS_visual-identity.xlsx)

**Comment by Stefansiepman** [comment]
I also updated the excel sheet with codes that refer to the images
[GGIS_visual-identity.zip](https://github.com/kartoza/IGRAC-GGIS/files/15305296/GGIS_visual-identity.zip)

**Comment by meomancer** [comment]
Thank you so much @Stefansiepman

**Comment by meomancer** [comment]
Hi @Stefansiepman @clau1313 
I have updated the code for new style
Could you check and review it on staging?
https://staging.igrac.kartoza.com/

**Comment by Stefansiepman** [comment]
Looks good, thanks for the work you put into it! One minor thing, which wasn't specifically mentioned in the excel sheet, is related to the 'home' button. Could you align its hover colour to that of the menu bars? Because it's currently still orange

**Comment by meomancer** [comment]
Hi @Stefansiepman I have updated it but my connection is bad to update the staging one
Can you check below video?
https://github.com/kartoza/IGRAC-GGIS/assets/4530905/a9932a50-ee28-4be3-ba2f-d28503a6d09f

If it is ok, i could release it tomorrow

CC @SterckxArnaud @clau1313

**Comment by Stefansiepman** [comment]
Excellent work @meomancer! Thanks! Case closed
