### ISSUE TITLE
GGIS very slow and logo shifted up

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/IGRAC-GGIS#694]
- [ ] Dear colleagues, the GGIS is very slow today, it takes ages before the data appear on the maps, and sometimes it simply fails:
![image](https://github.com/kartoza/IGRAC-GGIS/assets/107027990/c6ab1667-cd3d-44d0-b60e-5ccbc0357646)

I had the same issue last week already.

- [x] In addition, I remarked that the IGRAC logo shifts up when opening mapstore,
![image](https://github.com/kartoza/IGRAC-GGIS/assets/107027990/33ad91ee-ab6c-48f5-9181-b90fa4c17973)

**Comment by SterckxArnaud** [comment]
I see that the logo is rightly positioned now but I still struggle to access the data

**Comment by meomancer** [comment]
Hi @SterckxArnaud 
We are still checking for geoserver issue

**Comment by SterckxArnaud** [comment]
Hi Irwan, we really need to move on on this GeoServer issue, the GGIS has not been functional for 2 weeks now
