### ISSUE TITLE
Data type: GGMN by default

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/IGRAC-GGIS#697]
Priority: Medium
Good morning,

I would like to ask if you could set "GGMN" as the default option in the dropdown menu on our Data Download page, instead of "Well and Monitoring data. Thanks.

![image](https://github.com/kartoza/IGRAC-GGIS/assets/107027990/b7ac98fa-4409-4320-92ac-d99087ac6a6e)

**Comment by meomancer** [comment]
We need to hardcoded it, i will update it

**Comment by meomancer** [comment]
hi @clau1313 
This is already updated

**Comment by clau1313** [comment]
hi @meomancer, thanks! I will check when the GGMN is up again

**Comment by clau1313** [comment]
It's working, thanks @meomancer!
