### ISSUE TITLE
Separating GGMN data and Well and Monitoring data

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/IGRAC-GGIS#700]
Good afternon,

We are wondering if it is feasible to separate the GGMN and Well and Monitoring data, since some users have been experiencing some confusion when downloading the two data sets. We would like to:
Keep the GGMN as it is
Change the name of "Well and Monitoring data" to "Other data" in the dropdown menu, and change the dataset to include only data that is not in the GGMN (e.g. Jasechko data).

![image](https://github.com/kartoza/IGRAC-GGIS/assets/107027990/9e475043-6ab5-4458-a59c-1eef095cf34b)

Is this possible? Thank you.

**Comment by meomancer** [comment]
Yes, it is possible @clau1313

**Comment by clau1313** [comment]
hi @meomancer, thanks. Then, can you please make the changes?

**Comment by meomancer** [comment]
Hi @clau1313 
This is already implemented, could you check it?
