### ISSUE TITLE
API Netherlands

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/IGRAC-GGIS#705]
Priority: Medium
Dear Irwan, groundwater monitoring data from the Netherlands can be fetched through REST API. You will find the different requests available here: [https://publiek.broservices.nl/gm/gld/v1/swagger-ui/#/](https://publiek.broservices.nl/gm/gld/v1/swagger-ui#/)

We would like to fetch the monitoring data belonging to the following data providers:

-  Provincie Drenthe | 01179514 (​B)
-  Provincie Flevoland | 32164140 (​B)
-  Provincie Fryslân | 01178978 (​B)
-  Provincie Gelderland | 51468751 (​B)
-  Provincie Groningen | 01182023 (​B)
-  Provincie Limburg | 50052969 (​B)
-  Provincie Noord-Brabant | 17278718 (​B)
-  Provincie Noord-Holland | 34362354 (​B)
-  Provincie Overijssel | 51048329 (​B)
-  Provincie Utrecht | 30277172 (​B)
-  Provincie Zeeland | 20168636 (​B)
-  Provincie Zuid-Holland | 27375169 (​B)
- 
You can retrieve the monitoring stations available for each data provider using the following request: 

`https://publiek.broservices.nl/gm/gld/v1/bro-ids?bronhouder=51048329`
where "bronhouder" expects the ID of the data provider. 

Could you please have a look and explore whether it would be possible to get the data in the GGMN?

**Comment by SterckxArnaud** [comment]
Hi Irwan, we have been in contact with the data providers and there are few requests that we could use to fetch the data. Before that, we (at IGRAC) need to figure out what data we want to fetch. We will let you know once we have made our decision.

**Comment by meomancer** [comment]
Hi @SterckxArnaud 
I would like to work on this next week, is there any detail for this?

**Comment by SterckxArnaud** [comment]
Hi Irwan, there are some issues with the Dutch database, which is still in development. Let's close this issue and come back to it once their database is ready
