### ISSUE TITLE
Change sftp container to use minio bucket

### ISSUE THREAD

**Issue by meomancer** [kartoza/IGRAC-GGIS#710]
# Problem
New infra does not have sftp container, so we need to ask eHYD to push to our minio

# Solution
- [x] Create igrac bucket on Kartoza minio
- [x] Copy all of current sftp content to new minio
- [x] Change harvester to access minio
- [x] Add client key and gives write access to client (key is forwarded by email)

**Comment by EliVolsch** [comment]
@meomancer is this ticket still relevant?

**Comment by meomancer** [comment]
Hi @EliVolsch 
I think this is done

**Comment by EliVolsch** [comment]
@meomancer I agree, we can close this one
