### ISSUE TITLE
Test new infrastructure

### ISSUE THREAD

**Issue by meomancer** [kartoza/IGRAC-GGIS#711]
# Problem
We need to test our new infrastructure

# Solution
- [x] Test batch upload
- [x] Check all datasets
- [ ] Test upload datasets

**Comment by EliVolsch** [comment]
Run scripted tests

#### Tests:
- [ ] Previous scripted tests (Old tests)
- [ ] Staging scripted tests
- [ ] Provide feedback report

**Comment by EliVolsch** [comment]
Tests have been conducted and all completed successfully
