### ISSUE TITLE
Layers not available

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/IGRAC-GGIS#717]
Priotiy: High

The layers in the GGIS are not available

![image](https://github.com/user-attachments/assets/7a9d90ea-f3e8-46ff-ae89-31b1b58867a2)

**Comment by EliVolsch** [comment]
@SterckxArnaud It seem like the issue has been fixed. Can you please check if the issues still persists on your end? 

![image](https://github.com/user-attachments/assets/67dfbb60-aa48-491e-ba7a-4f8a037f47c5)

**Comment by SterckxArnaud** [comment]
Yes, thank you for fixing the issue promptly!
