### ISSUE TITLE
Edit download.properties file (#643) in the Geoserver data directory

### ISSUE THREAD

**Issue by robertohuru** [kartoza/IGRAC-GGIS#718]
Hi @meomancer,

Resolving issue #643 requires updating the `download.properties` file which is found in the root of the GeoServer data directory.

I would like to suggest the following options:
1. Locate `download.properties` and update the maxFeatures value to 0.
```maxFeatures=0```

**Automate fix on restarts**
2 If not exist inside GeoServer data directory, create a new file `download.properties`, replace its content with below configuration text and mount it to `/spcgeonode-geodatadir/download.properties` inside the geoserver service.
```
# download.properties
hardOutputLimit=52428800
rasterSizeLimits=64000000
maxAnimationFrames=0
writeLimits=64000000
compressionLevel=4
maxFeatures=0
```

cc: @tharanathkartoza @EliVolsch

**Comment by meomancer** [comment]
Thank you so much @robertohuru 
This is works on docker compose, but we need to update it on rancher or kubernetes to mount the individual file, but i'm not sure it is possible or not.

Could we maybe put the file on entrypoint scripts to replace the file? We could create new geoserver image for that

**Comment by meomancer** [comment]
Hetzner : I have placed the file so that when it restarts, the configuration still persists.
DO: @tharanathkartoza has placed the file, and the configuration is already persistent.

CC @EliVolsch
