### ISSUE TITLE
Wells ground water level 503 issue

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/IGRAC-GGIS#720]
I found an issue with the ground level report on the wells and monitoring data page, on DO. When i select a point from the map I get a 503 error in the information pane on the right. This seems to be the case for all the points.

[https://igrac.do.kartoza.com/view/well-and-monitoring-data/](https://igrac.do.kartoza.com/view/well-and-monitoring-data/)

![image](https://github.com/user-attachments/assets/2d26baec-2163-4e7d-acd8-1f5a00e303a4)
 

Here is a view from the [https://ggis.un-igrac.org/view/well-and-monitoring-data/](https://ggis.un-igrac.org/view/well-and-monitoring-data/) platform of what is expected
![image](https://github.com/user-attachments/assets/670c5f47-a9ff-43ea-b87d-9343a9a27fcb)

**Comment by EliVolsch** [comment]
@meomancer is this ticket still relevant? I believe the issue has been addressed by updating the resources of the server.

**Comment by meomancer** [comment]
Yes, i think it is already fixed @EliVolsch 
We can reopen if it is still happens
