### ISSUE TITLE
 TBA viewer not available

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/IGRAC-GGIS#729]
Priority: High

This viewer is not available: https://ggis.un-igrac.org/view/tba

![image](https://github.com/user-attachments/assets/41795bf4-47be-40ba-9c9d-7289fb3d54bc)

**Comment by robertohuru** [comment]
@EliVolsch vewer is available for authenticated users.

**Comment by EliVolsch** [comment]
@SterckxArnaud the map is viewer is available when logged in as pointed out. It seems like it may be sharing permissions problem. 

@robertohuru from the share tab I can see that anyone can view, however I don't think this setting has applied, or there may be an issue with the permissions?
![image](https://github.com/user-attachments/assets/35253640-3527-49ed-a1b8-86b7d8426dd2)

**Comment by SterckxArnaud** [comment]
Any update colleagues to restore this viewer?

**Comment by meomancer** [comment]
Hi @SterckxArnaud and @EliVolsch 
This is fixed

**Comment by EliVolsch** [comment]
I can confirm that I was able to view the dataset without being authenticated. Thank you

![image](https://github.com/user-attachments/assets/e429e8f0-65d2-4e0b-8a3b-b40f5b08362a)
