### ISSUE TITLE
GGMN metadata

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/IGRAC-GGIS#737]
Good afternoon, I would like to edit the GGMN metadata, but now I see that there are 3 GGMN layers. Which one is the one I should edit? and why do we have 3 GGMN layers? Thanks!

![image](https://github.com/user-attachments/assets/5eea031b-8b22-44a4-90aa-e5ff55e56f9a)

Claudia

**Comment by meomancer** [comment]
Hi @clau1313 
![IGRAC 2](https://github.com/user-attachments/assets/f6541706-2e09-413f-813c-94f06d15a3e8)

(1) is layer (can be seen by database like icon)
(2) is map (can be seen by map icon)
(3) is layer

(1) is layer, that is being used by GGMN map
(2) is GGMN map on home page
(3) is the old one, i'm not sure what is using it and why recreate the layer before, maybe we can unpublish it

**Comment by clau1313** [comment]
hi @meomancer, thanks for the clarification. With unpublish it, do you mean to delete it? but then are we sure that this won't cause any problem?

**Comment by clau1313** [comment]
The wells are back! So I guess the problem was solved.

**Comment by meomancer** [comment]
Hi @clau1313 
Not delete it, but making it unpublished

![Selection_028](https://github.com/user-attachments/assets/aca8852c-8c64-4067-b7ed-d99443b0f381)

**Comment by clau1313** [comment]
Thanks for the clarification @meomancer. Then yes, can you please unpublish the old GGMN layer?

**Comment by meomancer** [comment]
Hi @clau1313 Done
Now it is being hidden for users, except admin

Non logged in
![Selection_041](https://github.com/user-attachments/assets/6edbb1ae-84d8-4ed9-b24b-fcb386d47783)

Admin
![Selection_040](https://github.com/user-attachments/assets/2772b439-8dbe-43b9-abfa-fd51f000e5aa)
