### ISSUE TITLE
GGMN wells disappeared

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/IGRAC-GGIS#738]
Good afternoon,

The GGMN wells dissapeared from the viewer. Can you please look into it? Thanks!

![image](https://github.com/user-attachments/assets/722d8bdc-dddc-4907-9a0e-4bb515a9bcdd)

**Comment by clau1313** [comment]
The wells are back! So I guess the problem was solved, thanks.

**Comment by meomancer** [comment]
Hi @clau1313 
The database was down, we will finding out to keep the database up

Thank you
