### ISSUE TITLE
Security Issue on GGMN Website

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/IGRAC-GGIS#740]
My colleague Claudia cannot access the GGMN website (ggmn.un-igrac.org) due to a security error related to HTTPS. Could you kindly look into this issue and let me know when it has been resolved?
Best regards,
Elie

![image](https://github.com/user-attachments/assets/059527d4-e0aa-4922-bffa-71e895f5bb91)

**Comment by meomancer** [comment]
Hi @clau1313 
cc @EliVolsch @lgkgh 

We need to ask you to change ggmn.un-igrac.org pointing to 188.166.194.173, please?

Thank you

**Comment by clau1313** [comment]
Hi @meomancer, thanks. @Stefansiepman can you please look into this?

**Comment by clau1313** [comment]
@meomancer done, problem solved.

Next time, can you please inform us in advance when we need to do this kind of changes? Thanks.
