### ISSUE TITLE
Follow-Up on Issue Submission

### ISSUE THREAD

**Issue by Eliegergesgerges** [kartoza/IGRAC-GGIS#741]
<img width="379" alt="Screenshot 2024-11-27 165918" src="https://github.com/user-attachments/assets/59c9c132-c3fc-45c5-b206-daf90711c745">

Hi,

I hope you're doing well. I wanted to check if you can see the issues I submitted. I usually receive a reply, but this time I haven’t seen any response.

This is a bit urgent, as we are currently unable to upload monitoring data to the GGMN.

I would appreciate your assistance with this.

Best regards,
Elie

**Comment by meomancer** [comment]
This is already covered on other tickets
