### ISSUE TITLE
Deleting Uploads

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/IGRAC-GGIS#744]
Can you please remove these three rows?
Is there a way for me to delete the rows myself as well?

![image](https://github.com/user-attachments/assets/e7de074f-ef72-4671-b75f-b385e8319cb6)

Best,
Elie

**Comment by meomancer** [comment]
Hi @Eliegergesgerges 
I have deleted it, could you check it?

**Comment by meomancer** [comment]
Hi @Eliegergesgerges 
There is delete button now, could you test it?

**Comment by Eliegergesgerges** [comment]
Yes it works perfectly Thanks !

**Comment by Elie114** [comment]
We can close this issue
