### ISSUE TITLE
Can't Access the GGIS or the GGMN all morning

### ISSUE THREAD

**Issue by Eliegergesgerges** [kartoza/IGRAC-GGIS#748]
<img width="290" alt="Screenshot 2024-12-05 112712" src="https://github.com/user-attachments/assets/3d320a51-c5e5-4014-8e14-70877b6db100">

This is happening all morning and from different laptops!

**Comment by meomancer** [comment]
Hi @Eliegergesgerges 
Database is down, please retry it

**Comment by Eliegergesgerges** [comment]
Yes works now

**Comment by meomancer** [comment]
Thank you so much @Eliegergesgerges 
We are still busy to improve the stability on the database

**Comment by Eliegergesgerges** [comment]
No Problem! Thank you :)

**Comment by Elie114** [comment]
We can close this issue
